// @generated by @frameless/solid; do not edit.
// Solid event batching exposes final post-dispatch state while preserving authored write order (T004b); no deferred notifications are needed.
function Frame(props) {
	return <section data-frame>{props.children}</section>;
}
export function SlotPage() {
	return (
		<Frame>
			<strong data-projected-node>Projected composition</strong>
		</Frame>
	);
}
