// @generated by @frameless/solid; do not edit.
// Solid event batching exposes final post-dispatch state while preserving authored write order (T004b); no deferred notifications are needed.
import { createSignal, createContext, useContext } from 'solid-js';
function createCompositionSharedShared() {
	const [count, setCount] = createSignal(0);
	const [history, setHistory] = createSignal('seed');
	const [audit, setAudit] = createSignal('pending');
	const advance = () => {
		setHistory(`${history()}:${count()}`);
		setCount(count() + 1);
		setAudit(`${history()}|${count()}`);
	};
	const append = () => {
		setHistory(`${history()}!`);
	};
	return { count, history, audit, advance, append };
}
const CompositionSharedContext = createContext();
function useCompositionShared() {
	const value = useContext(CompositionSharedContext);
	if (!value) {
		throw new Error('useCompositionShared is missing its provider');
	}
	return value;
}
export function CompositionSharedProvider(props) {
	const value = createCompositionSharedShared();
	return (
		<CompositionSharedContext.Provider value={value}>
			{props.children}
		</CompositionSharedContext.Provider>
	);
}
function Incrementer() {
	const shared = useCompositionShared();
	return (
		<>
			<button
				data-action="advance-shared"
				onClick={() => {
					shared.advance();
				}}
			>
				Advance
			</button>
			<button
				data-action="append-shared"
				onClick={() => {
					shared.append();
				}}
			>
				Append
			</button>
		</>
	);
}
function Reader() {
	const shared = useCompositionShared();
	return <output data-shared-reader>{`${shared.history()}|${shared.count()}`}</output>;
}
function SharedAudit() {
	const shared = useCompositionShared();
	return <output data-shared-audit>{shared.audit()}</output>;
}
export function SharedParticipants() {
	return (
		<>
			<Incrementer />
			<Reader />
			<SharedAudit />
		</>
	);
}
