// @generated by @frameless/solid; do not edit.
// Solid event batching exposes final post-dispatch state while preserving authored write order (T004b); no deferred notifications are needed.
import { onMount, onCleanup } from 'solid-js';

function FocusField(props) {
	const attachHost = (node) => {
		onMount(() => {
			let cleanup = undefined;
			cleanup = ((node) => {
				const localState = node.parentElement?.querySelector('[data-handle-state]');
				let witness = document.querySelector('body > [data-handle-witness]');
				if (witness === null) {
					witness = document.createElement('section');
					witness.dataset.handleWitness = '';
					witness.innerHTML = '<output data-handle-state></output>';
					document.body.append(witness);
				}
				if (localState !== null) localState.textContent = 'set';
				const externalState = witness.querySelector('[data-handle-state]');
				if (externalState !== null) externalState.textContent = 'set';
				return () => {
					if (localState !== null) localState.textContent = 'cleared';
					if (externalState !== null) externalState.textContent = 'cleared';
				};
			})(node);
			onCleanup(() => {
				if (typeof cleanup === 'function') {
					cleanup();
					cleanup = undefined;
				}
			});
		});
	};
	return (
		<input
			data-focus-target
			ref={(node) => {
				props.input(node);
				onCleanup(() => props.input(undefined));
				attachHost(node);
			}}
		/>
	);
}

export function FocusPage() {
	let input;
	return (
		<section data-handle-witness>
			<output data-handle-state />
			<FocusField input={(node) => (input = node)} />
			<button
				data-action="focus-composed"
				onClick={() => {
					input?.focus();
				}}
			>
				Focus
			</button>
		</section>
	);
}
