// @generated by @frameless/solid; do not edit.
// Solid event batching exposes final post-dispatch state while preserving authored write order (T004b); no deferred notifications are needed.
import { createSignal, createEffect, onMount, onCleanup } from 'solid-js';
export function CleanupPage() {
	const [behaviorInput, setBehaviorInput] = createSignal('one');
	const attachHost = (node) => {
		onMount(() => {
			let behaviorInputInput = behaviorInput();
			let cleanup = undefined;
			cleanup = ((node) => {
				let witness = document.querySelector('body > [data-composition-witness]');
				if (witness === null) {
					witness = document.createElement('section');
					witness.dataset.compositionWitness = '';
					witness.innerHTML =
						'<output data-composition-cleanup></output><output data-behavior-log></output>';
					document.body.append(witness);
				}
				const localState = node.querySelector('[data-composition-cleanup]');
				const externalState = witness.querySelector('[data-composition-cleanup]');
				const localLog = node.querySelector('[data-behavior-log]');
				const externalLog = witness.querySelector('[data-behavior-log]');
				const append = (entries) => {
					const prior = externalLog?.textContent ?? '';
					const next = prior === '' ? entries.join('|') : `${prior}|${entries.join('|')}`;
					if (localLog !== null) localLog.textContent = next;
					if (externalLog !== null) externalLog.textContent = next;
				};
				if (localState !== null) localState.textContent = 'attached';
				if (externalState !== null) externalState.textContent = 'attached';
				append([`install:A:${behaviorInputInput}`, `install:B:${behaviorInputInput}`]);
				return () => {
					append([`cleanup:B:${behaviorInputInput}`, `cleanup:A:${behaviorInputInput}`]);
					if (localState !== null) localState.textContent = 'cleaned';
					if (externalState !== null) externalState.textContent = 'cleaned';
				};
			})(node);
			let behaviorInputsReady = false;
			createEffect(() => {
				const behaviorInputInputNext = behaviorInput();
				const behaviorChanged = behaviorInputInputNext !== behaviorInputInput;
				if (!behaviorInputsReady) {
					behaviorInputsReady = true;
					return;
				}
				if (behaviorChanged && typeof cleanup === 'function') {
					cleanup();
					cleanup = undefined;
				}
				behaviorInputInput = behaviorInputInputNext;
				if (behaviorChanged) {
					cleanup = ((node) => {
						let witness = document.querySelector('body > [data-composition-witness]');
						if (witness === null) {
							witness = document.createElement('section');
							witness.dataset.compositionWitness = '';
							witness.innerHTML =
								'<output data-composition-cleanup></output><output data-behavior-log></output>';
							document.body.append(witness);
						}
						const localState = node.querySelector('[data-composition-cleanup]');
						const externalState = witness.querySelector('[data-composition-cleanup]');
						const localLog = node.querySelector('[data-behavior-log]');
						const externalLog = witness.querySelector('[data-behavior-log]');
						const append = (entries) => {
							const prior = externalLog?.textContent ?? '';
							const next =
								prior === '' ? entries.join('|') : `${prior}|${entries.join('|')}`;
							if (localLog !== null) localLog.textContent = next;
							if (externalLog !== null) externalLog.textContent = next;
						};
						if (localState !== null) localState.textContent = 'attached';
						if (externalState !== null) externalState.textContent = 'attached';
						append([
							`install:A:${behaviorInputInput}`,
							`install:B:${behaviorInputInput}`,
						]);
						return () => {
							append([
								`cleanup:B:${behaviorInputInput}`,
								`cleanup:A:${behaviorInputInput}`,
							]);
							if (localState !== null) localState.textContent = 'cleaned';
							if (externalState !== null) externalState.textContent = 'cleaned';
						};
					})(node);
				}
			});
			onCleanup(() => {
				if (typeof cleanup === 'function') {
					cleanup();
					cleanup = undefined;
				}
			});
		});
	};
	return (
		<section data-composition-witness ref={attachHost}>
			<output data-composition-cleanup />
			<output data-behavior-log />
			<button
				data-action="change-behavior-input"
				onClick={() => {
					setBehaviorInput('two');
				}}
			>
				Change behavior input
			</button>
		</section>
	);
}
