// @generated by @frameless/solid; do not edit.
// Solid event batching exposes final post-dispatch state while preserving authored write order (T004b); no deferred notifications are needed.
import { createSignal, createContext, useContext } from 'solid-js';

function createPropsValueShared() {
	const [value] = createSignal(5);
	return { value };
}

const PropsValueContext = createContext();

function usePropsValue() {
	const value = useContext(PropsValueContext);
	if (!value) {
		throw new Error('usePropsValue is missing its provider');
	}
	return value;
}

export function PropsValueProvider(props) {
	const value = createPropsValueShared();
	return <PropsValueContext.Provider value={value}>{props.children}</PropsValueContext.Provider>;
}

function PropsReader() {
	const shared = usePropsValue();
	return <output data-tier-props>{shared.value()}</output>;
}

export function PropsPage() {
	return <PropsReader />;
}
