// @generated by @frameless/solid; do not edit.
// Solid event batching exposes final post-dispatch state while preserving authored write order (T004b); no deferred notifications are needed.
import { createSignal, createContext, useContext } from 'solid-js';

function createFullPairShared() {
	const [left] = createSignal(7);
	const [right] = createSignal('seven');
	return { left, right };
}

const FullPairContext = createContext();

function useFullPair() {
	const value = useContext(FullPairContext);
	if (!value) {
		throw new Error('useFullPair is missing its provider');
	}
	return value;
}

export function FullPairProvider(props) {
	const value = createFullPairShared();
	return <FullPairContext.Provider value={value}>{props.children}</FullPairContext.Provider>;
}

function FullPairFirst() {
	const pair = useFullPair();
	return <output data-tier-object="first">{`${pair.left()}|${pair.right()}`}</output>;
}

function FullPairSecond() {
	const pair = useFullPair();
	return <output data-tier-object="second">{`${pair.left()}|${pair.right()}`}</output>;
}

export function ObjectPage() {
	return (
		<>
			<FullPairFirst />
			<FullPairSecond />
		</>
	);
}
