// @generated by @frameless/solid; do not edit.
// Solid event batching exposes final post-dispatch state while preserving authored write order (T004b); no deferred notifications are needed.
import { createSignal } from 'solid-js';
function createPageLedgerShared() {
	const [count, setCount] = createSignal(0);
	const increment = () => {
		setCount(count() + 1);
	};
	return { count, increment };
}
const pageLedgerShared = createPageLedgerShared();
function usePageLedger() {
	return pageLedgerShared;
}
export function PageLedger() {
	const ledger = usePageLedger();
	return (
		<>
			<button
				data-action="increment-page-tier"
				onClick={() => {
					ledger.increment();
				}}
			>
				Increment
			</button>
			<output data-tier-page>{ledger.count()}</output>
		</>
	);
}
