// @generated by @frameless/solid; do not edit.
// Solid event batching exposes final post-dispatch state while preserving authored write order (T004b); no deferred notifications are needed.
export function Panel(props) {
	return (
		<section data-panel>
			<h2 data-panel-label>{props.label}</h2>
			<div data-panel-body>{props.children}</div>
		</section>
	);
}
