import { mkdir, mkdtemp, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'pathe';
import { fileURLToPath } from 'node:url';
import { dirname } from 'pathe';
import { afterEach, describe, expect, test } from 'vitest';

const PACKAGE_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
import {
	checkGeneratedFiles,
	checkSources,
	discoverGeneratedFiles,
	REACT_GATE_POLICIES,
} from '../src/gate/index.ts';

const temporaryRoots: string[] = [];
afterEach(async () => {
	await Promise.all(
		temporaryRoots.splice(0).map((root) => rm(root, { recursive: true, force: true })),
	);
});

const valid = `import { useState } from 'react';
export function Mutant({ items = [] }) {
  const [value, setValue] = useState(0);
  return <section><button onClick={() => {
    const nextValue = value + 1;
    setValue(nextValue);
  }}>change</button><ul>{items.map((item) => <li key={item.id}>{item.id}</li>)}</ul></section>;
}`;

async function policies(source: string): Promise<string[]> {
	const result = await checkSources([{ file: 'generated/Mutant.jsx', source }]);
	expect(result.violations.every((entry) => /^T002 ruling \d+$/.test(entry.dossierRef))).toBe(true);
	return result.violations.map((entry) => entry.policy);
}

describe('React dossier gate', () => {
	test('publishes a dossier reference on every policy object', () => {
		expect(REACT_GATE_POLICIES.length).toBeGreaterThan(0);
		expect(REACT_GATE_POLICIES.every((policy) => /^T002 ruling \d+$/.test(policy.dossierRef))).toBe(true);
	});

	test('discovers, parses, and accepts every checked-in generated component', async () => {
		expect(await discoverGeneratedFiles()).toEqual([
			'generated/S1.jsx',
			'generated/S2.jsx',
			'generated/S3.jsx',
		]);
		const result = await checkGeneratedFiles();
		expect(result.violations, JSON.stringify(result.violations, null, 2)).toEqual([]);
		for (const file of result.files) {
			expect(await readFile(resolve(PACKAGE_ROOT, file), 'utf8')).toContain('@generated by @frameless/react');
		}
	});

	test.each([
		['unused import', valid.replace('useState }', 'useMemo, useState }'), 'react-import-allowlist'],
		['React recommended rule', valid.replace('<section>', '<section class="bad">'), 'eslint:react/no-unknown-property'],
		['Hooks recommended rule', valid.replace("import { useState }", "import { useEffect, useState }").replace('const [value', 'useEffect(() => { console.log(items); }, []);\n  const [value'), 'eslint:react-hooks/exhaustive-deps'],
		['index key AST', valid.replace('key={item.id}', 'key={index}').replace('(item) =>', '(item, index) =>'), 'index-key'],
		['index key plugin', valid.replace('key={item.id}', 'key={index}').replace('(item) =>', '(item, index) =>'), 'eslint:react/no-array-index-key'],
		['render aliased setter', valid.replace('return <section>', 'const update = setValue;\n  update(1);\n  return <section>'), 'render-phase-setter'],
		['render member-wrapped setter', valid.replace('return <section>', 'const updates = { run: setValue };\n  updates.run(1);\n  return <section>'), 'render-phase-setter'],
		['aliased setter', valid.replace('const nextValue = value + 1;\n    setValue(nextValue);', 'const update = setValue;\n    update(value + 1);\n    update(value + 2);'), 'one-call-per-setter'],
		['member-wrapped setter', valid.replace('const nextValue = value + 1;\n    setValue(nextValue);', 'const updates = { run: setValue };\n    updates.run(value + 1);\n    updates.run(value + 2);'), 'one-call-per-setter'],
		['helper-wrapped render setter', valid.replace('return <section>', 'const update = () => setValue(1);\n  update();\n  return <section>'), 'render-phase-setter'],
		['disable directive', `/* eslint-disable no-unused-vars */\n${valid}`, 'eslint-directive'],
		['enable directive', `/* eslint-enable no-unused-vars */\n${valid}`, 'eslint-directive'],
		['inline rule config', `/* eslint no-unused-vars: "off" */\n${valid}`, 'eslint-directive'],
		['undisclosed require', valid.replace('const [value', "const fs = require('node:fs'); fs;\n  const [value"), 'undisclosed-import'],
		['undisclosed dynamic import', valid.replace('const [value', "import('elsewhere');\n  const [value"), 'undisclosed-import'],
		['dead expression', valid.replace('return <section>', 'value;\n  return <section>'), 'eslint:no-unused-expressions'],
		['unreachable statement', valid.replace('return <section>', 'if (items.length) return null;\n  return null;\n  value;\n  return <section>'), 'eslint:no-unreachable'],
		['hook after guard', valid.replace('const [value', 'if (!items.length) return null;\n  const [value'), 'hook-after-guard'],
		['aliased useEffect', valid.replace("import { useState }", "import { useEffect as useSideEffect, useState }").replace('const [value', 'useSideEffect(() => {});\n  const [value'), 'render-phase-effect'],
		['aliased useLayoutEffect', valid.replace("import { useState }", "import { useLayoutEffect as layout, useState }").replace('const [value', 'layout(() => {});\n  const [value'), 'render-phase-effect'],
		['aliased useInsertionEffect', valid.replace("import { useState }", "import { useInsertionEffect as insert, useState }").replace('const [value', 'insert(() => {});\n  const [value'), 'render-phase-effect'],
		['react import allowlist', valid.replace('useState }', 'useCallback, useState }'), 'react-import-allowlist'],
		['forwardRef import', valid.replace('useState }', 'forwardRef, useState }'), 'no-forwardRef'],
		['forwardRef member', `import { useState } from 'react'; import React from 'react';\n${valid.split('\n').slice(1).join('\n')}\nReact.forwardRef(() => null);`, 'no-forwardRef'],
		['string ref', valid.replace('<section>', '<section><div ref="legacy" />'), 'no-forwardRef'],
		['controlled input', valid.replace('<section>', '<section><input value={value} />'), 'controlled-input'],
		['onInput', valid.replace('<section>', '<section><input value={value} onInput={() => {}} />'), 'on-input'],
		['let in handler', valid.replace('const nextValue = value + 1;', 'let nextValue = value + 1;'), 'const-only-handlers'],
		['two setter calls', valid.replace('setValue(nextValue);', 'setValue(nextValue);\n    setValue(nextValue + 1);'), 'one-call-per-setter'],
		['nonliteral direct state initial', valid.replace('useState(0)', 'useState(items.length)'), 'use-state-initializer'],
		['leaked render', valid.replace('{items.map', '{items.length && items.map'), 'eslint:react/jsx-no-leaked-render'],
		['missing map key', valid.replace(' key={item.id}', ''), 'key-required'],
		['wrong component shape', valid.replace('function Mutant({ items = [] })', 'const Mutant = ({ items = [] }) =>'), 'component-shape'],
		['visible ref', valid.replace('useState }', 'useRef, useState }').replace('const [value, setValue] = useState(0);', 'const visible = useRef(0);\n  const [value, setValue] = useState(0);').replace('<section>', '<section>{visible.current}'), 'ref-visibility'],
		['render-read setup ref', valid.replace('useState }', 'useRef, useState }').replace('const [value, setValue] = useState(0);', 'const setupDone = useRef(null);\n  if (setupDone.current === null) setupDone.current = true;\n  const leaked = setupDone.current;\n  leaked;\n  const [value, setValue] = useState(0);'), 'ref-visibility'],
		['boolean setup guard', valid.replace('useState }', 'useRef, useState }').replace('const [value, setValue] = useState(0);', 'const setupDone = useRef(null);\n  if (!setupDone.current) setupDone.current = true;\n  const [value, setValue] = useState(0);'), 'ref-guard-shape'],
		['foreign import', `import value from 'elsewhere';\n${valid}`, 'undisclosed-import'],
	])('rejects the %s bypass mutation', async (_name, source, policy) => {
		expect(await policies(source)).toContain(policy);
	});

	test('a newly added generated file is discovered and cannot bypass the gate', async () => {
		// macOS tmpdir is a symlink (/var -> /private/var); ESLint compares realpaths
		// against cwd and silently ignores files that appear outside it.
		const root = await realpath(await mkdtemp(resolve(tmpdir(), 'frameless-react-gate-')));
		temporaryRoots.push(root);
		await mkdir(resolve(root, 'generated'));
		// Base no-unused-expressions does not flag `void` expressions; use a bare
		// literal expression, which it unambiguously reports.
		await writeFile(resolve(root, 'generated/New.jsx'), `${valid}\n0;\n`);
		const result = await checkGeneratedFiles({ cwd: root });
		expect(result.files).toEqual(['generated/New.jsx']);
		expect(result.violations.map((entry) => entry.policy)).toContain('eslint:no-unused-expressions');
	});
});
