<!-- @generated by @frameless/svelte from Panel; do not edit. -->
<script lang="ts">
	let { label, children } = $props();
</script>

<section data-panel
	><h2 data-panel-label>{label}</h2
	><div data-panel-body
		>{@render children?.()}</div
></section>
