<!-- @generated by @frameless/svelte from ComposedPage; do not edit. -->
<script lang="ts">
	import Panel from './M1-panel.svelte';
</script>

<Panel label={'Composed'}
	><p data-panel-copy>Projected across the module boundary</p
></Panel>
