import { readFile } from 'node:fs/promises';
import type { EnrichedIR } from '@frameless/compiler';
import { resolve } from 'pathe';
import { describe, expect, test } from 'vitest';
import { emit } from '../src/emitter/index.ts';
import {
	checkGeneratedFiles,
	checkSources,
	discoverGeneratedFiles,
	QWIK_GATE_POLICIES,
} from '../src/gate/index.ts';

const packageRoot = resolve(import.meta.dirname, '..');
const compilerGoldenRoot = resolve(packageRoot, '../../compiler/test/goldens');

async function golden(name: string): Promise<EnrichedIR> {
	return JSON.parse(
		await readFile(resolve(compilerGoldenRoot, name), 'utf8'),
	) as EnrichedIR;
}

describe('Qwik v2 dossier gate', () => {
	test('publishes independent source and artifact-required policies', () => {
		expect(QWIK_GATE_POLICIES.slice(0, 2)).toEqual([
			{ id: 'no-visible-task', dossierRef: 'T002-qwik-architecture D8' },
			{
				id: 'persistence-render-lowering',
				dossierRef: 'T002-qwik-architecture D8',
			},
		]);
		// Qwik's own lint rules, added by T006 to close the gate asymmetry with
		// React and Solid. These are a third-party arbiter: they encode what the
		// Qwik team considers correct, not what we decided.
		expect(QWIK_GATE_POLICIES.slice(2).map((policy) => policy.id)).toEqual([
			'eslint:qwik/use-method-usage',
			'eslint:qwik/no-react-props',
			'eslint:qwik/jsx-key',
			'eslint:qwik/jsx-no-script-url',
			'eslint:qwik/no-use-visible-task',
			'eslint:qwik/scope-use-task',
			'eslint:qwik/no-async-prevent-default',
			'eslint:qwik/prefer-classlist',
			'eslint:qwik/serializer-signal-usage',
			'eslint:qwik/unused-server',
			'eslint:qwik/jsx-img',
			'eslint:qwik/jsx-a',
		]);
		expect(
			QWIK_GATE_POLICIES.filter((policy) => policy.requiresArtifact).map(
				(policy) => policy.id,
			),
		).toEqual(['persistence-render-lowering']);
	});

	test('discovers and accepts the clean S1/S2/S3 emitted corpus', async () => {
		expect(await discoverGeneratedFiles()).toEqual([
			'generated/S1.jsx',
			'generated/S2.jsx',
			'generated/S3.jsx',
		]);
		const result = await checkGeneratedFiles();
		// KNOWN-FAILING EXPECTATION, per T003 Ruling 5. Qwik's own
		// no-async-prevent-default rule flags generated/S3.jsx:38 - the emitter
		// puts event.preventDefault() inside an async QRL, where Qwik says it
		// cannot work. That is a real emitter defect and is NOT suppressed here:
		// this goal's charter forbids changing emitter behavior from a testing
		// task. See docs/goals/frameless-testing-ci-v1/notes/
		// findings-003-qwik-async-preventdefault.md.
		//
		// This is exact equality, so if the emitter is fixed and the violation
		// disappears, this test fails and forces the finding to be closed
		// deliberately rather than drifting shut.
		expect(result.violations, JSON.stringify(result.violations, null, 2)).toEqual([
			{
				file: 'generated/S3.jsx',
				policy: 'eslint:qwik/no-async-prevent-default',
				dossierRef: 'frameless-testing-ci-v1 T003 ruling 2',
				message:
					'This is an asynchronous function and does not support preventDefault. \nUse preventDefault attributes instead',
				line: 38,
			},
		]);
		expect(result.unevaluated).toEqual([
			{ policy: 'persistence-render-lowering', reason: 'requires-artifact' },
		]);
		expect(Object.keys(result)).toEqual(['files', 'policies', 'violations']);
		for (const file of result.files)
			expect(await readFile(resolve(packageRoot, file), 'utf8')).toContain(
				'@generated by @frameless/qwik',
			);
	});

	test('MUTATION: rejects an injected useVisibleTask$ in emitted source', async () => {
		const source = await readFile(resolve(packageRoot, 'generated/S1.jsx'), 'utf8');
		const mutant = source
			.replace('useTask$ }', 'useTask$, useVisibleTask$ }')
			.replace(
				'export const RenderOnce',
				'useVisibleTask$(() => {});\n\nexport const RenderOnce',
			);
		const result = await checkSources([
			{ file: 'generated/VisibleTaskMutant.jsx', source: mutant },
		]);
		expect(result.violations.map((entry) => entry.policy)).toContain('no-visible-task');
		expect(
			result.violations.filter((entry) => entry.policy === 'no-visible-task'),
		).toEqual(
			expect.arrayContaining([
				expect.objectContaining({
					dossierRef: 'T002-qwik-architecture D8',
					line: 2,
				}),
			]),
		);
	});

	test('MUTATION: persistence-bearing IR fails closed in the gate and emitter', async () => {
		const artifact = structuredClone(await golden('s1-render-once.json')) as EnrichedIR;
		(artifact.records.persistence as unknown[]).push({ graphNodeId: 'state:count' });
		const source = await readFile(resolve(packageRoot, 'generated/S1.jsx'), 'utf8');
		const result = await checkSources([
			{ file: 'generated/PersistenceMutant.jsx', source, artifact },
		]);
		expect(result.unevaluated).toEqual([]);
		expect(result.violations).toEqual([
			expect.objectContaining({
				policy: 'persistence-render-lowering',
				dossierRef: 'T002-qwik-architecture D8',
			}),
		]);
		expect(() => emit(artifact)).toThrow('does not support persistence-bearing IR');
	});
});

// CALIBRATION for the eslint policies added by T006. A gate rule nobody has
// watched reject something is not evidence it works. Each case feeds the gate
// source that violates one Qwik rule and proves the violation is reported under
// that rule's policy id.
describe('MUTATION: Qwik lint policies reject violating emitted source', () => {
	const cases = [
		{
			rule: 'qwik/jsx-key',
			source: `export const C = () => <ul>{[1, 2].map((n) => <li>{n}</li>)}</ul>;`,
		},
		{
			rule: 'qwik/no-react-props',
			source: `export const C = () => <div className="x" />;`,
		},
		{
			rule: 'qwik/jsx-no-script-url',
			source: `export const C = () => <a href="javascript:void(0)">x</a>;`,
		},
		{
			rule: 'qwik/jsx-img',
			source: `export const C = () => <img src="/a.png" />;`,
		},
	];

	for (const { rule, source } of cases) {
		test(`${rule} is caught`, async () => {
			const result = await checkSources([{ file: 'generated/Mutant.jsx', source }]);
			const policies = result.violations.map((violation) => violation.policy);
			expect(policies, JSON.stringify(result.violations, null, 2)).toContain(
				`eslint:${rule}`,
			);
		});
	}

	test('the clean corpus does not trip these same rules', async () => {
		const result = await checkGeneratedFiles();
		const tripped = new Set(result.violations.map((violation) => violation.policy));
		for (const { rule } of cases) expect(tripped).not.toContain(`eslint:${rule}`);
	});
});
