import { readFile } from 'node:fs/promises';
import type { EnrichedIR } from '@frameless/compiler';
import { resolve } from 'pathe';
import { describe, expect, test } from 'vitest';
import { emit } from '../src/emitter/index.ts';
import {
	checkGeneratedFiles,
	checkSources,
	discoverGeneratedFiles,
	QWIK_GATE_POLICIES,
} from '../src/gate/index.ts';

const packageRoot = resolve(import.meta.dirname, '..');
const compilerGoldenRoot = resolve(packageRoot, '../../compiler/test/goldens');

async function golden(name: string): Promise<EnrichedIR> {
	return JSON.parse(
		await readFile(resolve(compilerGoldenRoot, name), 'utf8'),
	) as EnrichedIR;
}

describe('Qwik v2 dossier gate', () => {
	test('publishes independent source and artifact-required policies', () => {
		expect(QWIK_GATE_POLICIES).toEqual([
			{ id: 'no-visible-task', dossierRef: 'T002-qwik-architecture D8' },
			{
				id: 'persistence-render-lowering',
				dossierRef: 'T002-qwik-architecture D8',
			},
		]);
		expect(
			QWIK_GATE_POLICIES.filter((policy) => policy.requiresArtifact).map(
				(policy) => policy.id,
			),
		).toEqual(['persistence-render-lowering']);
	});

	test('discovers and accepts the clean S1/S2/S3 emitted corpus', async () => {
		expect(await discoverGeneratedFiles()).toEqual([
			'generated/S1.jsx',
			'generated/S2.jsx',
			'generated/S3.jsx',
		]);
		const result = await checkGeneratedFiles();
		expect(result.violations, JSON.stringify(result.violations, null, 2)).toEqual([]);
		expect(result.unevaluated).toEqual([
			{ policy: 'persistence-render-lowering', reason: 'requires-artifact' },
		]);
		expect(Object.keys(result)).toEqual(['files', 'policies', 'violations']);
		for (const file of result.files)
			expect(await readFile(resolve(packageRoot, file), 'utf8')).toContain(
				'@generated by @frameless/qwik',
			);
	});

	test('MUTATION: rejects an injected useVisibleTask$ in emitted source', async () => {
		const source = await readFile(resolve(packageRoot, 'generated/S1.jsx'), 'utf8');
		const mutant = source
			.replace('useTask$ }', 'useTask$, useVisibleTask$ }')
			.replace(
				'export const RenderOnce',
				'useVisibleTask$(() => {});\n\nexport const RenderOnce',
			);
		const result = await checkSources([
			{ file: 'generated/VisibleTaskMutant.jsx', source: mutant },
		]);
		expect(result.violations.map((entry) => entry.policy)).toContain('no-visible-task');
		expect(
			result.violations.filter((entry) => entry.policy === 'no-visible-task'),
		).toEqual(
			expect.arrayContaining([
				expect.objectContaining({
					dossierRef: 'T002-qwik-architecture D8',
					line: 2,
				}),
			]),
		);
	});

	test('MUTATION: persistence-bearing IR fails closed in the gate and emitter', async () => {
		const artifact = structuredClone(await golden('s1-render-once.json')) as EnrichedIR;
		(artifact.records.persistence as unknown[]).push({ graphNodeId: 'state:count' });
		const source = await readFile(resolve(packageRoot, 'generated/S1.jsx'), 'utf8');
		const result = await checkSources([
			{ file: 'generated/PersistenceMutant.jsx', source, artifact },
		]);
		expect(result.unevaluated).toEqual([]);
		expect(result.violations).toEqual([
			expect.objectContaining({
				policy: 'persistence-render-lowering',
				dossierRef: 'T002-qwik-architecture D8',
			}),
		]);
		expect(() => emit(artifact)).toThrow('does not support persistence-bearing IR');
	});
});
