import { readFile } from 'node:fs/promises';
import type { EnrichedIR } from '@frameless/compiler';
import { resolve } from 'pathe';
import { beforeAll, describe, expect, test } from 'vitest';
import { emit } from '../src/emitter/index.ts';
import type { GatePolicy } from '../src/gate/index.ts';
import {
	checkGeneratedFiles,
	checkSources,
	discoverGeneratedFiles,
	SVELTE_GATE_POLICIES,
} from '../src/gate/index.ts';

const packageRoot = resolve(import.meta.dirname, '..');
const compilerGoldenRoot = resolve(packageRoot, '../../compiler/test/goldens');

async function golden(name: string): Promise<EnrichedIR> {
	return JSON.parse(await readFile(resolve(compilerGoldenRoot, name), 'utf8')) as EnrichedIR;
}

/**
 * MUTATION CONSTRUCTOR - every mutant in this file is built with this. Copied
 * verbatim in intent from `packages/frameworks/qwik/test/gate.test.ts`, whose own
 * doc comment instructs a new adapter to do exactly this and NOT to reach for a
 * bare `.replace()`.
 *
 * `String.prototype.replace` promises to return a string, NOT to have matched.
 * When the search misses it returns the input unchanged, with no error, and the
 * test then asserts a gate policy against source the gate has every right to
 * accept - green while measuring nothing. That is defect 3 cause B
 * (defects-and-targets T006/T007), where a CRLF checkout made one Solid search
 * literal unmatchable and the row had been asserting against a non-mutant for as
 * long as it had existed. This corpus is exposed the same way: its mutants are
 * built from emitted files read off disk, which the emitter is free to reshape.
 *
 * The assertion is on the OUTPUT, not on the search: a search that matched but
 * changed nothing yields a non-mutant just the same, and is rejected the same.
 */
function mutate(source: string, search: string | RegExp, replacement: string): string {
	const mutated = source.replace(search, replacement);
	if (mutated !== source) return mutated;
	throw new Error(
		`gate mutation did not change the source: ${String(search)} left it byte-identical, ` +
			'so this test would assert a policy against a non-mutant',
	);
}

/** `replaceAll` twin of `mutate`, with the same output-side precondition. */
function mutateAll(source: string, search: string | RegExp, replacement: string): string {
	const mutated = source.replaceAll(search, replacement);
	if (mutated !== source) return mutated;
	throw new Error(
		`gate mutation did not change the source: ${String(search)} left it byte-identical, ` +
			'so this test would assert a policy against a non-mutant',
	);
}

let s1 = '';
let s2 = '';
let s3 = '';
beforeAll(async () => {
	[s1, s2, s3] = await Promise.all(
		['S1', 'S2', 'S3'].map((name) =>
			readFile(resolve(packageRoot, `generated/${name}.svelte`), 'utf8'),
		),
	);
});

function policiesFor(file: string, source: string): string[] {
	return checkSources([{ file, source }]).violations.map((entry) => entry.policy);
}

describe('Svelte dossier gate', () => {
	test('publishes independent source and artifact-required policies', () => {
		expect(SVELTE_GATE_POLICIES.map((policy) => policy.id)).toEqual([
			'generated-header',
			'no-legacy-event-directive',
			'no-bindable',
			'no-stop-propagation',
			'derived-expression-purity',
			'sanctioned-svelte-ignore',
			'no-inter-sibling-whitespace',
			'persistence-render-lowering',
		]);
		expect(
			(SVELTE_GATE_POLICIES as readonly GatePolicy[])
				.filter((policy) => policy.requiresArtifact)
				.map((policy) => policy.id),
		).toEqual(['persistence-render-lowering']);
	});

	test('discovers and accepts the clean S1/S2/S3 emitted corpus', async () => {
		expect(await discoverGeneratedFiles()).toEqual([
			'generated/S1.svelte',
			'generated/S2.svelte',
			'generated/S3.svelte',
		]);
		const result = await checkGeneratedFiles();
		// [] IS NOT SELF-EVIDENT EVIDENCE - every policy below carries a mutation
		// row proving it can reject, and the two anti-vacuity rows prove the two
		// policies most at risk of degenerating into "reject everything" do not.
		expect(result.violations, JSON.stringify(result.violations, null, 2)).toEqual([]);
		expect(result.unevaluated).toEqual([
			{ policy: 'persistence-render-lowering', reason: 'requires-artifact' },
		]);
		expect(Object.keys(result)).toEqual(['files', 'policies', 'violations']);
		for (const file of result.files)
			expect(await readFile(resolve(packageRoot, file), 'utf8')).toContain(
				'@generated by @frameless/svelte',
			);
	});

	// CALIBRATION for the mutation constructor itself. A helper nobody has watched
	// fail is not evidence that it can fail, and the failure it guards against is
	// silent by construction.
	test('CALIBRATION: a mutation that leaves the source unchanged is loud', () => {
		expect(() => mutate(s1, 'text that is not in the emitted S1', 'x')).toThrow(
			/did not change the source/,
		);
		expect(s1).toContain('$state(');
		expect(() => mutate(s1, '$state(', '$state(')).toThrow(/did not change the source/);
		expect(() => mutateAll(s1, 'text that is not in the emitted S1', 'x')).toThrow(
			/did not change the source/,
		);
	});

	test('MUTATION: rejects emitted source without the generated header', () => {
		const mutant = mutate(s1, '<!-- @generated by @frameless/svelte', '<!-- hand written');
		expect(policiesFor('generated/HeaderMutant.svelte', mutant)).toContain(
			'generated-header',
		);
	});

	test('MUTATION: rejects the Svelte 4 on:click directive spelling', () => {
		// The same lexical substitution flips category across the major version -
		// the exact reason IR-4's version corollary is not amended. IR-4 is
		// DEFERRED, so only baseline-safe forms may be emitted.
		const mutant = mutate(s1, 'onclick={', 'on:click={');
		const policies = policiesFor('generated/LegacyMutant.svelte', mutant);
		expect(policies).toContain('no-legacy-event-directive');
	});

	test('MUTATION: rejects bind: and $bindable, whose failure mode is a dev-only warning', () => {
		const directive = mutate(s3, 'value={text}', 'bind:value={text}');
		expect(policiesFor('generated/BindMutant.svelte', directive)).toContain('no-bindable');
		const bindable = mutate(s3, 'let { initial,', 'let { initial = $bindable(),');
		expect(policiesFor('generated/BindableMutant.svelte', bindable)).toContain('no-bindable');
	});

	test('MUTATION: rejects stopPropagation, and the emitter refuses to produce it', async () => {
		const mutant = mutate(s3, 'event.preventDefault();', 'event.stopPropagation();');
		expect(policiesFor('generated/StopPropagationMutant.svelte', mutant)).toContain(
			'no-stop-propagation',
		);
		// The gate is the second line. The first is the emitter: a declared
		// stopPropagation throws rather than growing an on()-from-svelte/events
		// path that the corpus has no instance to test.
		const artifact = structuredClone(await golden('s3-event-form.json'));
		const event = artifact.records.events.find((entry) => entry.syncPolicy)!;
		(event as unknown as { syncPolicy: { actions: string[] } }).syncPolicy.actions.push(
			'stopPropagation',
		);
		expect(() => emit(artifact)).toThrow(/fails closed on a declared stopPropagation/);
	});

	test('MUTATION: rejects an unsanctioned svelte-ignore code', () => {
		const mutant = mutate(
			s3,
			'a11y_click_events_have_key_events',
			'state_unsafe_mutation',
		);
		const violations = checkSources([
			{ file: 'generated/IgnoreMutant.svelte', source: mutant },
		]).violations;
		expect(violations.map((entry) => entry.policy)).toContain('sanctioned-svelte-ignore');
		expect(violations.find((entry) => entry.policy === 'sanctioned-svelte-ignore')?.message)
			.toContain('state_unsafe_mutation');
	});

	test('MUTATION: rejects whitespace between two siblings', () => {
		// MEASURED at 5.56.8: Svelte keeps this as a single space text node while
		// JSX drops the whole whitespace-only line, so the emitted text content
		// would diverge from React's and Solid's.
		const mutant = mutate(s1, /<\/output\n(\t*)>/, '</output>\n$1');
		expect(policiesFor('generated/WhitespaceMutant.svelte', mutant)).toContain(
			'no-inter-sibling-whitespace',
		);
	});

	test('MUTATION: persistence-bearing IR fails closed in the gate and the emitter', async () => {
		const artifact = structuredClone(await golden('s1-render-once.json'));
		(artifact.records.persistence as unknown[]).push({ graphNodeId: 'state:count' });
		const result = checkSources([
			{ file: 'generated/PersistenceMutant.svelte', source: s1, artifact },
		]);
		expect(result.unevaluated).toEqual([]);
		expect(result.violations).toEqual([
			expect.objectContaining({ policy: 'persistence-render-lowering' }),
		]);
		expect(() => emit(artifact)).toThrow(/does not support persistence-bearing IR/);
	});
});

/**
 * IR-7 - the sleeper. S1's `$derived` is trivial and will always pass, which is
 * the definition of a green vacuum, so the policy is calibrated against planted
 * members of the set it claims to catch (instrument rule 4) and against two
 * shapes it must NOT catch.
 */
describe('MUTATION: derived-expression-purity (IR-7)', () => {
	test('rejects an update expression inside $derived', () => {
		const mutant = mutate(s1, 'count * multiplier', 'count++ * multiplier');
		const violations = checkSources([
			{ file: 'generated/DerivedUpdateMutant.svelte', source: mutant },
		]).violations;
		expect(violations.map((entry) => entry.policy)).toContain('derived-expression-purity');
		expect(
			violations.find((entry) => entry.policy === 'derived-expression-purity')?.message,
		).toContain('update expression');
	});

	test('rejects an assignment inside $derived', () => {
		const mutant = mutate(s1, 'count * multiplier', '(count = 2) * multiplier');
		const violations = checkSources([
			{ file: 'generated/DerivedAssignMutant.svelte', source: mutant },
		]).violations;
		expect(violations.map((entry) => entry.policy)).toContain('derived-expression-purity');
		expect(
			violations.find((entry) => entry.policy === 'derived-expression-purity')?.message,
		).toContain('assignment');
	});

	test('rejects a known-mutating method call inside $derived', () => {
		const mutant = mutate(s2, 'todos.filter((todo) => todo.done)', 'todos.sort()');
		const violations = checkSources([
			{ file: 'generated/DerivedSortMutant.svelte', source: mutant },
		]).violations;
		expect(violations.map((entry) => entry.policy)).toContain('derived-expression-purity');
		expect(
			violations.find((entry) => entry.policy === 'derived-expression-purity')?.message,
		).toContain('.sort()');
	});

	test('rejects a delete expression inside $derived', () => {
		const mutant = mutate(s1, '${prefix}${count', '${delete globalThis.x}${count');
		expect(policiesFor('generated/DerivedDeleteMutant.svelte', mutant)).toContain(
			'derived-expression-purity',
		);
	});

	test('ANTI-VACUITY: a non-mutating call and a mutation OUTSIDE $derived are accepted', () => {
		// S2's own derived is `todos.filter(...).length`. If this policy were
		// "reject any call" the clean corpus would already be red, and every row
		// above would be measuring nothing.
		expect(s2).toContain('$derived(todos.filter((todo) => todo.done).length)');
		expect(policiesFor('generated/S2.svelte', s2)).not.toContain(
			'derived-expression-purity',
		);
		// S2's handlers assign to `todos` and call `.slice()`/`.concat()` all over.
		// The policy reads $derived ancestry, not text.
		expect(s2).toContain('todos = todos.concat(item);');
		// And a planted assignment in a handler stays accepted - proving the walk
		// really is scoped to $derived arguments rather than to the whole script.
		const handlerMutant = mutateAll(s2, "draft = '';", "draft = ''; next = next + 1;");
		expect(policiesFor('generated/HandlerMutant.svelte', handlerMutant)).not.toContain(
			'derived-expression-purity',
		);
	});

	test('states what it cannot see, so a pass is never read as a purity proof', () => {
		// NOT a policy failure - a DOCUMENTED blind spot, pinned so that closing it
		// later is a deliberate change rather than an accident. `$derived(f())` is
		// accepted no matter what `f` does, because the walk never leaves the
		// expression.
		const source = [
			'<!-- @generated by @frameless/svelte from Blind; do not edit. -->',
			'<script>',
			'\tlet count = $state(1);',
			'\tfunction impure() {',
			'\t\tcount += 1;',
			'\t\treturn count;',
			'\t}',
			'\tconst derived = $derived(impure());',
			'</script>',
			'',
			'<p>{derived}</p>',
		].join('\n');
		expect(policiesFor('generated/Blind.svelte', source)).not.toContain(
			'derived-expression-purity',
		);
	});
});
