<!-- @generated by @frameless/vue from AsyncBoard; do not edit. -->
<script setup lang="ts">
	import { ref } from 'vue';
	const props = defineProps({ ready: { type: null, required: true }, onTrace: { type: Function, required: true } });
	const ticks = ref(0);
	const phase = ref('idle');
	const cancels = ref(0);
</script>

<template>
	<form data-scenario="s8">
		<p data-async="ticks">{{ ticks }}</p>
		<p data-async="phase">{{ phase }}</p>
		<p data-async="cancels">{{ cancels }}</p>
		<button
			type="button"
			data-action="run"
			@click="async (event) => {
				phase = 'pending';
				await ready;
				ticks = ticks + 1;
				phase = 'done';
				onTrace('run', { phase: 'done' }, event);
			}"
		>run</button>
		<button
			type="submit"
			data-action="cancel-run"
			@click="async (event) => {
				event.preventDefault();
				await ready;
				cancels = cancels + 1;
				onTrace('cancel', { cancels: 1 }, event);
			}"
		>cancel</button>
	</form>
</template>
