<!-- @generated by @frameless/vue from EventForm; do not edit. -->
<script setup>
	import { ref } from 'vue';
	const props = defineProps(['initial', 'onTrace']);
	const text = ref(props.initial);
	const checked = ref(false);
	const writes = ref(0);
</script>

<template>
	<form
		data-scenario="s3"
		v-on:click="(event) => {
			if (event.target.dataset.action === 'submit') {
				onTrace('bubble', { source: 'form' }, event);
			}
		}"
	>
		<input
			data-action="text"
			v-bind:value="text"
			v-on:input="(event) => {
				text = event.currentTarget.value;
				onTrace('text', { value: event.currentTarget.value }, event);
			}"
		>
		<input
			type="checkbox"
			data-action="checked"
			v-bind:checked="checked"
			v-on:change="(event) => {
				checked = event.currentTarget.checked;
				onTrace('checked', { checked: event.currentTarget.checked }, event);
			}"
		>
		<button
			type="button"
			data-action="submit"
			v-on:click="(event) => {
				event.preventDefault();
				writes = 1;
				writes = 2;
				onTrace('submit', { text, checked, writes: 2 }, event);
			}"
		>submit</button>
		<button
			type="submit"
			data-action="cancel-submit"
			v-on:click="(event) => {
				event.preventDefault();
			}"
		>cancel-submit</button>
		<output data-writes="true">{{ writes }}</output>
		<span data-callback-marker="present"></span>
		<details data-cancel="guarded">
			<summary
				data-action="cancel-open"
				v-on:click="(event) => {
					if (event.detail === 1) {
						event.preventDefault();
					}
				}"
			>cancel-open</summary>
		</details>
		<details data-cancel="unguarded">
			<summary
				data-action="allow-open"
				v-on:click="(event) => {
					if (event.detail === 2) {
						event.preventDefault();
					}
				}"
			>allow-open</summary>
		</details>
	</form>
</template>
