<!-- @generated by @frameless/vue from FormBoard; do not edit. -->
<script setup>
	import { computed, ref } from 'vue';
	const props = defineProps(['seed', 'onTrace']);
	const size = ref('s');
	const notes = ref('draft');
	const pick = ref('r1');
	const lock = ref(null);
	const rows = ref(props.seed.map((row) => ({ ...row })));
	const chosen = computed(() => rows.value.filter((row) => row.on).map((row) => row.id).join('+') || 'none');
	const onFirst = computed(() => pick.value === 'r1');
	const onSecond = computed(() => pick.value === 'r2');
	const locked = computed(() => lock.value !== null);
	const guard = computed(() => lock.value === null ? null : 'held');
</script>

<template>
	<form data-scenario="s7">
		<select
			data-control="size"
			:data-size="size"
			@input="(event) => {
				const next = event.currentTarget.value;
				size = next;
				onTrace('size', { size: next }, event);
			}"
		>
			<option value="s">small</option>
			<option value="m">medium</option>
			<option value="l">large</option>
		</select>
		<textarea
			data-control="notes"
			:data-notes="notes"
			@input="(event) => {
				const next = event.currentTarget.value;
				notes = next;
				onTrace('notes', { notes: next }, event);
			}"
		></textarea>
		<input
			type="radio"
			name="s7pick"
			data-pick="r1"
			:checked="onFirst"
			@change="(event) => {
				pick = 'r1';
				onTrace('pick', { pick: 'r1' }, event);
			}"
		>
		<input
			type="radio"
			name="s7pick"
			data-pick="r2"
			:checked="onSecond"
			@change="(event) => {
				pick = 'r2';
				onTrace('pick', { pick: 'r2' }, event);
			}"
		>
		<p data-picked="true">{{ pick }}</p>
		<p data-chosen="true">{{ chosen }}</p>
		<ul data-tags="true">
			<li v-for="row in rows" :key="row.id" :data-oracle-form-key="row.id">
				<input
					type="checkbox"
					:data-tag="row.id"
					:checked="row.on"
					@change="(event) => {
						const next = rows.map((entry) => entry.id === row.id ? { id: entry.id, on: !entry.on } : entry);
						rows = next;
						onTrace('tag', { id: row.id }, event);
					}"
				>
			</li>
		</ul>
		<button
			type="button"
			data-action="resize"
			@click="(event) => {
				size = 'l';
				notes = 'final';
				onTrace('resize', { size: 'l', notes: 'final' }, event);
			}"
		>resize</button>
		<button
			type="button"
			data-action="lock"
			:data-lock="lock"
			@click="(event) => {
				const next = lock === null ? 'on' : null;
				lock = next;
				onTrace('lock', { lock: next }, event);
			}"
		>lock</button>
		<button type="button" data-guard="true" :aria-disabled="locked" :data-held="guard">guard</button>
	</form>
</template>
