<!-- @generated by @frameless/vue from NestedBoard; do not edit. -->
<script setup lang="ts">
	import { computed, ref } from 'vue';
	const props = defineProps(['seed', 'onTrace']);
	const groups = ref(props.seed.map((group) => ({ ...group, rows: group.rows.slice() })));
	const selection = ref('none');
	const marked = ref('none');
	const cells = computed(() => groups.value.flatMap((group) => group.rows).length);
</script>

<template>
	<section data-scenario="s4">
		<output data-selection="true">{{ selection }}</output>
		<p data-count="cells">{{ cells }}/{{ groups.length }}</p>
		<button
			data-action="flip"
			@click="(event) => {
				const flipped = groups.map((group) => ({ ...group, rows: group.rows.slice().reverse() }));
				groups = flipped;
				onTrace('flip', { order: flipped.map((group) => group.id) }, event);
			}"
		>flip</button>
		<button
			data-action="reorder"
			@click="(event) => {
				const order = groups.slice().reverse();
				groups = order;
				onTrace('reorder', { order: order.map((group) => group.id) }, event);
			}"
		>reorder</button>
		<ul data-groups="true">
			<li v-for="group in groups" :key="group.id" :data-oracle-group-key="group.id">
				<ul :data-rows="group.id">
					<li v-for="row in group.rows" :key="row.id" :data-oracle-cell-key="row.id">
						<button
							:data-select="row.id"
							@click="(event) => {
								selection = `${group.id}>${row.id}`;
								marked = row.id;
								onTrace('select', { group: group.id, row: row.id }, event);
							}"
						>select</button>
						<span v-if="marked === row.id" :data-cell-on="row.id">on</span>
						<span v-else :data-cell-off="row.id">off</span>
						<details :data-cell-open="row.id">
							<summary :data-open-cell="row.id">open</summary>
						</details>
					</li>
				</ul>
			</li>
		</ul>
	</section>
</template>
