<!-- @generated by @frameless/vue from RenderOnce; do not edit. -->
<script setup lang="ts">
	import { computed, ref } from 'vue';
	const props = defineProps(['label', 'multiplier', 'visible', 'onTrace']);
	props.onTrace('setup', { runs: 1 });
	const count = ref(1);
	const prefix = `${props.label}:`;
	const derived = computed(() => `${prefix}${count.value * props.multiplier}`);
</script>

<template>
	<div data-s1-root="">
		<p v-if="!visible" data-branch="hidden">hidden</p>
		<section v-else data-scenario="s1">
			<output data-value="derived">{{ derived }}</output>
			<button
				data-action="increment"
				@click="() => {
					count++;
					onTrace('change', { count });
				}"
			>increment</button>
		</section>
	</div>
</template>
