<!-- @generated by @frameless/vue from TodoMvc; do not edit. -->
<script setup lang="ts">
	import { computed, ref } from 'vue';
	const props = defineProps({ onTrace: { type: Function, required: true } });
	const todos = ref([{ id: 't1', title: 'Taste JavaScript', done: true }, { id: 't2', title: 'Buy a unicorn', done: false }]);
	const draft = ref('');
	const next = ref(3);
	const filter = ref('all');
	const editing = ref('');
	const editDraft = ref('');
	const active = computed(() => todos.value.filter((todo) => !todo.done).length);
	const completed = computed(() => todos.value.filter((todo) => todo.done).length);
	const allDone = computed(() => todos.value.length > 0 && todos.value.filter((todo) => !todo.done).length === 0);
	const remainingLabel = computed(() => todos.value.filter((todo) => !todo.done).length === 1 ? ' item left' : ' items left');
</script>

<template>
	<section class="todoapp" data-app="todomvc">
		<header class="header">
			<h1>todos</h1>
			<form
				class="new-todo-form"
				data-action="add"
				@click="(event) => onTrace('press', { area: 'new-todo' }, event)"
				@submit="(event) => {
					event.preventDefault();
					const title = draft.trim();
					const item = { id: `t${next}`, title, done: false };
					todos = title === '' ? todos : todos.concat(item);
					next = title === '' ? next : next + 1;
					draft = '';
					onTrace('add', { id: item.id, title }, event);
				}"
			>
				<input
					class="new-todo"
					placeholder="What needs to be done?"
					data-action="new"
					:value="draft"
					@input="(event) => draft = event.currentTarget.value"
				>
			</form>
		</header>
		<main v-if="todos.length > 0" class="main">
			<input
				id="toggle-all"
				class="toggle-all"
				type="checkbox"
				data-action="toggle-all"
				:checked="allDone"
				@change="(event) => {
					const done = event.currentTarget.checked;
					todos = todos.map((todo) => ({ id: todo.id, title: todo.title, done }));
					onTrace('toggle-all', { done }, event);
				}"
			>
			<label for="toggle-all">Mark all as complete</label>
			<ul class="todo-list">
				<li
					v-for="todo in todos"
					:key="todo.id"
					:class="editing === todo.id ? 'editing' : todo.done ? 'completed' : ''"
					:data-oracle-todo-key="todo.id"
					:hidden="filter === 'active' ? todo.done : filter === 'completed' ? !todo.done : false"
				>
					<form
						v-if="editing === todo.id"
						class="edit-form"
						:data-commit="todo.id"
						@click="(event) => onTrace('press', { area: 'edit' }, event)"
						@submit="(event) => {
							event.preventDefault();
							const title = editDraft.trim();
							todos = title === '' ? todos : todos.map((entry) => entry.id === todo.id ? { id: entry.id, title, done: entry.done } : entry);
							editing = '';
							editDraft = '';
							onTrace('commit', { id: todo.id, title }, event);
						}"
					>
						<input
							class="edit"
							:data-edit="todo.id"
							:value="editDraft"
							@input="(event) => editDraft = event.currentTarget.value"
						>
						<button
							type="button"
							class="cancel-edit"
							:data-revert="todo.id"
							@click="(event) => {
								editing = '';
								editDraft = '';
								onTrace('revert', { id: todo.id }, event);
							}"
						>cancel</button>
					</form>
					<div v-else class="view">
						<input
							class="toggle"
							type="checkbox"
							:data-toggle="todo.id"
							:checked="todo.done"
							@change="(event) => {
								const done = event.currentTarget.checked;
								todos = todos.map((entry) => entry.id === todo.id ? { id: entry.id, title: entry.title, done } : entry);
								onTrace('toggle', { id: todo.id, done }, event);
							}"
						>
						<button
							type="button"
							class="todo-title"
							:data-title="todo.id"
							@click="(event) => {
								const opened = event.detail === 2;
								editing = opened ? todo.id : editing;
								editDraft = opened ? todo.title : editDraft;
								onTrace('edit', { id: todo.id, opened }, event);
							}"
						>{{ todo.title }}</button>
						<button
							type="button"
							class="destroy"
							:data-destroy="todo.id"
							@click="(event) => {
								todos = todos.filter((entry) => entry.id !== todo.id);
								onTrace('destroy', { id: todo.id }, event);
							}"
						>x</button>
					</div>
				</li>
			</ul>
		</main>
		<footer v-if="todos.length > 0" class="footer">
			<span class="todo-count"><strong>{{ active }}</strong>{{ remainingLabel }}</span>
			<ul class="filters">
				<li>
					<a
						href="#/"
						data-filter="all"
						:class="filter === 'all' ? 'selected' : ''"
						@click="(event) => {
							event.preventDefault();
							filter = 'all';
							onTrace('filter', { filter: 'all' }, event);
						}"
					>All</a>
				</li>
				<li>
					<a
						href="#/active"
						data-filter="active"
						:class="filter === 'active' ? 'selected' : ''"
						@click="(event) => {
							event.preventDefault();
							filter = 'active';
							onTrace('filter', { filter: 'active' }, event);
						}"
					>Active</a>
				</li>
				<li>
					<a
						href="#/completed"
						data-filter="completed"
						:class="filter === 'completed' ? 'selected' : ''"
						@click="(event) => {
							event.preventDefault();
							filter = 'completed';
							onTrace('filter', { filter: 'completed' }, event);
						}"
					>Completed</a>
				</li>
			</ul>
			<button
				v-if="completed > 0"
				type="button"
				class="clear-completed"
				data-action="clear-completed"
				@click="(event) => {
					const cleared = todos.filter((todo) => todo.done).length;
					todos = todos.filter((todo) => !todo.done);
					onTrace('clear-completed', { cleared }, event);
				}"
			>Clear completed</button>
		</footer>
	</section>
</template>
