// @generated by @frameless/solid; do not edit.
import { createSignal, untrack, For, Show } from 'solid-js';
import { createStore, produce, reconcile } from 'solid-js/store';

function __framelessWrite(key, attr, value) {
	try {
		localStorage.setItem(key, value);
	} catch {
		void 0;
	}
	document.documentElement.setAttribute(attr, value);
}

export function KeyedTodo(props) {
	const [todos, setTodos] = createStore(untrack(() => props.seed.map((todo) => ({ ...todo }))));
	const [draft, setDraft] = createSignal(
		globalThis.__FRAMELESS_STATE__?.['markless:draft'] ?? 'light',
	);
	let next = 3;
	const complete = () => todos.filter((todo) => todo.done).length;
	return (
		<section data-scenario="s2">
			<p data-count="complete">
				{complete()}/{todos.length}
			</p>
			<input
				data-action="new"
				value={draft()}
				attr:value={draft()}
				onInput={(event) => {
					setDraft(event.currentTarget.value);
					__framelessWrite(
						'markless:draft',
						'data-markless-draft',
						event.currentTarget.value,
					);
				}}
			/>
			<button
				data-action="add"
				onClick={(event) => {
					const item = { id: `c${next}`, title: draft(), done: false };
					next++;
					setTodos(reconcile(todos.concat(item), { key: 'id' }));
					setDraft('');
					__framelessWrite('markless:draft', 'data-markless-draft', '');
					props.onTrace('add', { id: item.id, title: item.title }, event);
				}}
			>
				add
			</button>
			<Show when={todos.length === 0}>
				<p data-empty="true">empty</p>
			</Show>
			<ul>
				<For each={todos}>
					{(todo) => (
						<li data-oracle-row-key={todo.id}>
							<input
								data-edit={todo.id}
								value={todo.title}
								attr:value={todo.title}
								onInput={(event) => {
									const title = event.currentTarget.value;
									setTodos(
										produce((storeDraft) => {
											const alias = storeDraft.find(
												(item) => item.id === todo.id,
											);
											alias.title = title;
										}),
									);
									props.onTrace('edit', { id: todo.id, title }, event);
								}}
							/>
							<input
								type="checkbox"
								data-toggle={todo.id}
								checked={todo.done}
								onChange={(event) => {
									const checked = event.currentTarget.checked;
									setTodos(
										produce((storeDraft2) => {
											const alias = storeDraft2.find(
												(item) => item.id === todo.id,
											);
											alias.done = checked;
										}),
									);
									props.onTrace('toggle', { id: todo.id, checked }, event);
								}}
							/>
							<button
								data-remove={todo.id}
								onClick={(event) => {
									setTodos(
										reconcile(
											todos.filter((item) => item.id !== todo.id),
											{ key: 'id' },
										),
									);
									props.onTrace('remove', { id: todo.id }, event);
								}}
							>
								remove
							</button>
						</li>
					)}
				</For>
			</ul>
			<button
				data-action="reorder"
				onClick={(event) => {
					const order = todos.slice().reverse();
					setTodos(reconcile(order, { key: 'id' }));
					props.onTrace('reorder', { order: order.map((todo) => todo.id) }, event);
				}}
			>
				reorder
			</button>
			<button
				data-action="clear"
				onClick={(event) => {
					const count = todos.length;
					setTodos(reconcile([], { key: 'id' }));
					props.onTrace('clear', { count }, event);
				}}
			>
				clear
			</button>
		</section>
	);
}
