// @generated by @frameless/solid; do not edit.
import { createSignal } from 'solid-js';

function __framelessWrite(key, attr, value) {
	try {
		localStorage.setItem(key, value);
	} catch {
		void 0;
	}
	document.documentElement.setAttribute(attr, value);
}

export function PersistedFilter(props) {
	const [filter, setFilter] = createSignal(
		globalThis.__FRAMELESS_STATE__?.['markless:filter'] ?? 'all',
	);
	const [draft, setDraft] = createSignal(
		globalThis.__FRAMELESS_STATE__?.['markless:draft'] ?? '',
	);
	let touches = '0';
	const label = () => `${filter()}:${draft()}`;
	return (
		<section data-scenario="p1">
			<p data-filter="value">{filter()}</p>
			<p data-label="value">{label()}</p>
			<input
				data-action="draft"
				value={draft()}
				attr:value={draft()}
				onInput={(event) => {
					setDraft(event.currentTarget.value);
					__framelessWrite('markless:draft', 'data-markless-draft', draft());
				}}
			/>
			<button
				data-action="cycle"
				onClick={(event) => {
					setFilter(filter() === 'all' ? 'done' : 'all');
					__framelessWrite('markless:filter', 'data-markless-filter', filter());
					touches = `${Number(touches) + 1}`;
					__framelessWrite('markless:touches', 'data-markless-touches', touches);
					props.onTrace('cycle', { filter: filter() }, event);
				}}
			>
				cycle
			</button>
		</section>
	);
}
