// @generated by @frameless/react; do not edit.
import { useRef, useState } from 'react';

function __framelessWrite(key, attr, value) {
	try {
		localStorage.setItem(key, value);
	} catch {
		void 0;
	}
	document.documentElement.setAttribute(attr, value);
}

export function PersistedFilter({ onTrace }) {
	const [filter, setFilter] = useState(
		() => globalThis.__FRAMELESS_STATE__?.['markless:filter'] ?? 'all',
	);
	const [draft, setDraft] = useState(
		() => globalThis.__FRAMELESS_STATE__?.['markless:draft'] ?? '',
	);
	const touches = useRef('0');
	const label = `${filter}:${draft}`;
	return (
		<section data-scenario="p1">
			<p data-filter="value">{filter}</p>
			<p data-label="value">{label}</p>
			<input
				data-action="draft"
				value={draft}
				onChange={(event) => {
					const nextDraft = event.target.value;
					setDraft(nextDraft);
					__framelessWrite('markless:draft', 'data-markless-draft', nextDraft);
				}}
			/>
			<button
				data-action="cycle"
				onClick={(event) => {
					const currentState3 = touches.current;
					const nextFilter = filter === 'all' ? 'done' : 'all';
					setFilter(nextFilter);
					__framelessWrite('markless:filter', 'data-markless-filter', nextFilter);
					touches.current = `${Number(currentState3) + 1}`;
					__framelessWrite(
						'markless:touches',
						'data-markless-touches',
						`${Number(currentState3) + 1}`,
					);
					onTrace('cycle', { filter: nextFilter }, event);
				}}
			>
				cycle
			</button>
		</section>
	);
}
