import { readdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import ngPlugin from '@angular-eslint/eslint-plugin';
import tplPlugin from '@angular-eslint/eslint-plugin-template';
import * as templateParser from '@angular-eslint/template-parser';
import { BindingType, parseTemplate } from '@angular/compiler';
import * as tsParser from '@typescript-eslint/parser';
import { ESLint } from 'eslint';
import type { EnrichedIR } from '@frameless/compiler';
import { dirname, normalize, relative, resolve } from 'pathe';

export type DossierRef =
	// Standalone single-file component, class named from the IR's exportedName,
	// and BOTH arbiters - @angular/compiler parseTemplate and @angular-eslint.
	| 'frameless-angular-v1 T002 ruling 4 (both arbiters, compiler first)'
	// onTrace is an @Input, never an @Output/EventEmitter: emit() takes ONE value
	// and the corpus calls onTrace with two AND three positional arguments.
	| 'frameless-angular-v1 T002 ruling 2 (onTrace is an @Input)'
	// IR-1/IR-2: no bindable prop kind and no emit concept. Two-way binding is out
	// of scope on two independent axes.
	| 'frameless-angular-v1 T002 also ruled (IR-1/IR-2)'
	// IR-5: two declared actions, emitted as ordinary in-body statements.
	// stopPropagation fails closed rather than growing an untested path.
	| 'frameless-angular-v1 T002 also ruled (IR-5)'
	// IR-7: purity is never asserted while an Angular getter is re-evaluated on
	// every change-detection pass. Conservative syntactic guard, not a proof.
	| 'frameless-angular-v1 T002 also ruled (IR-7)'
	// IR-4 deferred, version corollary NOT amended: the emitted form set is an
	// explicit allowlist and the lane's version floor is the max over it.
	| 'frameless-angular-v1 T002 also ruled (IR-4 baseline form inventory)'
	// SETTLED, no longer held out. T005 re-ran all six gates against this landed
	// lane: decorator-vs-signal is DENIED at G5, and G6 FAILs, so nothing but this
	// policy pins the form. Worked example 11 in docs/emitter-idiom-policy.md.
	| 'frameless-angular-v1 T005 (decorator-vs-signal, DENIED at G5 and G6)'
	// OnPush is the Angular 22 DEFAULT, so emitting changeDetection at all is an
	// explicit opt-out the applied arbiter reports.
	| 'frameless-angular-v1 T003a ruling 2 (OnPush is the Angular 22 default)'
	// The whitespace layout the template printer depends on, MEASURED at 22.0.8.
	| 'frameless-angular-v1 T003 measurement M1'
	// Qwik's artifact-required policy, transposed: fail closed on persistence.
	| 'T002-qwik-architecture D8'
	// The THIRD-PARTY arbiter. Every policy above encodes what WE decided; these
	// encode what the Angular team decided.
	| 'frameless-angular-v1 T003 lint arbiter';

export type GatePolicy = {
	readonly id: string;
	readonly dossierRef: DossierRef;
	readonly requiresArtifact?: true;
};
export type GateViolation = {
	readonly file: string;
	readonly policy: string;
	readonly dossierRef: DossierRef;
	readonly message: string;
	readonly line: number | null;
};
export type GateResult = {
	readonly files: readonly string[];
	readonly policies: readonly GatePolicy[];
	readonly violations: readonly GateViolation[];
	readonly unevaluated: ReadonlyArray<{
		readonly policy: string;
		readonly reason: 'requires-artifact';
	}>;
};

type Node = Record<string, any>;

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const GENERATED_HEADER = '// @generated by @frameless/angular';

function persistenceArtifactPolicy() {
	const policy = {
		id: 'persistence-render-lowering',
		dossierRef: 'T002-qwik-architecture D8',
	} as const;
	Object.defineProperty(policy, 'requiresArtifact', { enumerable: false, value: true });
	return policy as typeof policy & { readonly requiresArtifact: true };
}

// ---------------------------------------------------------------------------
// the third-party arbiter
// ---------------------------------------------------------------------------

/**
 * THE APPLIED SET IS DERIVED, NOT HAND-PICKED, AND THAT IS THE WHOLE POINT.
 *
 * `frameless-angular-v1` T002 ruling 4 modelled this gate on the Svelte one,
 * which consumes `eslint-plugin-svelte`'s `configs.recommended` - a
 * THIRD-PARTY-AUTHORED applied set, which is what makes an arbiter genuinely
 * independent: WE did not choose which rules judge us. T003 then REFUTED THAT
 * RULING'S PREMISE by measurement: `@angular-eslint/eslint-plugin` exports only
 * `rules` (50) and `@angular-eslint/eslint-plugin-template` only `processors` and
 * `rules` (41). NEITHER PUBLISHES A CONFIG. The presets live solely in the
 * `angular-eslint` META package, which T002's own stop_if forbids for a
 * measured reason - see `WHY_THE_META_PACKAGE_IS_NOT_USED`.
 *
 * T003a's answer, and the reason the conclusion survives STRONGER than the
 * premise: every `@angular-eslint` rule carries its OWN membership flag,
 * `meta.docs.recommended === 'recommended'`, and the meta package's published
 * preset is GENERATED FROM THAT SAME METADATA - its header reads, verbatim,
 * "DO NOT EDIT THIS FILE / In order to update this config, please run
 * `pnpm update-rule-configs`". So deriving here is not transcription and not
 * reconstruction: it is running UPSTREAM'S OWN GENERATOR against UPSTREAM'S OWN
 * SOURCE OF TRUTH, already sitting inside the two permitted leaf packages. A rule
 * upstream adds to `recommended` arrives here automatically, which is exactly the
 * property a transcribed set would fake.
 */
function recommendedRules(prefix: string, rules: Readonly<Record<string, unknown>>): string[] {
	return Object.entries(rules)
		.filter(
			([, rule]) =>
				(rule as { meta?: { docs?: { recommended?: unknown } } }).meta?.docs?.recommended ===
				'recommended',
		)
		.map(([name]) => `${prefix}${name}`)
		.sort();
}

/** The 12 of 50 TypeScript rules upstream's own metadata marks `recommended`. */
export const ANGULAR_ESLINT_TS_RULES_DERIVED: readonly string[] = recommendedRules(
	'@angular-eslint/',
	ngPlugin.rules as unknown as Record<string, unknown>,
);

/** The 4 of 41 template rules upstream's own metadata marks `recommended`. */
export const ANGULAR_ESLINT_TEMPLATE_RULES_DERIVED: readonly string[] = recommendedRules(
	'@angular-eslint/template/',
	tplPlugin.rules as unknown as Record<string, unknown>,
);

export type AddedEslintRule = {
	readonly rule: string;
	readonly severity: 'error' | 'warn';
	readonly reason: string;
};

/**
 * THE ONE MEASURED GAP BETWEEN THE DERIVATION AND UPSTREAM'S PUBLISHED PRESET,
 * AND ITS DIRECTION IS WHAT MAKES IT SAFE.
 *
 * `use-lifecycle-interface` IS in upstream's published `ts-recommended` at
 * severity `warn`, and its own `meta.docs.recommended` is `undefined`. The
 * derivation therefore yields 12 where upstream publishes 13, so the applied set
 * is DERIVED UNION ONE RECORDED ADDITION.
 *
 * NOTE THE DIRECTION: the only frameless-authored delta ADDS a rule, and there
 * are ZERO omissions. AN ADDITIONS-ONLY DELTA CANNOT BE USED TO MAKE A CORPUS
 * GREEN, which is precisely what keeps the independence property intact. The
 * `frameless-angular-v1` T003a dissent records the residual risk honestly: if
 * upstream adds a SECOND warn-tier rule the derivation misses it silently, and
 * the miss direction is "fewer rules judge us" - which can under-cover a defect
 * but cannot hide one.
 *
 * It is also load-bearing here rather than decorative. This emitter initialises
 * every component local in `ngOnInit` (a field initialiser runs before Angular
 * has written a single `@Input`), so every emitted class declares a lifecycle
 * method, and this rule is what forces the matching `implements OnInit`.
 */
export const ANGULAR_ESLINT_RULES_ADDED: readonly AddedEslintRule[] = [
	{
		rule: '@angular-eslint/use-lifecycle-interface',
		severity: 'error',
		reason:
			"MEASURED: upstream's published ts-recommended carries this rule at severity 'warn' while its own meta.docs.recommended is undefined, so a pure derivation from the metadata misses it. Added with its provenance rather than left out, and applied at 'error' because this gate reports every message identically - a warn-tier arbiter verdict that did not fail the gate would be an arbiter nobody has to answer to. It is not decorative here: every emitted class declares ngOnInit, and this rule is what requires the matching `implements OnInit`.",
	},
];

/**
 * ZERO OMISSIONS, asserted as a constant so the absence is a decision rather than
 * an oversight. The qwik gate USED TO drop two rules from `configs.recommended`
 * with no recorded reason - the silent-drop this discipline exists to prevent, and
 * the defect T003a routed upward against shipped code. It no longer does: see
 * `QWIK_ESLINT_RULES_REQUIRING_TYPES` in `packages/frameworks/qwik/src/gate/index.ts`,
 * which now names every unapplied rule with the reason it cannot run, and
 * `QWIK_ESLINT_RECOMMENDED_RULES`, which asserts totality in both directions.
 * Nothing is dropped here either.
 */
export const ANGULAR_ESLINT_RULES_OMITTED: readonly { rule: string; reason: string }[] = [];

/** Every rule this gate actually runs, sorted. Derived union the one addition. */
export const ANGULAR_ESLINT_RULES_APPLIED: readonly string[] = [
	...ANGULAR_ESLINT_TS_RULES_DERIVED,
	...ANGULAR_ESLINT_TEMPLATE_RULES_DERIVED,
	...ANGULAR_ESLINT_RULES_ADDED.map((entry) => entry.rule),
].sort();

/**
 * WHY THE `angular-eslint` META PACKAGE STAYS FORBIDDEN, measured rather than
 * assumed.
 *
 * Its `ts-base.js` and `template-base.js` carry ONLY `parser` and `plugins` - no
 * rules, no `files` globs, no processor. That is the OPPOSITE of Svelte, whose
 * base entry carried the parser instance, the globs and the processor, which is
 * the stated reason the Svelte gate consumed the config whole. Angular's parser
 * and processor are already DIRECT dependencies of this package. So the meta
 * package buys nothing derivable and costs `@angular-devkit/core`,
 * `@angular-devkit/schematics`, `@angular-eslint/builder`,
 * `@angular-eslint/schematics` and an `@angular/cli >=22 <23` peer - which drags
 * the vendored vite 7.3.6 into a workspace pinned to vite 8. T002's stop_if was
 * not reflexive.
 */
export const WHY_THE_META_PACKAGE_IS_NOT_USED =
	'ts-base.js and template-base.js carry only parser and plugins - no rules, no files globs, no processor - while the parser and processor are already direct dependencies here. The package would add @angular/cli >=22 <23 and the devkit, which drag the vendored vite 7.3.6 into a workspace pinned to vite 8.';

/**
 * AN ASSERTED TOOLCHAIN FACT, in the sense `frameless-angular-v1` T002 ruling 1
 * invented for the vendored-vite divergence and T003a required a second time.
 *
 * MEASURED: `tsc -p packages/frameworks/angular` runs the CATALOG TypeScript,
 * while `@typescript-eslint/parser` - the parser under this arbiter - resolves a
 * DIFFERENT TypeScript. In effect that is benign and slightly BETTER than the
 * alternative: this gate lints EMITTED output, which is deliberately outside every
 * tsconfig here and is typechecked at T004 by `ng build` at TypeScript ~6, so
 * parsing at 6.x is CLOSER to the truth than parsing at the catalog's 5.x.
 *
 * BUT THE 6.x ARRIVES INCIDENTALLY, from `demos/svelte-official`'s own off-catalog
 * `typescript` declaration. It is NOT catalog-governed. If that demo drops it, the
 * parser under this arbiter changes with NO FILE IN THIS REPO CHANGING - exactly
 * the class the asserted-toolchain-fact mitigation exists for. ASSERT, DO NOT PIN:
 * `test/gate.test.ts` re-reads both resolved package.json files, so drift goes RED
 * instead of drifting silently.
 */
export const ANGULAR_ARBITER_TOOLCHAIN = {
	typescriptUnderTheArbiter: '6.0.3',
	typescriptUnderTsc: '5.9.3',
	angularCompiler: '22.0.8',
	angularEslint: '22.1.0',
	provenance:
		'typescript 6.0.3 is supplied INCIDENTALLY by demos/svelte-official, which declares typescript off-catalog. It is not governed by pnpm-workspace.yaml, whose catalog pins typescript ^5.9.3 - the version `pnpm check` runs. If demos/svelte-official drops its off-catalog TypeScript, the parser under this arbiter changes with no file in this repo changing.',
} as const;

const ESLINT_TS_RULES = [
	...ANGULAR_ESLINT_TS_RULES_DERIVED,
	...ANGULAR_ESLINT_RULES_ADDED.map((entry) => entry.rule),
];

function severities(rules: readonly string[]): Record<string, 'error'> {
	return Object.fromEntries(rules.map((rule) => [rule, 'error' as const]));
}

let cachedEslint: ESLint | undefined;
function makeEslint(): ESLint {
	cachedEslint ??= new ESLint({
		cwd: PACKAGE_ROOT,
		overrideConfigFile: true,
		// Emitted output must not be able to configure the gate that reads it.
		allowInlineConfig: false,
		overrideConfig: [
			{
				files: ['**/*.ts'],
				languageOptions: {
					parser: tsParser as never,
					parserOptions: { ecmaVersion: 'latest', sourceType: 'module' },
				},
				plugins: { '@angular-eslint': ngPlugin as never },
				// The processor is what lets the TEMPLATE rules reach an INLINE
				// template. Without it the four template rules would sit silent on
				// single-file components and the arbiter would be half a gate.
				processor: tplPlugin.processors['extract-inline-html'] as never,
				rules: severities(ESLINT_TS_RULES),
			},
			{
				files: ['**/*.html'],
				languageOptions: { parser: templateParser as never },
				plugins: { '@angular-eslint/template': tplPlugin as never },
				rules: severities(ANGULAR_ESLINT_TEMPLATE_RULES_DERIVED),
			},
		] as never,
	});
	return cachedEslint;
}

/**
 * `eslint:` marks a THIRD-PARTY arbiter, following the qwik, svelte and vue
 * gates. The frameless-owned policies in this file keep their BARE ids: they are
 * not eslint rules at all - they are hand-written walkers over Angular's own
 * template AST and TypeScript's own module AST - so a `frameless/` prefix would
 * imply a plugin that does not exist. The distinction the prefix carries is "who
 * decided this", and here it is carried by presence versus absence of `eslint:`.
 */
function eslintPolicyId(ruleId: string | null | undefined): string {
	return `eslint:${ruleId ?? 'parse'}`;
}

async function eslintViolations(file: string, source: string): Promise<GateViolation[]> {
	const [result] = await makeEslint().lintText(source, {
		filePath: resolve(PACKAGE_ROOT, file),
		warnIgnored: false,
	});
	return (result?.messages ?? []).map((message) =>
		violation(file, eslintPolicyId(message.ruleId), message.message, message.line ?? null),
	);
}

const ESLINT_POLICIES = ANGULAR_ESLINT_RULES_APPLIED.map((rule) => ({
	id: `eslint:${rule}`,
	dossierRef: 'frameless-angular-v1 T003 lint arbiter' as const,
}));

export const ANGULAR_GATE_POLICIES = [
	{ id: 'generated-header', dossierRef: 'frameless-angular-v1 T002 ruling 4 (both arbiters, compiler first)' },
	{ id: 'template-parse', dossierRef: 'frameless-angular-v1 T002 ruling 4 (both arbiters, compiler first)' },
	{ id: 'whitespace-stable-text', dossierRef: 'frameless-angular-v1 T003 measurement M1' },
	{
		id: 'no-signal-members',
		dossierRef: 'frameless-angular-v1 T005 (decorator-vs-signal, DENIED at G5 and G6)',
	},
	{ id: 'no-two-way-binding', dossierRef: 'frameless-angular-v1 T002 also ruled (IR-1/IR-2)' },
	{
		id: 'no-output-emitter',
		dossierRef: 'frameless-angular-v1 T002 ruling 2 (onTrace is an @Input)',
	},
	{
		id: 'no-change-detection-override',
		dossierRef: 'frameless-angular-v1 T003a ruling 2 (OnPush is the Angular 22 default)',
	},
	{ id: 'no-stop-propagation', dossierRef: 'frameless-angular-v1 T002 also ruled (IR-5)' },
	{ id: 'getter-expression-purity', dossierRef: 'frameless-angular-v1 T002 also ruled (IR-7)' },
	{
		id: 'baseline-form-inventory',
		dossierRef: 'frameless-angular-v1 T002 also ruled (IR-4 baseline form inventory)',
	},
	persistenceArtifactPolicy(),
	...ESLINT_POLICIES,
] as const satisfies readonly GatePolicy[];

const POLICIES = new Map<string, GatePolicy>(
	ANGULAR_GATE_POLICIES.map((policy) => [policy.id, policy]),
);

function violation(
	file: string,
	policy: string,
	message: string,
	line: number | null = null,
): GateViolation {
	return {
		file,
		policy,
		dossierRef:
			POLICIES.get(policy)?.dossierRef ??
			// `eslint:parse` is the only unpublished eslint policy: it is what a
			// message with no ruleId becomes, which is a parser failure rather than a
			// rule verdict. It still belongs to the arbiter.
			(policy.startsWith('eslint:')
				? 'frameless-angular-v1 T003 lint arbiter'
				: 'frameless-angular-v1 T002 ruling 4 (both arbiters, compiler first)'),
		message,
		line,
	};
}

/** Depth-first walk over a TypeScript-ESLint AST, never following back-references. */
function walkTs(value: unknown, visit: (record: Node) => void): void {
	if (!value || typeof value !== 'object') return;
	if (Array.isArray(value)) {
		value.forEach((entry) => walkTs(entry, visit));
		return;
	}
	const record = value as Node;
	if (typeof record.type !== 'string') return;
	visit(record);
	for (const [key, child] of Object.entries(record)) {
		if (key === 'parent' || key === 'loc' || key === 'range') continue;
		walkTs(child, visit);
	}
}

/**
 * Angular's template AST nodes are CLASS INSTANCES with heterogeneous child
 * fields, so the walk follows an explicit key list rather than every own
 * property - `sourceSpan`, `keySpan` and `value` are span objects and parsed
 * expressions, not template nodes, and descending into them would report an
 * `AST` node kind for every binding.
 */
const TEMPLATE_CHILD_KEYS = [
	'children',
	'branches',
	'attributes',
	'inputs',
	'outputs',
	'references',
	'variables',
	'templateAttrs',
	'directives',
	'cases',
	'contents',
	'empty',
	'item',
] as const;

function walkTemplate(nodes: unknown, visit: (node: Node) => void): void {
	const seen = new Set<unknown>();
	const step = (value: unknown): void => {
		if (!value || typeof value !== 'object') return;
		if (Array.isArray(value)) {
			value.forEach(step);
			return;
		}
		if (seen.has(value)) return;
		seen.add(value);
		const node = value as Node;
		visit(node);
		for (const key of TEMPLATE_CHILD_KEYS) step(node[key]);
	};
	step(nodes);
}

// ---------------------------------------------------------------------------
// the two ASTs this gate reads
// ---------------------------------------------------------------------------

type Parsed = {
	/** The emitted module's TypeScript AST. */
	readonly module: Node;
	/** The exported component class. */
	readonly component: Node | null;
	/** The `@Component({...})` metadata object. */
	readonly metadata: Node | null;
	/** The INLINE template text, exactly as `ng build` would read it. */
	readonly template: string | null;
	/** 1-based source line the template literal opens on. */
	readonly templateLine: number;
	/** Angular's own parse of the inline template. */
	readonly templateNodes: readonly Node[];
	readonly templateErrors: readonly string[];
};

function lineOfTs(node: Node): number | null {
	const line = node.loc?.start?.line;
	return typeof line === 'number' ? line : null;
}

function lineOfTemplate(parsed: Parsed, node: Node): number | null {
	const line = node.sourceSpan?.start?.line;
	return typeof line === 'number' ? parsed.templateLine + line : null;
}

function decoratorNamed(node: Node, name: string): Node | undefined {
	return ((node.decorators ?? []) as Node[]).find(
		(decorator) =>
			decorator.expression?.type === 'CallExpression' &&
			decorator.expression.callee?.type === 'Identifier' &&
			decorator.expression.callee.name === name,
	);
}

function parseEmitted(file: string, source: string): Parsed | null {
	let module: Node;
	try {
		module = tsParser.parse(source, {
			loc: true,
			range: true,
			sourceType: 'module',
		}) as unknown as Node;
	} catch {
		return null;
	}
	let component: Node | null = null;
	walkTs(module, (node) => {
		if (node.type === 'ClassDeclaration' && decoratorNamed(node, 'Component')) component = node;
	});
	const decorator = component ? decoratorNamed(component, 'Component') : undefined;
	const metadata = (decorator?.expression?.arguments?.[0] as Node | undefined) ?? null;
	const templateProperty = ((metadata?.properties ?? []) as Node[]).find(
		(property) => property.type === 'Property' && property.key?.name === 'template',
	);
	const literal = templateProperty?.value as Node | undefined;
	const template =
		literal?.type === 'TemplateLiteral' && literal.quasis?.length === 1
			? String(literal.quasis[0].value?.cooked ?? '')
			: null;
	const parsedTemplate =
		template === null ? null : parseTemplate(template, file.replace(/\.ts$/, '.html'));
	return {
		module,
		component,
		metadata: metadata?.type === 'ObjectExpression' ? metadata : null,
		template,
		templateLine: literal ? (lineOfTs(literal) ?? 1) : 1,
		templateNodes: (parsedTemplate?.nodes ?? []) as Node[],
		templateErrors: (parsedTemplate?.errors ?? []).map((error) => String(error.msg ?? error)),
	};
}

// ---------------------------------------------------------------------------
// IR-7
// ---------------------------------------------------------------------------

/**
 * Methods whose whole purpose is to mutate their receiver. Deliberately NOT a
 * list of "calls" - `this.todos.filter(...)` inside a getter is correct and must
 * stay accepted, which is what stops this policy degenerating into "reject any
 * call".
 */
const KNOWN_MUTATING_METHODS = new Set([
	'add',
	'append',
	'appendChild',
	'assign',
	'clear',
	'copyWithin',
	'defineProperty',
	'delete',
	'fill',
	'insertBefore',
	'pop',
	'push',
	'remove',
	'removeAttribute',
	'replaceChildren',
	'reverse',
	'set',
	'setAttribute',
	'shift',
	'sort',
	'splice',
	'unshift',
	'write',
]);

/**
 * IR-7 - THE CONSERVATIVE GUARD, NOT A PURITY PROOF.
 *
 * `ExpressionSite.expression` is an arbitrary AST node and the IR never asserts
 * that it is pure, while an Angular GETTER - which is how this emitter lowers a
 * `computed` binding - is re-evaluated on EVERY change-detection pass. A getter
 * that mutates therefore does not merely produce a wrong value: it writes on every
 * tick, and Angular reports that (if at all) as a dev-mode
 * ExpressionChangedAfterItHasBeenCheckedError, so absence of a red test is not
 * evidence of correctness. S1's `derived` is trivial and WILL always pass, which
 * is exactly why the green it produces is a vacuum.
 *
 * A real purity proof is a compiler-wide change with no forcing case, so this is
 * the decidable subset instead: a syntactic reject-list applied to the EMITTER'S
 * OWN OUTPUT.
 *
 * WHAT IT CANNOT SEE, stated plainly rather than implied:
 *   - mutation performed inside a function the getter CALLS. `get x() { return
 *     f(); }` is accepted no matter what `f` assigns; the walk never leaves the
 *     getter.
 *   - a mutating method this list does not name, including any method on a
 *     user-defined object, and any mutation through a computed member access.
 *   - a getter with a side effect, which is syntactically indistinguishable from
 *     a property read.
 *   - anything reached through `eval`, `Function`, or a dynamic property name.
 * It is therefore SOUND ONLY as a reject-list: a violation is real, a pass is not
 * a proof.
 */
function impureNodes(root: Node): Array<{ node: Node; reason: string }> {
	const found: Array<{ node: Node; reason: string }> = [];
	walkTs(root, (node) => {
		if (node.type === 'AssignmentExpression')
			found.push({ node, reason: `assignment (${String(node.operator ?? '=')})` });
		else if (node.type === 'UpdateExpression')
			found.push({ node, reason: `update expression (${String(node.operator ?? '')})` });
		else if (node.type === 'UnaryExpression' && node.operator === 'delete')
			found.push({ node, reason: 'delete expression' });
		else if (
			(node.type === 'CallExpression' || node.type === 'NewExpression') &&
			node.callee?.type === 'MemberExpression' &&
			!node.callee.computed &&
			node.callee.property?.type === 'Identifier' &&
			KNOWN_MUTATING_METHODS.has(node.callee.property.name)
		)
			found.push({
				node,
				reason: `call to the known-mutating method .${node.callee.property.name}()`,
			});
	});
	return found;
}

// ---------------------------------------------------------------------------
// the baseline form inventory
// ---------------------------------------------------------------------------

/**
 * THE PRECONDITION THIS ASSERTS, and the one place the Angular lane's answer
 * DIFFERS FROM VUE'S rather than inheriting it.
 *
 * `frameless-angular-v1` T002 deferred IR-4 and did not amend the emitter idiom
 * policy's version corollary. That corollary has two conjuncts, and the second -
 * "the emitter can know the version it is targeting" - is satisfiable two ways: an
 * explicit target-version input, or an emitter that emits ONLY
 * baseline-version-safe forms. The Vue lane took the second way and could claim
 * "safe across the whole Vue 3 line".
 *
 * THAT CLAIM IS UNAVAILABLE HERE AND SAYING SO IS THE POINT. Angular's line runs
 * from 2 to 22, and this emitter's output is NOT safe across it: `@if`/`@for` are
 * Angular 17, and a standalone-by-default component is Angular 19. The honest
 * discharge is therefore an explicit allowlist whose entries each carry a version
 * FLOOR, plus a lane floor computed as the MAX over the entries - a recorded
 * number a test re-derives, not a silent widening. `ANGULAR_BASELINE_FLOOR` below
 * is that number and `test/gate.test.ts` re-derives it from the inventory.
 *
 * Two of those floors are not free choices. `@angular-eslint/template/prefer-
 * control-flow` is IN THE APPLIED SET and reports `*ngIf`/`*ngFor` directly
 * (measured), and `*ngIf` would additionally need an `imports:` entry the IR does
 * not declare. So the third-party arbiter itself pushes this lane above 17.
 *
 * FLOOR HONESTY IS THE POINT. A floor is a CLAIM about the earliest version at
 * which the form is available and means what the emitter needs; it is a lower
 * bound and need not be tight. `status: 'unverified'` carries the reason it could
 * not be checked, and a guessed floor recorded as verified is precisely the
 * failure this exists to stop. A `verified` entry must cite a file inside a
 * RESOLVED package and verbatim text in it; `test/gate.test.ts` re-reads every
 * citation and calibrates that checker in both directions.
 *
 * WHAT IT CANNOT SEE, stated plainly: it reads emitted STRUCTURE, so it cannot
 * know what a form MEANS at a version this repo does not have installed. It
 * catches a new form arriving unannounced. It does not catch a form whose
 * semantics changed under a fixed spelling.
 */
export type BaselineFormKind =
	| 'import'
	| 'decorator'
	| 'component-metadata'
	| 'class-heritage'
	| 'class-member'
	| 'template-node'
	| 'template-binding'
	| 'control-flow';

export type FloorEvidence =
	| {
			readonly status: 'verified';
			/** Path INSIDE a resolved package. Re-read by the gate test. */
			readonly package: string;
			readonly file: string;
			/** Verbatim text that must be present at that path. */
			readonly needle: string;
	  }
	| { readonly status: 'unverified'; readonly reason: string };

export type BaselineForm = {
	readonly kind: BaselineFormKind;
	readonly form: string;
	/** The earliest Angular version this inventory CLAIMS the form is safe at. */
	readonly floor: string;
	readonly evidence: FloorEvidence;
};

/**
 * EVERY FLOOR BELOW READS `unverified`, and the reason is a MEASURED property of
 * the resolved package rather than laziness: `@angular/compiler@22.0.8` as
 * installed ships NO CHANGELOG and not a single `@since` tag - it contains
 * exactly `LICENSE`, `README.md`, `package.json`, `fesm2022/` and `types/`.
 * Presence at the pin is not a floor; it is equally consistent with "2.0" and
 * with "nobody wrote one down".
 */
const CORE_DECORATOR_FLOOR_REASON =
	'@Component and @Input are the original Angular 2 decorator surface, which is documentary evidence from the Angular release history rather than from any artifact this repo has. The resolved @angular/compiler ships no CHANGELOG and no @since tag anywhere, so the floor could not be checked against something on disk.';

const CONTROL_FLOW_FLOOR_REASON =
	'Built-in control flow (@if/@for/@else) shipped in Angular 17.0 as a developer-preview and was stable at 17.2, so 17.0 is a lower bound taken from the release history. The resolved @angular/compiler parses it at 22.0.8 - measured - but presence at the pin dates nothing, which is exactly the inference this column exists to refuse.';

const STANDALONE_FLOOR_REASON =
	'A component with no `standalone` key is standalone only from Angular 19, where the property began defaulting to true; at 14-18 the same emitted bytes declare a component that needs an NgModule. This is the HIGHEST floor in the inventory and therefore the one that sets ANGULAR_BASELINE_FLOOR. Taken from the release history: nothing in the resolved packages dates it.';

const TEMPLATE_NODE_FLOOR_REASON =
	'A node kind of the Angular template parser present for the whole Angular 2+ line, so 2.0 is a safe lower bound rather than a tight one. The resolved package dates neither the class nor its name.';

const CHANGE_DETECTOR_FLOOR_REASON =
	'ChangeDetectorRef and its markForCheck() are part of the original Angular 2 change-detection surface, so 2.0 is a safe lower bound rather than a tight one. What is NOT documentary is what the call MEANS here: under zoneless change detection markForCheck() also NOTIFIES THE SCHEDULER, which is what makes it schedule a tick rather than merely flag a view, and that behaviour is the reason the emitter spells it. That semantic is Angular 18+, and it is covered by the 19.0 standalone floor this inventory already carries rather than by a second entry - a form whose meaning changed under a fixed spelling is exactly what this inventory says it cannot see, so it is written down here instead.';

const INJECT_FLOOR_REASON =
	'The standalone inject() function shipped in Angular 14.0, which is a lower bound taken from the release history. The resolved @angular/core ships no CHANGELOG and no @since tag, so the floor could not be checked against something on disk; the entry is below this lane\'s 19.0 standalone floor either way, so it does not move ANGULAR_BASELINE_FLOOR.';

const LIFECYCLE_FLOOR_REASON =
	'ngOnInit and the OnInit interface are part of the original Angular 2 component lifecycle. Documentary, not checkable against an artifact this repo has.';

export const BASELINE_FORM_INVENTORY: readonly BaselineForm[] = [
	{
		kind: 'import',
		form: '@angular/core#Component',
		floor: '2.0',
		evidence: { status: 'unverified', reason: CORE_DECORATOR_FLOOR_REASON },
	},
	{
		kind: 'import',
		form: '@angular/core#Input',
		floor: '2.0',
		evidence: { status: 'unverified', reason: CORE_DECORATOR_FLOOR_REASON },
	},
	{
		kind: 'import',
		form: '@angular/core#OnInit',
		floor: '2.0',
		evidence: { status: 'unverified', reason: LIFECYCLE_FLOOR_REASON },
	},
	// Both entered the inventory with S8, the corpus's async scenario, and both
	// are emitted ONLY into a class that has an async handler. See
	// `notifyAfterSuspension` in ../emitter/index.ts for the browser measurement
	// that made them necessary: without the notification the post-`await` writes
	// land in the fields and the DOM is never re-rendered.
	{
		kind: 'import',
		form: '@angular/core#ChangeDetectorRef',
		floor: '2.0',
		evidence: { status: 'unverified', reason: CHANGE_DETECTOR_FLOOR_REASON },
	},
	{
		kind: 'import',
		form: '@angular/core#inject',
		floor: '14.0',
		evidence: { status: 'unverified', reason: INJECT_FLOOR_REASON },
	},
	{
		kind: 'decorator',
		form: 'Component',
		floor: '2.0',
		evidence: { status: 'unverified', reason: CORE_DECORATOR_FLOOR_REASON },
	},
	{
		kind: 'decorator',
		form: 'Input',
		floor: '2.0',
		evidence: { status: 'unverified', reason: CORE_DECORATOR_FLOOR_REASON },
	},
	{
		kind: 'component-metadata',
		form: 'selector',
		floor: '2.0',
		evidence: { status: 'unverified', reason: CORE_DECORATOR_FLOOR_REASON },
	},
	{
		kind: 'component-metadata',
		form: 'template',
		floor: '2.0',
		evidence: { status: 'unverified', reason: CORE_DECORATOR_FLOOR_REASON },
	},
	{
		// The ABSENCE of `standalone` is itself a version-gated form, and it is the
		// entry that sets this lane's floor. Recorded as a form so it cannot be lost.
		kind: 'component-metadata',
		form: '(no standalone key)',
		floor: '19.0',
		evidence: { status: 'unverified', reason: STANDALONE_FLOOR_REASON },
	},
	{
		kind: 'class-heritage',
		form: 'implements',
		floor: '2.0',
		evidence: { status: 'unverified', reason: LIFECYCLE_FLOOR_REASON },
	},
	// `get` rather than `getter`: this is `MethodDefinition.kind` verbatim, so a
	// `set` or a `constructor` arriving in emitted output is an un-inventoried form
	// rather than something a friendlier spelling would have absorbed.
	...(['property', 'get', 'method'] as const).map(
		(form): BaselineForm => ({
			kind: 'class-member',
			form,
			floor: '2.0',
			evidence: { status: 'unverified', reason: CORE_DECORATOR_FLOOR_REASON },
		}),
	),
	...(
		[
			'Element',
			'Text',
			'BoundText',
			'TextAttribute',
			'BoundAttribute',
			'BoundEvent',
			'Variable',
		] as const
	).map(
		(form): BaselineForm => ({
			kind: 'template-node',
			form,
			floor: '2.0',
			evidence: { status: 'unverified', reason: TEMPLATE_NODE_FLOOR_REASON },
		}),
	),
	...(['IfBlock', 'IfBlockBranch', 'ForLoopBlock'] as const).map(
		(form): BaselineForm => ({
			kind: 'template-node',
			form,
			floor: '17.0',
			evidence: { status: 'unverified', reason: CONTROL_FLOW_FLOOR_REASON },
		}),
	),
	...(['@if', '@else', '@for'] as const).map(
		(form): BaselineForm => ({
			kind: 'control-flow',
			form,
			floor: '17.0',
			evidence: { status: 'unverified', reason: CONTROL_FLOW_FLOOR_REASON },
		}),
	),
	...(['Property', 'Attribute', 'event', 'interpolation'] as const).map(
		(form): BaselineForm => ({
			kind: 'template-binding',
			form,
			floor: '2.0',
			evidence: { status: 'unverified', reason: TEMPLATE_NODE_FLOOR_REASON },
		}),
	),
];

const INVENTORY = new Set(BASELINE_FORM_INVENTORY.map((entry) => `${entry.kind}:${entry.form}`));

/**
 * The lane's version floor, DERIVED as the max over the inventory rather than
 * written down twice. Emitted output is claimed safe at this Angular version and
 * NOT below it, which is a narrower and more honest claim than the Vue lane's
 * "safe across the whole major line" - see the inventory's doc comment.
 */
export const ANGULAR_BASELINE_FLOOR: string = BASELINE_FORM_INVENTORY.map(
	(entry) => entry.floor,
).reduce((highest, floor) => {
	const [left, right] = [highest.split('.').map(Number), floor.split('.').map(Number)];
	return (right[0]! - left[0]! || right[1]! - left[1]!) > 0 ? floor : highest;
}, '0.0');

export type ObservedForm = {
	readonly kind: BaselineFormKind;
	readonly form: string;
	readonly line: number | null;
};

function bindingTypeName(type: unknown): string {
	const name = (BindingType as unknown as Record<number, string>)[type as number];
	return typeof name === 'string' ? name : `TYPE_${String(type)}`;
}

function templateNodeName(node: Node): string {
	return node?.constructor?.name ?? 'UNKNOWN';
}

function observeForms(parsed: Parsed): ObservedForm[] {
	const found: ObservedForm[] = [];
	walkTs(parsed.module, (node) => {
		if (node.type === 'ImportDeclaration') {
			const from = String((node.source as Node | undefined)?.value ?? '?');
			const specifiers = (node.specifiers ?? []) as Node[];
			const line = lineOfTs(node);
			if (specifiers.length === 0) found.push({ kind: 'import', form: `${from}#*`, line });
			for (const specifier of specifiers)
				found.push({
					kind: 'import',
					form: `${from}#${
						specifier.type === 'ImportSpecifier'
							? String(specifier.imported?.name ?? '?')
							: specifier.type === 'ImportDefaultSpecifier'
								? 'default'
								: '*'
					}`,
					line,
				});
		}
		if (node.type === 'Decorator')
			found.push({
				kind: 'decorator',
				form: String(node.expression?.callee?.name ?? node.expression?.name ?? '?'),
				line: lineOfTs(node),
			});
	});
	for (const property of (parsed.metadata?.properties ?? []) as Node[])
		found.push({
			kind: 'component-metadata',
			form: String(property.key?.name ?? property.key?.value ?? '?'),
			line: lineOfTs(property),
		});
	if (parsed.metadata)
		found.push({ kind: 'component-metadata', form: '(no standalone key)', line: null });
	for (const clause of (parsed.component?.implements ?? []) as Node[])
		found.push({ kind: 'class-heritage', form: 'implements', line: lineOfTs(clause) });
	if (parsed.component?.superClass)
		found.push({ kind: 'class-heritage', form: 'extends', line: lineOfTs(parsed.component) });
	for (const member of (parsed.component?.body?.body ?? []) as Node[]) {
		const line = lineOfTs(member);
		if (member.type === 'PropertyDefinition')
			found.push({ kind: 'class-member', form: member.static ? 'static-property' : 'property', line });
		else if (member.type === 'MethodDefinition')
			found.push({
				kind: 'class-member',
				form: member.kind === 'method' ? 'method' : String(member.kind),
				line,
			});
		else found.push({ kind: 'class-member', form: String(member.type), line });
	}

	walkTemplate(parsed.templateNodes, (node) => {
		const name = templateNodeName(node);
		const line = lineOfTemplate(parsed, node);
		found.push({ kind: 'template-node', form: name, line });
		if (name === 'BoundText') found.push({ kind: 'template-binding', form: 'interpolation', line });
		if (name === 'BoundAttribute')
			found.push({ kind: 'template-binding', form: bindingTypeName(node.type), line });
		if (name === 'BoundEvent') found.push({ kind: 'template-binding', form: 'event', line });
		if (name === 'IfBlock') found.push({ kind: 'control-flow', form: '@if', line });
		if (name === 'IfBlockBranch' && node.expression === null)
			found.push({ kind: 'control-flow', form: '@else', line });
		if (name === 'ForLoopBlock') {
			found.push({ kind: 'control-flow', form: '@for', line });
			if (node.empty) found.push({ kind: 'control-flow', form: '@empty', line });
		}
	});
	return found;
}

/**
 * Every form the emitted source actually contains, deduped and sorted. Exported
 * because a fail-closed allowlist that observes NOTHING passes vacuously, and
 * `test/gate.test.ts` pins the observed set of the shipped corpus against a
 * literal - so a walk that stopped descending is a red test rather than a silently
 * green gate.
 */
export function collectEmittedForms(source: string): ReadonlyArray<{
	readonly kind: BaselineFormKind;
	readonly form: string;
}> {
	const parsed = parseEmitted('generated/inline.ts', source);
	if (!parsed) throw new Error('collectEmittedForms received a source TypeScript could not parse');
	const seen = new Set<string>();
	const forms: Array<{ kind: BaselineFormKind; form: string }> = [];
	for (const observation of observeForms(parsed)) {
		const key = `${observation.kind}:${observation.form}`;
		if (seen.has(key)) continue;
		seen.add(key);
		forms.push({ kind: observation.kind, form: observation.form });
	}
	return forms.sort((left, right) =>
		`${left.kind}:${left.form}`.localeCompare(`${right.kind}:${right.form}`),
	);
}

function inventoryViolations(file: string, parsed: Parsed): GateViolation[] {
	const violations: GateViolation[] = [];
	const reported = new Set<string>();
	for (const observation of observeForms(parsed)) {
		const key = `${observation.kind}:${observation.form}`;
		if (INVENTORY.has(key) || reported.has(key)) continue;
		reported.add(key);
		violations.push(
			violation(
				file,
				'baseline-form-inventory',
				`Emitted Angular source uses the ${observation.kind} form ${JSON.stringify(observation.form)}, which is not in the baseline form inventory. IR-4 is DEFERRED, so this emitter's only discharge of the version corollary's second conjunct is an explicit allowlist with a recorded floor per entry; a new form has to be added to BASELINE_FORM_INVENTORY with a version floor and an honest floor-evidence status, and it may raise ANGULAR_BASELINE_FLOOR`,
				observation.line,
			),
		);
	}
	return violations;
}

// ---------------------------------------------------------------------------
// policies
// ---------------------------------------------------------------------------

/**
 * THE MEASURED WHITESPACE POLICY (T003 measurement M1), stated as a property of
 * the RESULT rather than of the layout that produced it.
 *
 * `parseTemplate` applies Angular's `preserveWhitespaces: false` default, so the
 * nodes read here are already condensed - MEASURED at 22.0.8, which is what makes
 * this readable straight off Angular's own tree instead of reimplementing the
 * rule. Condense drops a whitespace-ONLY text node outright and collapses a run of
 * two or more whitespace characters inside a content-bearing node to a single
 * space, but a LONE newline survives verbatim.
 *
 * All the failures land in one observable, so one check catches them all: AFTER
 * CONDENSE, NO EMITTED TEXT MAY CARRY AN UNTRIMMED EDGE - plain text or an
 * interpolation's literal segments.
 *
 *   `<button>\n\tincrement\n</button>` -> Text `" increment\n"`   rejected
 *   `<p>{{ a }}\n/{{ b }}</p>`         -> BoundText `["","\n/",""]` rejected, and
 *                                         this is S2's `1/2` becoming `1\n/2`
 *   the shipped layout                 -> the whitespace node is gone  accepted
 *
 * BoundText is read through `ast.strings`, which is where the LITERAL segments of
 * an interpolation live; the empty leading and trailing segments of
 * `{{ a }}/{{ b }}` are normal and are skipped, so this is not "reject any
 * interpolation".
 */
function whitespaceViolations(file: string, parsed: Parsed): GateViolation[] {
	const violations: GateViolation[] = [];
	walkTemplate(parsed.templateNodes, (node) => {
		const name = templateNodeName(node);
		const line = lineOfTemplate(parsed, node);
		if (name === 'Text') {
			const content = String(node.value ?? '');
			if (content !== content.trim() || content.length === 0)
				violations.push(
					violation(
						file,
						'whitespace-stable-text',
						`Emitted Angular template has the condensed text node ${JSON.stringify(content)}, which carries an untrimmed edge. Angular's preserveWhitespaces:false default condenses a run of whitespace to a single space and keeps a lone newline verbatim, so this text would render differently from the react, solid, qwik, svelte and vue lanes`,
						line,
					),
				);
			return;
		}
		if (name !== 'BoundText') return;
		for (const segment of (node.value?.ast?.strings ?? []) as string[]) {
			if (segment.length === 0 || segment === segment.trim()) continue;
			violations.push(
				violation(
					file,
					'whitespace-stable-text',
					`Emitted Angular template has the interpolation text segment ${JSON.stringify(segment)}, which carries an untrimmed edge and would render differently from the react, solid, qwik, svelte and vue lanes`,
					line,
				),
			);
		}
	});
	return violations;
}

/**
 * THE ROW THAT IS NOW THE ONLY THING PINNING A SETTLED RULING. It no longer holds a
 * question open; it enforces an answer, and the arbiter cannot do it.
 *
 * `docs/goals/frameless-idiom-policy-v1/notes/T006-cold-agent.md` ruled decorator
 * `@Input()`/`@Output()` versus signal `input()`/`output()` NO-SUGAR, decided
 * independently TWICE with no Angular in the repo. `frameless-angular-v1` T005 then
 * re-ran all six gates against this landed lane at `@angular/core` 22.0.8 and the
 * ruling HELD: G1 PASS, G2 PASS, G3 PASS, G4 PASS (narrowed), G5 FAIL, G6 FAIL -
 * DENIED, not deferred, and Gate 5 decides. Worked example 11 in
 * `docs/emitter-idiom-policy.md`; the decision site is `propMembers()` in
 * `../emitter/index.ts`.
 *
 * GATE 5's TWO MEASURED LIMBS, so a future reader does not have to fetch them:
 * a `computed()` over `instance.derived` stays `kit:2` under `@Input()` while the
 * DOM reads `kit:10`, and returns `kit:10` under `input()`; and the exported member
 * type changes `any` -> `InputSignal<any>`, turning a consumer write into a
 * `TypeError`. NOT the reason, and refuted by measurement: "required inputs throw
 * NG0950" - plain `input()` read unset returns `undefined` exactly as `@Input()`
 * does, and `input.required()` is unreachable for this emitter.
 *
 * GATE 6 FAILED, which is why this policy exists rather than a behavioural check:
 * `pnpm e2e` would NOT go red on this sugar, because both arms render identically.
 * The six-row green proves activation neutrality; it does not pin the form choice.
 *
 * MEASURED, and this is why the policy is frameless-owned rather than delegated:
 * `@angular-eslint/prefer-signals` holds the OPPOSITE view - but upstream did NOT
 * put it in `recommended`, it lives in `all`. So a signal member draws ZERO
 * messages from the applied set (measured on a planted `seed = input()` mutant).
 * Nothing but this policy stands between the emitter and a ruling nothing enforces.
 */
const SIGNAL_APIS = new Set([
	'computed',
	'contentChild',
	'contentChildren',
	'effect',
	'input',
	'linkedSignal',
	'model',
	'output',
	'outputFromObservable',
	'resource',
	'signal',
	'toObservable',
	'toSignal',
	'viewChild',
	'viewChildren',
]);

function signalViolations(file: string, parsed: Parsed): GateViolation[] {
	const violations: GateViolation[] = [];
	walkTs(parsed.module, (node) => {
		if (
			node.type !== 'CallExpression' ||
			node.callee?.type !== 'Identifier' ||
			!SIGNAL_APIS.has(String(node.callee.name))
		)
			return;
		violations.push(
			violation(
				file,
				'no-signal-members',
				`Emitted Angular source calls ${String(node.callee.name)}(); the decorator-vs-signal member declaration was ruled NO-SUGAR twice independently (frameless-idiom-policy-v1 T006) and frameless-angular-v1 T005 re-ran all six gates against this landed lane at @angular/core 22.0.8 and upheld it - DENIED, not deferred, decided at Gate 5 (a computed() over instance.derived diverges from the rendered DOM under @Input() but not under input(), and the exported member type changes any -> InputSignal<any>, turning a consumer write into a TypeError). Gate 6 also FAILED: pnpm e2e would NOT go red on this sugar, because both arms render identically. @angular-eslint/prefer-signals holds the opposite view but upstream keeps it in \`all\`, not \`recommended\`, so the applied arbiter is silent here by measurement - this policy is the only thing standing between the emitter and a ruling nothing enforces. See worked example 11 in docs/emitter-idiom-policy.md`,
				lineOfTs(node),
			),
		);
	});
	return violations;
}

/**
 * IR-1 gives no bindable prop kind and IR-2 no emit concept, so two-way binding is
 * out of scope on two independent axes.
 *
 * MEASURED: `[(ngModel)]="draft"` draws ZERO messages from the applied set -
 * `@angular-eslint/template/banana-in-box` only reports the `([x])` MISORDERING,
 * not the construct - so this is another class only a frameless-owned policy sees.
 * Read off Angular's own parse (`BindingType.TwoWay`) rather than off the text.
 */
function twoWayViolations(file: string, parsed: Parsed): GateViolation[] {
	const violations: GateViolation[] = [];
	walkTemplate(parsed.templateNodes, (node) => {
		const name = templateNodeName(node);
		const line = lineOfTemplate(parsed, node);
		if (name === 'BoundAttribute' && node.type === BindingType.TwoWay)
			violations.push(
				violation(
					file,
					'no-two-way-binding',
					`Emitted Angular template two-way binds ${String(node.name)}; two-way binding needs a bindable prop kind the IR does not have (IR-1) and an emit concept it does not have (IR-2)`,
					line,
				),
			);
		if (
			(name === 'BoundAttribute' || name === 'BoundEvent') &&
			/^ngModel(?:Change)?$/.test(String(node.name ?? ''))
		)
			violations.push(
				violation(
					file,
					'no-two-way-binding',
					`Emitted Angular template binds ${String(node.name)}; ngModel is FormsModule machinery the IR does not declare and would additionally need an imports: entry on the standalone component`,
					line,
				),
			);
	});
	return violations;
}

/**
 * RULING 2 - `onTrace` is an `@Input()`, never an `@Output()`/`EventEmitter`.
 *
 * Decided by the CORPUS rather than by idiom: `EventEmitter.emit()` takes ONE
 * value and the corpus calls `onTrace` with TWO and THREE positional arguments
 * with the DOM event third, so an output forces an emitter-invented wrapper object
 * no other lane has. Arity is VARIABLE within one corpus, so there is no
 * non-arbitrary payload shape.
 *
 * MEASURED, and worth recording because the two authorities AGREE by different
 * mechanisms: a planted `@Output() onTrace = new EventEmitter()` also draws
 * `@angular-eslint/no-output-on-prefix` from the applied set, which reaches the
 * same refusal from Angular's own naming guidance rather than from the IR.
 */
function outputViolations(file: string, parsed: Parsed): GateViolation[] {
	const violations: GateViolation[] = [];
	walkTs(parsed.module, (node) => {
		const line = lineOfTs(node);
		if (
			node.type === 'Decorator' &&
			(node.expression?.callee?.name === 'Output' || node.expression?.name === 'Output')
		)
			violations.push(
				violation(
					file,
					'no-output-emitter',
					'Emitted Angular source declares an @Output(); EventEmitter.emit takes one value and the corpus calls onTrace with two AND three positional arguments with the DOM event third, so an output forces an emitter-invented wrapper object no other lane has',
					line,
				),
			);
		if (node.type === 'NewExpression' && node.callee?.name === 'EventEmitter')
			violations.push(
				violation(
					file,
					'no-output-emitter',
					'Emitted Angular source constructs an EventEmitter; the IR declares onTrace as a callback PROP (ComponentPropExpression.kind "callback"), while EnrichedEventRecord - the IR\'s actual event concept - binds to a hostNodeId that onTrace does not have',
					line,
				),
			);
	});
	return violations;
}

/**
 * At Angular 22 `OnPush` IS the default and
 * `@angular-eslint/prefer-on-push-component-change-detection` - which IS in the
 * applied set - reports only an explicit opt-out. Emitting NO `changeDetection`
 * key is therefore correct, and the consequence a downstream lane must carry is
 * that EMITTED COMPONENTS ARE OnPush-CHECKED. Ruled by frameless-angular-v1 T003a.
 */
function changeDetectionViolations(file: string, parsed: Parsed): GateViolation[] {
	const violations: GateViolation[] = [];
	for (const property of (parsed.metadata?.properties ?? []) as Node[])
		if (property.key?.name === 'changeDetection')
			violations.push(
				violation(
					file,
					'no-change-detection-override',
					'Emitted Angular source sets changeDetection; at Angular 22 OnPush IS the default, so any explicit value is an opt-out that @angular-eslint/prefer-on-push-component-change-detection reports, and emitted components are OnPush-checked by design',
					lineOfTs(property),
				),
			);
	return violations;
}

function stopPropagationViolations(file: string, parsed: Parsed): GateViolation[] {
	const violations: GateViolation[] = [];
	walkTs(parsed.module, (node) => {
		if (
			node.type === 'CallExpression' &&
			node.callee?.type === 'MemberExpression' &&
			!node.callee.computed &&
			node.callee.property?.type === 'Identifier' &&
			node.callee.property.name === 'stopPropagation'
		)
			violations.push(
				violation(
					file,
					'no-stop-propagation',
					'Emitted Angular source calls stopPropagation(); the corpus has zero instances across all twelve goldens, so the emitter fails closed on the declared action rather than growing an emitter path nothing can test',
					lineOfTs(node),
				),
			);
	});
	return violations;
}

function getterViolations(file: string, parsed: Parsed): GateViolation[] {
	const violations: GateViolation[] = [];
	for (const member of (parsed.component?.body?.body ?? []) as Node[]) {
		if (member.type !== 'MethodDefinition' || member.kind !== 'get') continue;
		for (const { node, reason } of impureNodes(member.value as Node))
			violations.push(
				violation(
					file,
					'getter-expression-purity',
					`Emitted component getter ${String(member.key?.name ?? '?')} contains a ${reason}; IR-7 never asserts purity, and Angular re-evaluates a getter on every change-detection pass`,
					lineOfTs(node),
				),
			);
	}
	return violations;
}

/**
 * ARBITER 1, as a standing gate policy rather than only an emitter precondition.
 * `frameless-angular-v1` T002 ruling 4 makes it PRIMARY and requires it be
 * asserted as an EXACT EMPTY error set over all three templates: it interrogates
 * this board's central risk directly - did forced lowering produce a template
 * Angular's own parser accepts?
 */
function templateParseViolations(file: string, parsed: Parsed): GateViolation[] {
	if (parsed.template === null)
		return [
			violation(
				file,
				'template-parse',
				'Emitted Angular source has no inline `template:` template literal on its @Component decorator, so Angular\'s own parser has nothing to arbitrate',
				1,
			),
		];
	return parsed.templateErrors.map((message) =>
		violation(
			file,
			'template-parse',
			`@angular/compiler parseTemplate reported: ${message}`,
			parsed.templateLine,
		),
	);
}

async function sourceViolations(file: string, source: string): Promise<GateViolation[]> {
	const violations: GateViolation[] = [];
	if (!source.startsWith(GENERATED_HEADER))
		violations.push(
			violation(
				file,
				'generated-header',
				`Emitted Angular source must open with ${JSON.stringify(GENERATED_HEADER)}`,
				1,
			),
		);
	const parsed = parseEmitted(file, source);
	if (!parsed)
		return [
			...violations,
			violation(file, 'generated-header', 'TypeScript could not parse emitted source', 1),
		];
	if (!parsed.component)
		return [
			...violations,
			violation(
				file,
				'generated-header',
				'Emitted Angular source declares no class carrying an @Component decorator',
				1,
			),
		];
	violations.push(...templateParseViolations(file, parsed));
	violations.push(...inventoryViolations(file, parsed));
	violations.push(...whitespaceViolations(file, parsed));
	violations.push(...signalViolations(file, parsed));
	violations.push(...twoWayViolations(file, parsed));
	violations.push(...outputViolations(file, parsed));
	violations.push(...changeDetectionViolations(file, parsed));
	violations.push(...stopPropagationViolations(file, parsed));
	violations.push(...getterViolations(file, parsed));
	return violations;
}

function persistenceViolations(file: string, artifact: EnrichedIR): GateViolation[] | undefined {
	const persistence = (artifact.records as { readonly persistence?: unknown }).persistence;
	if (!Array.isArray(persistence)) return undefined;
	if (persistence.length === 0) return [];
	return [
		violation(
			file,
			'persistence-render-lowering',
			'Angular emission fails closed on persistence-bearing IR; render-time persistence has no Angular lowering yet',
		),
	];
}

// ---------------------------------------------------------------------------
// entry points
// ---------------------------------------------------------------------------

async function collectTsFiles(root: string, directory: string): Promise<string[]> {
	const absolute = resolve(root, directory);
	const entries = await readdir(absolute, { withFileTypes: true }).catch(
		(error: NodeJS.ErrnoException) => {
			if (error.code === 'ENOENT') return [];
			throw error;
		},
	);
	const files: string[] = [];
	for (const entry of entries) {
		const child = resolve(absolute, entry.name);
		if (entry.isDirectory()) files.push(...(await collectTsFiles(root, relative(root, child))));
		else if (entry.isFile() && entry.name.endsWith('.ts'))
			files.push(normalize(relative(root, child)));
	}
	return files;
}

export async function discoverGeneratedFiles(
	options: { readonly cwd?: string; readonly directory?: string } = {},
): Promise<string[]> {
	const cwd = resolve(options.cwd ?? PACKAGE_ROOT);
	return (await collectTsFiles(cwd, options.directory ?? 'generated')).sort();
}

/** ASYNC because `ESLint.lintText` is, matching the Svelte and Vue gate signatures. */
export async function checkSources(
	entries: ReadonlyArray<{
		readonly file: string;
		readonly source: string;
		readonly artifact?: EnrichedIR;
	}>,
): Promise<GateResult> {
	const violations: GateViolation[] = [];
	const unevaluatedPolicies = new Set<string>();
	for (const { file, source, artifact } of entries) {
		violations.push(...(await sourceViolations(file, source)));
		violations.push(...(await eslintViolations(file, source)));
		const artifactViolations = artifact ? persistenceViolations(file, artifact) : undefined;
		if (artifactViolations) violations.push(...artifactViolations);
		else unevaluatedPolicies.add('persistence-render-lowering');
	}
	const result = {
		files: entries.map((entry) => entry.file),
		policies: ANGULAR_GATE_POLICIES,
		violations,
	} as unknown as GateResult;
	Object.defineProperty(result, 'unevaluated', {
		enumerable: false,
		value: [...unevaluatedPolicies].map((policy) => ({
			policy,
			reason: 'requires-artifact',
		})),
	});
	return result;
}

export async function checkGeneratedFiles(
	options: { readonly cwd?: string; readonly directory?: string } = {},
): Promise<GateResult> {
	const cwd = resolve(options.cwd ?? PACKAGE_ROOT);
	const files = await discoverGeneratedFiles({ cwd, directory: options.directory });
	const entries = await Promise.all(
		files.map(async (file) => ({ file, source: await readFile(resolve(cwd, file), 'utf8') })),
	);
	return checkSources(entries);
}
