// @generated by @frameless/react; do not edit.
import { useState } from 'react';

export function AttrBoard({ seed, onTrace }) {
	const [locked, setLocked] = useState(false);
	const [steps, setSteps] = useState(0);
	const [rows, setRows] = useState(() => {
		return seed.map((row) => ({ ...row }));
	});
	const stage = locked ? 'locked' : 'open';
	const sealed =
		rows
			.filter((row) => row.off)
			.map((row) => row.id)
			.join('+') || 'none';
	return (
		<section data-scenario="s9">
			<button type="button" data-gate="true" disabled={locked} data-stage={stage}>
				gate
			</button>
			<input type="text" data-note="true" required={locked} />
			<p data-sealed="true">{sealed}</p>
			<p data-steps="true">{steps}</p>
			<ul data-fields="true">
				{rows.map((row) => (
					<li key={row.id} data-oracle-attr-key={row.id}>
						<button type="button" data-field={row.id} disabled={row.off}>
							field
						</button>
						<button
							type="button"
							data-seal={row.id}
							onClick={(event) => {
								const next = rows.map((entry) =>
									entry.id === row.id ? { id: entry.id, off: !entry.off } : entry,
								);
								const nextRows = next;
								setRows(nextRows);
								onTrace('seal', { id: row.id }, event);
							}}
						>
							seal
						</button>
					</li>
				))}
			</ul>
			<button
				type="button"
				data-action="lock"
				onClick={(event) => {
					const nextLocked = true;
					setLocked(nextLocked);
					const nextSteps = steps + 1;
					setSteps(nextSteps);
					onTrace('lock', { locked: true }, event);
				}}
			>
				lock
			</button>
			<button
				type="button"
				data-action="unlock"
				onClick={(event) => {
					const nextLocked = false;
					setLocked(nextLocked);
					const nextSteps = steps + 1;
					setSteps(nextSteps);
					onTrace('unlock', { locked: false }, event);
				}}
			>
				unlock
			</button>
		</section>
	);
}
