// @generated by @frameless/react; do not edit.
import { useState } from 'react';

export function BranchBoard({ seed, onTrace }) {
	const [phase, setPhase] = useState('live');
	const [entries, setEntries] = useState(() => {
		return seed.slice();
	});
	const [ticks, setTicks] = useState(0);
	const [seen, setSeen] = useState('none');
	const size = entries.length;
	return (
		<section data-scenario="s5">
			<p data-count="size">{size}</p>
			<button
				data-action="toggle"
				onClick={(event) => {
					const next = phase === 'live' ? 'idle' : 'live';
					const nextPhase = next;
					setPhase(nextPhase);
					onTrace('toggle', { phase: next }, event);
				}}
			>
				toggle
			</button>
			{phase === 'live' ? (
				<div data-arm="live">
					<output data-live-ticks="true">{ticks}</output>
					<p data-live-seen="true">{seen}</p>
					<button
						data-action="tick"
						onClick={(event) => {
							const nextTicks = ticks + 1;
							setTicks(nextTicks);
							onTrace('tick', { ticks: nextTicks }, event);
						}}
					>
						tick
					</button>
					<ul data-branch-rows="true">
						{entries.map((entry) => (
							<li key={entry.id} data-oracle-branch-key={entry.id}>
								<button
									data-pick={entry.id}
									onClick={(event) => {
										const nextSeen = entry.id;
										setSeen(nextSeen);
										onTrace('pick', { id: entry.id }, event);
									}}
								>
									pick
								</button>
							</li>
						))}
					</ul>
				</div>
			) : (
				<div data-arm="idle">
					<output data-idle-ticks="true">{ticks}</output>
					<p data-idle-seen="true">{seen}</p>
					<button
						data-action="drop"
						onClick={(event) => {
							const remaining = entries.slice(1);
							const nextEntries = remaining;
							setEntries(nextEntries);
							onTrace('drop', { size: remaining.length }, event);
						}}
					>
						drop
					</button>
				</div>
			)}
		</section>
	);
}
