// @generated by @frameless/react; do not edit.
import { useRef, useState } from 'react';

export function CodexClone({
	onTrace,
}: {
	onTrace: (name: string, detail: Record<string, unknown>, event: unknown) => void;
}) {
	const [threads, setThreads] = useState(() => {
		return [
			{ id: 'c1', title: 'Emit six lanes from one source', stamp: '2m ago' },
			{ id: 'c2', title: 'Measure the async door', stamp: '1h ago' },
			{ id: 'c3', title: 'Style the composer shell', stamp: 'Yesterday' },
		];
	});
	const [messages, setMessages] = useState(() => {
		return [
			{
				id: 'm1',
				thread: 'c1',
				role: 'user',
				text: 'What does the corpus prove?',
				stamp: '09:41',
				live: false,
			},
			{
				id: 'm2',
				thread: 'c1',
				role: 'assistant',
				text: 'One authored source, emitted six ways, compared byte for byte.',
				stamp: '09:41',
				live: false,
			},
		];
	});
	const [openThread, setOpenThread] = useState('c1');
	const [openTitle, setOpenTitle] = useState('Emit six lanes from one source');
	const [draft, setDraft] = useState('');
	const nextMessage = useRef(3);
	const nextThread = useRef(4);
	const [status, setStatus] = useState('idle');
	const [rightTab, setRightTab] = useState('details');
	const [bottomTab, setBottomTab] = useState('terminal');
	const visible = messages.filter((message) => message.thread === openThread).length;
	const visibleLabel =
		messages.filter((message) => message.thread === openThread).length === 1
			? ' message in this thread'
			: ' messages in this thread';
	const turns = messages.filter(
		(message) => message.thread === openThread && message.role === 'user',
	).length;
	const turnsLabel =
		messages.filter((message) => message.thread === openThread && message.role === 'user')
			.length === 1
			? ' turn on the record'
			: ' turns on the record';
	const streaming = status === 'streaming';
	const blocked = status === 'streaming' || draft.trim() === '';
	return (
		<section className="codex" data-app="codex-clone">
			<aside className="rail" data-rail="sidebar">
				<div className="brand" data-rail="brand">
					<span className="brand-mark">F</span>
					<span className="brand-name">Frameless Codex</span>
				</div>
				<button
					type="button"
					className="new-chat"
					data-action="new-chat"
					onClick={(event) => {
						const currentState5 = nextThread.current;
						const id = `c${currentState5}`;
						const nextThreads = threads.concat({
							id,
							title: 'New conversation',
							stamp: 'now',
						});
						setThreads(nextThreads);
						nextThread.current = currentState5 + 1;
						const nextOpenThread = id;
						setOpenThread(nextOpenThread);
						const nextOpenTitle = 'New conversation';
						setOpenTitle(nextOpenTitle);
						onTrace('new-chat', { id }, event);
					}}
				>
					New chat
				</button>
				<p className="rail-label" data-rail="label">
					Chats
				</p>
				<ul className="rail-list" data-rail="list">
					{threads.map((thread) => (
						<li key={thread.id} className="rail-row">
							<button
								type="button"
								className={
									openThread === thread.id ? 'rail-item selected' : 'rail-item'
								}
								data-thread={thread.id}
								onClick={(event) => {
									const nextOpenThread = thread.id;
									setOpenThread(nextOpenThread);
									const nextOpenTitle = thread.title;
									setOpenTitle(nextOpenTitle);
									onTrace('open', { id: thread.id }, event);
								}}
							>
								{thread.title}
							</button>
						</li>
					))}
				</ul>
			</aside>
			<main className="thread" data-thread="main">
				<header className="thread-head">
					<h2 className="thread-title" data-thread="title">
						{openTitle}
					</h2>
					<p className="thread-meta" data-thread="meta">
						<strong>{visible}</strong>
						{visibleLabel}
					</p>
				</header>
				{visible === 0 ? (
					<div className="empty" data-thread="empty">
						<h3 className="empty-heading">Where should we begin?</h3>
						<p className="empty-note">
							Ask anything. The answer arrives in three chunks.
						</p>
					</div>
				) : null}
				<ol className="messages" data-thread="list">
					{messages.map((message) => (
						<li
							key={message.id}
							className={
								message.role === 'user'
									? 'message message-user'
									: 'message message-assistant'
							}
							data-message={message.id}
							hidden={message.thread !== openThread}
						>
							<p className="message-role" data-role={message.id}>
								{message.role}
							</p>
							<p className="message-text" data-text={message.id}>
								{message.text}
							</p>
							<p className="message-stamp" data-stamp={message.id}>
								{message.stamp}
							</p>
							<span
								className="message-caret"
								data-caret={message.id}
								hidden={!message.live}
							>
								typing
							</span>
						</li>
					))}
				</ol>
				<form
					className="composer"
					data-action="send"
					onClick={(event) => {
						onTrace('press', { area: 'composer' }, event);
					}}
					onSubmit={async (event) => {
						const currentState4 = nextMessage.current;
						event.preventDefault();
						const text = draft.trim();
						const home = openThread;
						const askId = `m${currentState4}`;
						const replyId = `m${currentState4 + 1}`;
						const asked = messages.concat({
							id: askId,
							thread: home,
							role: 'user',
							text,
							stamp: '09:42',
							live: false,
						});
						const opened = asked.concat({
							id: replyId,
							thread: home,
							role: 'assistant',
							text: '',
							stamp: '09:42',
							live: true,
						});
						const nextMessages = text === '' ? messages : opened;
						setMessages(nextMessages);
						nextMessage.current = text === '' ? currentState4 : currentState4 + 2;
						const nextDraft = '';
						setDraft(nextDraft);
						const nextStatus = text === '' ? status : 'streaming';
						setStatus(nextStatus);
						await new Promise((settle) => {
							setTimeout(() => settle(true), 400);
						});
						const chunk1 = opened.map((entry) =>
							entry.id === replyId
								? {
										id: entry.id,
										thread: entry.thread,
										role: entry.role,
										text: 'Reading the twelve-scenario corpus',
										stamp: entry.stamp,
										live: true,
									}
								: entry,
						);
						const nextMessages2 = text === '' ? nextMessages : chunk1;
						setMessages(nextMessages2);
						await new Promise((settle) => {
							setTimeout(() => settle(true), 400);
						});
						const chunk2 = chunk1.map((entry) =>
							entry.id === replyId
								? {
										id: entry.id,
										thread: entry.thread,
										role: entry.role,
										text: 'Reading the twelve-scenario corpus, then emitting all six lanes',
										stamp: entry.stamp,
										live: true,
									}
								: entry,
						);
						const nextMessages3 = text === '' ? nextMessages2 : chunk2;
						setMessages(nextMessages3);
						await new Promise((settle) => {
							setTimeout(() => settle(true), 400);
						});
						const chunk3 = chunk2.map((entry) =>
							entry.id === replyId
								? {
										id: entry.id,
										thread: entry.thread,
										role: entry.role,
										text: 'Reading the twelve-scenario corpus, then emitting all six lanes from one authored source.',
										stamp: entry.stamp,
										live: false,
									}
								: entry,
						);
						const nextMessages4 = text === '' ? nextMessages3 : chunk3;
						setMessages(nextMessages4);
						const nextStatus2 = 'idle';
						setStatus(nextStatus2);
						onTrace('send', { id: replyId, text, thread: home }, event);
					}}
				>
					<textarea
						className="composer-input"
						placeholder="Ask anything"
						data-action="draft"
						value={draft}
						onChange={(event) => {
							const nextDraft = event.target.value;
							setDraft(nextDraft);
						}}
					/>
					<div className="composer-actions">
						<p className="composer-status" data-stream="status">
							{status}
						</p>
						<button
							type="submit"
							className="send"
							data-action="send-go"
							disabled={blocked}
						>
							Send
						</button>
					</div>
				</form>
			</main>
			<aside className="pane pane-right" data-pane="right">
				<div className="tabs" data-tabs="right">
					<button
						type="button"
						data-tab="right-details"
						className={rightTab === 'details' ? 'tab selected' : 'tab'}
						onClick={(event) => {
							const nextRightTab = 'details';
							setRightTab(nextRightTab);
							onTrace('right-tab', { tab: 'details' }, event);
						}}
					>
						Details
					</button>
					<button
						type="button"
						data-tab="right-files"
						className={rightTab === 'files' ? 'tab selected' : 'tab'}
						onClick={(event) => {
							const nextRightTab = 'files';
							setRightTab(nextRightTab);
							onTrace('right-tab', { tab: 'files' }, event);
						}}
					>
						Files
					</button>
				</div>
				<div
					className="pane-body"
					data-panel="right-details"
					hidden={rightTab !== 'details'}
				>
					<p className="pane-row" data-detail="turns">
						<strong>{turns}</strong>
						{turnsLabel}
					</p>
					<p className="pane-row" data-detail="title">
						{openTitle}
					</p>
					<p className="pane-row" data-detail="model">
						gpt-frameless-12
					</p>
				</div>
				<div className="pane-body" data-panel="right-files" hidden={rightTab !== 'files'}>
					<p className="pane-row" data-file="fixture">
						s12-codex-clone.tsrx
					</p>
					<p className="pane-row" data-file="theme">
						shadcn-theme/default.css
					</p>
					<p className="pane-row" data-file="note">
						T006-codex-clone.md
					</p>
				</div>
			</aside>
			<section className="pane pane-bottom" data-pane="bottom">
				<div className="tabs" data-tabs="bottom">
					<button
						type="button"
						data-tab="bottom-terminal"
						className={bottomTab === 'terminal' ? 'tab selected' : 'tab'}
						onClick={(event) => {
							const nextBottomTab = 'terminal';
							setBottomTab(nextBottomTab);
							onTrace('bottom-tab', { tab: 'terminal' }, event);
						}}
					>
						Terminal
					</button>
					<button
						type="button"
						data-tab="bottom-diff"
						className={bottomTab === 'diff' ? 'tab selected' : 'tab'}
						onClick={(event) => {
							const nextBottomTab = 'diff';
							setBottomTab(nextBottomTab);
							onTrace('bottom-tab', { tab: 'diff' }, event);
						}}
					>
						Diff
					</button>
				</div>
				<div
					className="pane-body"
					data-panel="bottom-terminal"
					hidden={bottomTab !== 'terminal'}
				>
					<p className="term-row" data-term="cmd">
						pnpm regenerate --lane all
					</p>
					<p className="term-row" data-term="state">
						{status}
					</p>
					<p className="term-row" data-term="live" hidden={!streaming}>
						chunk in flight
					</p>
				</div>
				<div className="pane-body" data-panel="bottom-diff" hidden={bottomTab !== 'diff'}>
					<p className="diff-row diff-add" data-diff="add">
						+ three unrolled chunks
					</p>
					<p className="diff-row diff-del" data-diff="del">
						- one variable-length loop
					</p>
				</div>
			</section>
		</section>
	);
}
