// @generated by @frameless/react; do not edit.
import { useState } from 'react';

export function FormBoard({ seed, onTrace }) {
	const [size, setSize] = useState('s');
	const [notes, setNotes] = useState('draft');
	const [pick, setPick] = useState('r1');
	const [lock, setLock] = useState(null);
	const [rows, setRows] = useState(() => {
		return seed.map((row) => ({ ...row }));
	});
	const chosen =
		rows
			.filter((row) => row.on)
			.map((row) => row.id)
			.join('+') || 'none';
	const onFirst = pick === 'r1';
	const onSecond = pick === 'r2';
	const locked = lock !== null;
	const guard = lock === null ? null : 'held';
	return (
		<form data-scenario="s7">
			<select
				data-control="size"
				data-size={size}
				onChange={(event) => {
					const next = event.target.value;
					const nextSize = next;
					setSize(nextSize);
					onTrace('size', { size: next }, event);
				}}
			>
				<option value="s">small</option>
				<option value="m">medium</option>
				<option value="l">large</option>
			</select>
			<textarea
				data-control="notes"
				data-notes={notes}
				onChange={(event) => {
					const next = event.target.value;
					const nextNotes = next;
					setNotes(nextNotes);
					onTrace('notes', { notes: next }, event);
				}}
			/>
			<input
				type="radio"
				name="s7pick"
				data-pick="r1"
				checked={onFirst}
				onChange={(event) => {
					const nextPick = 'r1';
					setPick(nextPick);
					onTrace('pick', { pick: 'r1' }, event);
				}}
			/>
			<input
				type="radio"
				name="s7pick"
				data-pick="r2"
				checked={onSecond}
				onChange={(event) => {
					const nextPick = 'r2';
					setPick(nextPick);
					onTrace('pick', { pick: 'r2' }, event);
				}}
			/>
			<p data-picked="true">{pick}</p>
			<p data-chosen="true">{chosen}</p>
			<ul data-tags="true">
				{rows.map((row) => (
					<li key={row.id} data-oracle-form-key={row.id}>
						<input
							type="checkbox"
							data-tag={row.id}
							checked={row.on}
							onChange={(event) => {
								const next = rows.map((entry) =>
									entry.id === row.id ? { id: entry.id, on: !entry.on } : entry,
								);
								const nextRows = next;
								setRows(nextRows);
								onTrace('tag', { id: row.id }, event);
							}}
						/>
					</li>
				))}
			</ul>
			<button
				type="button"
				data-action="resize"
				onClick={(event) => {
					const nextSize = 'l';
					setSize(nextSize);
					const nextNotes = 'final';
					setNotes(nextNotes);
					onTrace('resize', { size: 'l', notes: 'final' }, event);
				}}
			>
				resize
			</button>
			<button
				type="button"
				data-action="lock"
				data-lock={lock}
				onClick={(event) => {
					const next = lock === null ? 'on' : null;
					const nextLock = next;
					setLock(nextLock);
					onTrace('lock', { lock: next }, event);
				}}
			>
				lock
			</button>
			<button type="button" data-guard="true" aria-disabled={locked} data-held={guard}>
				guard
			</button>
		</form>
	);
}
