// @generated by @frameless/react; do not edit.
import { useState } from 'react';

export function HnItem({ parent, depth }: { parent: string; depth: number }) {
	const [comments, setComments] = useState(() => {
		return [
			{
				id: 'c1',
				parentId: 'root',
				author: 'tptacek',
				age: '3 hours ago',
				text: 'The measurement is the interesting part, not the clone.',
				kidsLabel: '3 replies',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c2',
				parentId: 'c1',
				author: 'pg',
				age: '2 hours ago',
				text: 'Agreed - a refusal you can quote is worth more than a guess.',
				kidsLabel: '2 replies',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c3',
				parentId: 'c2',
				author: 'dang',
				age: '2 hours ago',
				text: 'It also has to be read off the real module, not off a probe.',
				kidsLabel: '1 reply',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c4',
				parentId: 'c3',
				author: 'jl',
				age: '1 hour ago',
				text: 'That rule was bought with a defect, which is why it is written down.',
				kidsLabel: 'no replies',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c5',
				parentId: 'c1',
				author: 'patio11',
				age: '2 hours ago',
				text: 'Nesting depth is the only thing on this page that cannot be faked.',
				kidsLabel: 'no replies',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c6',
				parentId: 'root',
				author: 'sama',
				age: '4 hours ago',
				text: 'Does the thread actually recurse, or is it unrolled to a fixed depth?',
				kidsLabel: '4 replies',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c7',
				parentId: 'c6',
				author: 'evanyou',
				age: '4 hours ago',
				text: 'It recurses - the component names itself in its own template.',
				kidsLabel: '3 replies',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c8',
				parentId: 'c7',
				author: 'ryansolid',
				age: '3 hours ago',
				text: 'Two lanes refuse that spelling outright, and the message says why.',
				kidsLabel: '2 replies',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c9',
				parentId: 'c8',
				author: 'mhevery',
				age: '3 hours ago',
				text: 'One file, one component - so the self-reference has nowhere to land.',
				kidsLabel: '1 reply',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c10',
				parentId: 'c9',
				author: 'minimaxir',
				age: '2 hours ago',
				text: 'Five levels deep, and the indentation is real DOM nesting.',
				kidsLabel: 'no replies',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c11',
				parentId: 'root',
				author: 'whoishiring',
				age: '5 hours ago',
				text: 'Collapse the subtree and the recursive instance goes with it.',
				kidsLabel: '1 reply',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c12',
				parentId: 'c11',
				author: 'frameless',
				age: '5 hours ago',
				text: 'Every level seeds the same data and filters it by parent.',
				kidsLabel: 'no replies',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c13',
				parentId: 'root',
				author: 'dang',
				age: '6 hours ago',
				text: 'Please keep the discussion on the axis being measured.',
				kidsLabel: '1 reply',
				collapsed: false,
				voted: false,
			},
			{
				id: 'c14',
				parentId: 'c13',
				author: 'jacquesm',
				age: '6 hours ago',
				text: 'The axis is recursion, and it has a verdict per lane now.',
				kidsLabel: 'no replies',
				collapsed: false,
				voted: false,
			},
		];
	});
	return (
		<div className="hn-thread" data-thread={parent} data-depth={depth}>
			{depth === 0 ? (
				<div className="hn-itemhead" data-hn="itemhead">
					<header className="hn-head" data-hn="masthead">
						<a className="hn-logo" href="#/" data-hn="logo">
							<span className="hn-y">Y</span>
						</a>
						<a className="hn-brand" href="#/" data-hn="brand">
							Hacker News
						</a>
						<a className="hn-login" href="#/login" data-hn="login">
							login
						</a>
					</header>
					<div className="hn-story" data-story="h1">
						<span className="hn-titleline">
							<button
								type="button"
								className="hn-vote"
								aria-label="upvote"
								data-vote="h1"
							/>
							<a
								className="hn-storylink"
								href="https://github.com/markless-dev/frameless"
								data-title="h1"
							>
								Emit six framework lanes from one authored source
							</a>
							<span className="hn-domain" data-domain="h1">
								(github.com)
							</span>
						</span>
						<span className="hn-subtext" data-subtext="h1">
							<span className="hn-score" data-points="h1">
								412
							</span>
							<span className="hn-scorelabel">points</span>
							<span className="hn-meta">by pg 3 hours ago</span>
							<span className="hn-bar">|</span>
							<a className="hn-act" href="#/hide" data-act="hide">
								hide
							</a>
							<span className="hn-bar">|</span>
							<a className="hn-act" href="#/past" data-act="past">
								past
							</a>
							<span className="hn-bar">|</span>
							<a className="hn-act" href="#/favorite" data-act="favorite">
								favorite
							</a>
							<span className="hn-bar">|</span>
							<span className="hn-act" data-act="count">
								128 comments
							</span>
						</span>
					</div>
				</div>
			) : null}
			<ul className="hn-comments" data-comments={parent}>
				{comments.map((comment) => (
					<li
						key={comment.id}
						className="hn-comment"
						data-comment={comment.id}
						hidden={comment.parentId !== parent}
					>
						{comment.parentId === parent ? (
							<div className="hn-c" data-c={comment.id}>
								<div className="hn-chead">
									<button
										type="button"
										className="hn-vote"
										aria-label="upvote"
										data-cvote={comment.id}
										hidden={comment.voted}
										onClick={() => {
											const nextComments = comments.map((entry) =>
												entry.id === comment.id
													? {
															id: entry.id,
															parentId: entry.parentId,
															author: entry.author,
															age: entry.age,
															text: entry.text,
															kidsLabel: entry.kidsLabel,
															collapsed: entry.collapsed,
															voted: true,
														}
													: entry,
											);
											setComments(nextComments);
										}}
									/>
									<span className="hn-cby" data-cby={comment.id}>
										{comment.author}
									</span>
									<span className="hn-cage">{comment.age}</span>
									<button
										type="button"
										className="hn-ctoggle"
										data-collapse={comment.id}
										hidden={comment.collapsed}
										onClick={() => {
											const nextComments = comments.map((entry) =>
												entry.id === comment.id
													? {
															id: entry.id,
															parentId: entry.parentId,
															author: entry.author,
															age: entry.age,
															text: entry.text,
															kidsLabel: entry.kidsLabel,
															collapsed: true,
															voted: entry.voted,
														}
													: entry,
											);
											setComments(nextComments);
										}}
									>
										[-]
									</button>
									<button
										type="button"
										className="hn-ctoggle"
										data-expand={comment.id}
										hidden={!comment.collapsed}
										onClick={() => {
											const nextComments = comments.map((entry) =>
												entry.id === comment.id
													? {
															id: entry.id,
															parentId: entry.parentId,
															author: entry.author,
															age: entry.age,
															text: entry.text,
															kidsLabel: entry.kidsLabel,
															collapsed: false,
															voted: entry.voted,
														}
													: entry,
											);
											setComments(nextComments);
										}}
									>
										[+]
									</button>
									<span
										className="hn-ckids"
										data-ckids={comment.id}
										hidden={!comment.collapsed}
									>
										{comment.kidsLabel}
									</span>
								</div>
								<div
									className="hn-ctext"
									data-ctext={comment.id}
									hidden={comment.collapsed}
								>
									<span className="hn-cbody">{comment.text}</span>
								</div>
								<div className="hn-creply" hidden={comment.collapsed}>
									<a className="hn-act" href="#/reply" data-reply={comment.id}>
										reply
									</a>
								</div>
								<div
									className="hn-cnest"
									data-cnest={comment.id}
									hidden={comment.collapsed}
								>
									<HnItem parent={comment.id} depth={depth + 1} />
								</div>
							</div>
						) : null}
					</li>
				))}
			</ul>
		</div>
	);
}
