// @generated by @frameless/react; do not edit.
import { useState } from 'react';

export function TaskBoard({
	onTrace,
}: {
	onTrace: (name: string, detail: Record<string, unknown>, event: unknown) => void;
}) {
	const [columns, setColumns] = useState(() => {
		return [
			{
				id: 'backlog',
				title: 'Backlog',
				mark: '◌',
				prevId: '',
				nextId: 'todo',
				tasks: [
					{
						id: 't1',
						title: 'Mobile app redesign',
						blurb: 'Complete redesign of mobile application for better UX',
						date: 'Feb 10',
						comments: '2',
						links: '3',
						tags: [{ id: 't1g1', name: 'Design' }],
					},
					{
						id: 't2',
						title: 'API documentation update',
						blurb: 'Update API docs with latest endpoints and examples',
						date: 'Feb 15',
						comments: '',
						links: '8',
						tags: [{ id: 't2g1', name: 'Product' }],
					},
					{
						id: 't3',
						title: 'Accessibility improvements',
						blurb: 'Enhance accessibility for screen readers and keyboard navigation',
						date: 'Feb 20',
						comments: '1',
						links: '5',
						tags: [
							{ id: 't3g1', name: 'Design' },
							{ id: 't3g2', name: 'New releases' },
						],
					},
				],
			},
			{
				id: 'todo',
				title: 'Todo',
				mark: '○',
				prevId: 'backlog',
				nextId: 'progress',
				tasks: [
					{
						id: 't4',
						title: 'Design system update',
						blurb: 'Enhance design system for consistency and usability',
						date: 'Jan 25',
						comments: '4',
						links: '',
						tags: [
							{ id: 't4g1', name: 'Design' },
							{ id: 't4g2', name: 'New releases' },
						],
					},
					{
						id: 't5',
						title: 'Retention rate by 23%',
						blurb: 'Improve retention through campaigns and feature updates',
						date: 'Jan 25',
						comments: '4',
						links: '12',
						tags: [
							{ id: 't5g1', name: 'Marketing' },
							{ id: 't5g2', name: 'Product' },
						],
					},
					{
						id: 't6',
						title: 'Icon system',
						blurb: 'Develop scalable icons for cohesive platform visuals',
						date: 'Jan 25',
						comments: '4',
						links: '',
						tags: [{ id: 't6g1', name: 'Design' }],
					},
				],
			},
			{
				id: 'progress',
				title: 'In Progress',
				mark: '◑',
				prevId: 'todo',
				nextId: 'review',
				tasks: [
					{
						id: 't7',
						title: 'Search features',
						blurb: 'Upgrade search for faster, accurate user results',
						date: 'Jan 25',
						comments: '',
						links: '12',
						tags: [{ id: 't7g1', name: 'Product' }],
					},
					{
						id: 't8',
						title: 'Checkout flow design',
						blurb: 'Optimize checkout process to improve conversion rates',
						date: 'Jan 25',
						comments: '',
						links: '12',
						tags: [{ id: 't8g1', name: 'Design' }],
					},
				],
			},
			{
				id: 'review',
				title: 'Technical Review',
				mark: '◍',
				prevId: 'progress',
				nextId: '',
				tasks: [
					{
						id: 't9',
						title: 'Payment gateway integration',
						blurb: 'Integrate Stripe payment system for subscriptions',
						date: 'Jan 28',
						comments: '2',
						links: '5',
						tags: [{ id: 't9g1', name: 'Product' }],
					},
				],
			},
		];
	});
	const [dragId, setDragId] = useState('');
	const shipped = columns
		.filter((column) => column.nextId === '')
		.reduce((sum, column) => sum + column.tasks.length, 0);
	const totalLabel = `/${columns.reduce((sum, column) => sum + column.tasks.length, 0)}`;
	const tally = `${columns.filter((column) => column.nextId === '').reduce((sum, column) => sum + column.tasks.length, 0)}/${columns.reduce((sum, column) => sum + column.tasks.length, 0)}`;
	const summary =
		columns
			.filter((column) => column.nextId === '')
			.reduce((sum, column) => sum + column.tasks.length, 0) === 0
			? 'Nothing has reached review yet.'
			: columns
						.filter((column) => column.nextId === '')
						.reduce((sum, column) => sum + column.tasks.length, 0) < 2
				? 'Review is filling up.'
				: columns
							.filter((column) => column.nextId === '')
							.reduce((sum, column) => sum + column.tasks.length, 0) < 4
					? 'Half the board is in review.'
					: columns
								.filter((column) => column.nextId === '')
								.reduce((sum, column) => sum + column.tasks.length, 0) < 9
						? 'Almost everything is in review.'
						: 'Every task is in review.';
	const summaryEmoji =
		columns
			.filter((column) => column.nextId === '')
			.reduce((sum, column) => sum + column.tasks.length, 0) === 0
			? '◔'
			: columns
						.filter((column) => column.nextId === '')
						.reduce((sum, column) => sum + column.tasks.length, 0) < 2
				? '◑'
				: columns
							.filter((column) => column.nextId === '')
							.reduce((sum, column) => sum + column.tasks.length, 0) < 4
					? '◕'
					: columns
								.filter((column) => column.nextId === '')
								.reduce((sum, column) => sum + column.tasks.length, 0) < 9
						? '●'
						: '✦';
	return (
		<section className="tb" data-app="task-board">
			<div className="tb-shell">
				<aside className="tb-side" data-tb="sidebar">
					<div className="tb-brand" data-tb="brand">
						<span className="tb-mark">◧</span>
						<span className="tb-brandname">Frameless</span>
					</div>
					<nav className="tb-nav" data-tb="nav">
						<a
							className="tb-navlink"
							href="#/dashboard"
							data-nav="dashboard"
							onClick={(event) => {
								event.preventDefault();
								onTrace('nav', { to: 'dashboard' }, event);
							}}
						>
							<span className="tb-navicon">▤</span>
							<span className="tb-navtext">Dashboard</span>
						</a>
						<a
							className="tb-navlink tb-navlink-on"
							href="#/task"
							data-nav="task"
							onClick={(event) => {
								event.preventDefault();
								onTrace('nav', { to: 'task' }, event);
							}}
						>
							<span className="tb-navicon">☆</span>
							<span className="tb-navtext">Task</span>
							<span className="tb-badge" data-badge="task">
								{tally}
							</span>
						</a>
						<a
							className="tb-navlink"
							href="#/projects"
							data-nav="projects"
							onClick={(event) => {
								event.preventDefault();
								onTrace('nav', { to: 'projects' }, event);
							}}
						>
							<span className="tb-navicon">▣</span>
							<span className="tb-navtext">Projects</span>
						</a>
					</nav>
					<div className="tb-promo" data-tb="promo">
						<span className="tb-promotitle">One source, six lanes</span>
						<span className="tb-promotext">
							Every pixel on this page is emitted from a single .tsrx module into
							react, solid, qwik, svelte, vue and angular.
						</span>
					</div>
				</aside>
				<div className="tb-content">
					<header className="tb-top" data-tb="topbar">
						<button
							type="button"
							className="tb-icon"
							aria-label="toggle sidebar"
							data-action="toggle-sidebar"
							onClick={(event) => {
								onTrace('press', { area: 'toggle-sidebar' }, event);
							}}
						>
							<span className="tb-iconglyph">▥</span>
						</button>
						<h1 className="tb-crumb" data-tb="crumb">
							Task
						</h1>
						<span className="tb-topgap" />
						<span className="tb-stamp" data-tb="stamp">
							Last update 3 days ago
						</span>
						<button
							type="button"
							className="tb-pill"
							data-action="share"
							onClick={(event) => {
								onTrace('press', { area: 'share' }, event);
							}}
						>
							<span className="tb-pillglyph">↗</span>
							<span className="tb-pilltext">Share</span>
						</button>
					</header>
					<div className="tb-tools" data-tb="tools">
						<button
							type="button"
							className="tb-tool"
							data-action="filter"
							onClick={(event) => {
								onTrace('press', { area: 'filter' }, event);
							}}
						>
							<span className="tb-toolglyph">⚟</span>
							<span className="tb-tooltext">Filter</span>
						</button>
						<button
							type="button"
							className="tb-tool"
							data-action="sort"
							onClick={(event) => {
								onTrace('press', { area: 'sort' }, event);
							}}
						>
							<span className="tb-toolglyph">⇅</span>
							<span className="tb-tooltext">Sort</span>
						</button>
						<span className="tb-toolgap" />
						<span className="tb-date" data-tb="date">
							Sep 6, 2024
						</span>
						<button
							type="button"
							className="tb-tool tb-tool-solid"
							data-action="request-task"
							onClick={(event) => {
								onTrace('press', { area: 'request-task' }, event);
							}}
						>
							<span className="tb-toolglyph">+</span>
							<span className="tb-tooltext">Request task</span>
						</button>
					</div>
					<div className="tb-headline" data-tb="headline">
						<p className="tb-tally">
							<span className="tb-tallydone" data-tally="done">
								{shipped}
							</span>
							<span className="tb-tallytotal" data-tally="total">
								{totalLabel}
							</span>
						</p>
						<p className="tb-summaryline">
							<span className="tb-summaryemoji" data-summary="emoji">
								{summaryEmoji}
							</span>
							<span className="tb-summarytext" data-summary="text">
								{summary}
							</span>
						</p>
					</div>
					<p className="tb-note" data-tb="dragnote">
						<span className="tb-notemark">!</span>
						<span className="tb-notetext">
							DRAG A CARD ONTO ANOTHER COLUMN — it works in solid, qwik, svelte, vue
							and angular, and IT DOES NOT WORK IN REACT, which is the measurement
							rather than a shortfall. All six emitters produce the handlers from one
							.tsrx source; react-dom alone binds by a prop name of its own, so the
							flattened onDragover this compiler emits never fires there and the drop
							is never allowed. THE ◀ AND ▶ ARROWS MOVE A CARD IN ALL SIX LANES and
							are how react moves one. The reference this page was measured against
							has no working drag at all. See the fixture header.
						</span>
					</p>
					<main className="tb-board" data-tb="board">
						{columns.map((column) => (
							<div key={column.id} className="tb-col" data-col={column.id}>
								<div className="tb-colhead" data-colhead={column.id}>
									<span className="tb-colmark">{column.mark}</span>
									<span className="tb-coltitle" data-coltitle={column.id}>
										{column.title}
									</span>
									<span className="tb-colcount" data-colcount={column.id}>
										{column.tasks.length}
									</span>
									<span className="tb-colgap" />
									<button
										type="button"
										className="tb-colicon"
										aria-label="add task to column"
										data-coladd={column.id}
										onClick={(event) => {
											onTrace('press', { area: 'col-add' }, event);
										}}
									>
										<span className="tb-iconglyph">+</span>
									</button>
								</div>
								<ul
									className="tb-cards"
									data-cards={column.id}
									onDragover={(event) => {
										event.preventDefault();
									}}
									onDrop={(event) => {
										event.preventDefault();
										const nextColumns = columns.map((entry) =>
											entry.id === column.id
												? {
														id: entry.id,
														title: entry.title,
														mark: entry.mark,
														prevId: entry.prevId,
														nextId: entry.nextId,
														tasks: entry.tasks
															.filter((row) => row.id !== dragId)
															.concat(
																columns.flatMap((source) =>
																	source.tasks.filter(
																		(row) => row.id === dragId,
																	),
																),
															),
													}
												: entry.tasks.filter((row) => row.id === dragId)
															.length === 0
													? entry
													: {
															id: entry.id,
															title: entry.title,
															mark: entry.mark,
															prevId: entry.prevId,
															nextId: entry.nextId,
															tasks: entry.tasks.filter(
																(row) => row.id !== dragId,
															),
														},
										);
										setColumns(nextColumns);
										const nextDragId = '';
										setDragId(nextDragId);
										onTrace('drop', { to: column.id }, event);
									}}
								>
									{column.tasks.map((task) => (
										<li
											key={task.id}
											className="tb-card"
											data-card={task.id}
											data-dragging={task.id === dragId ? 'yes' : 'no'}
											draggable={task.id !== ''}
											onDragstart={(event) => {
												const nextDragId = task.id;
												setDragId(nextDragId);
												onTrace(
													'dragstart',
													{ id: task.id, from: column.id },
													event,
												);
											}}
											onDragend={(event) => {
												const nextDragId = '';
												setDragId(nextDragId);
												onTrace('dragend', { id: task.id }, event);
											}}
										>
											<div className="tb-cardtop">
												<span className="tb-cardmark">{column.mark}</span>
												<span
													className="tb-cardtitle"
													data-cardtitle={task.id}
												>
													{task.title}
												</span>
											</div>
											<p className="tb-cardblurb" data-cardblurb={task.id}>
												{task.blurb}
											</p>
											<div className="tb-tags" data-tags={task.id}>
												{task.tags.map((tag) => (
													<span
														key={tag.id}
														className="tb-tag"
														data-tag={tag.id}
													>
														{tag.name}
													</span>
												))}
											</div>
											<div className="tb-cardfoot" data-cardfoot={task.id}>
												<span className="tb-meta">
													<span className="tb-metaglyph">▤</span>
													<span className="tb-metatext">{task.date}</span>
												</span>
												<span
													className="tb-meta"
													hidden={task.comments === ''}
												>
													<span className="tb-metaglyph">▭</span>
													<span className="tb-metatext">
														{task.comments}
													</span>
												</span>
												<span
													className="tb-meta"
													hidden={task.links === ''}
												>
													<span className="tb-metaglyph">⛓</span>
													<span className="tb-metatext">
														{task.links}
													</span>
												</span>
												<span className="tb-metagap" />
												<button
													type="button"
													className="tb-move"
													aria-label="move task to the previous column"
													data-left={task.id}
													hidden={column.prevId === ''}
													onClick={(event) => {
														const nextColumns = columns.map((entry) =>
															entry.id === column.id
																? {
																		id: entry.id,
																		title: entry.title,
																		mark: entry.mark,
																		prevId: entry.prevId,
																		nextId: entry.nextId,
																		tasks: entry.tasks.filter(
																			(row) =>
																				row.id !== task.id,
																		),
																	}
																: entry.id === column.prevId
																	? {
																			id: entry.id,
																			title: entry.title,
																			mark: entry.mark,
																			prevId: entry.prevId,
																			nextId: entry.nextId,
																			tasks: entry.tasks.concat(
																				[task],
																			),
																		}
																	: entry,
														);
														setColumns(nextColumns);
														onTrace(
															'move',
															{ id: task.id, to: column.prevId },
															event,
														);
													}}
												>
													<span className="tb-moveglyph">◀</span>
												</button>
												<button
													type="button"
													className="tb-move"
													aria-label="move task to the next column"
													data-right={task.id}
													hidden={column.nextId === ''}
													onClick={(event) => {
														const nextColumns = columns.map((entry) =>
															entry.id === column.id
																? {
																		id: entry.id,
																		title: entry.title,
																		mark: entry.mark,
																		prevId: entry.prevId,
																		nextId: entry.nextId,
																		tasks: entry.tasks.filter(
																			(row) =>
																				row.id !== task.id,
																		),
																	}
																: entry.id === column.nextId
																	? {
																			id: entry.id,
																			title: entry.title,
																			mark: entry.mark,
																			prevId: entry.prevId,
																			nextId: entry.nextId,
																			tasks: entry.tasks.concat(
																				[task],
																			),
																		}
																	: entry,
														);
														setColumns(nextColumns);
														onTrace(
															'move',
															{ id: task.id, to: column.nextId },
															event,
														);
													}}
												>
													<span className="tb-moveglyph">▶</span>
												</button>
											</div>
										</li>
									))}
								</ul>
								<p
									className="tb-empty"
									data-empty={column.id}
									hidden={column.tasks.length !== 0}
								>
									<span className="tb-emptytext">No tasks here.</span>
								</p>
								<button
									type="button"
									className="tb-add"
									data-add={column.id}
									onClick={(event) => {
										onTrace('press', { area: 'add-task' }, event);
									}}
								>
									<span className="tb-addglyph">+</span>
									<span className="tb-addtext">Add task</span>
								</button>
							</div>
						))}
					</main>
				</div>
			</div>
		</section>
	);
}
