// @generated by @frameless/react; do not edit.
import { useRef, useState } from 'react';

export function TodoMvc({
	onTrace,
}: {
	onTrace: (name: string, detail: Record<string, unknown>, event: unknown) => void;
}) {
	const [todos, setTodos] = useState(() => {
		return [
			{ id: 't1', title: 'Taste JavaScript', done: true },
			{ id: 't2', title: 'Buy a unicorn', done: false },
		];
	});
	const [draft, setDraft] = useState('');
	const next = useRef(3);
	const [filter, setFilter] = useState('all');
	const [editing, setEditing] = useState('');
	const [editDraft, setEditDraft] = useState('');
	const active = todos.filter((todo) => !todo.done).length;
	const completed = todos.filter((todo) => todo.done).length;
	const allDone = todos.length > 0 && todos.filter((todo) => !todo.done).length === 0;
	const remainingLabel =
		todos.filter((todo) => !todo.done).length === 1 ? ' item left' : ' items left';
	return (
		<section className="todoapp" data-app="todomvc">
			<header className="header">
				<h1>todos</h1>
				<form
					className="new-todo-form"
					data-action="add"
					onClick={(event) => {
						onTrace('press', { area: 'new-todo' }, event);
					}}
					onSubmit={(event) => {
						const currentState5 = next.current;
						event.preventDefault();
						const title = draft.trim();
						const item = { id: `t${currentState5}`, title, done: false };
						const nextTodos = title === '' ? todos : todos.concat(item);
						setTodos(nextTodos);
						next.current = title === '' ? currentState5 : currentState5 + 1;
						const nextDraft = '';
						setDraft(nextDraft);
						onTrace('add', { id: item.id, title }, event);
					}}
				>
					<input
						className="new-todo"
						placeholder="What needs to be done?"
						data-action="new"
						value={draft}
						onChange={(event) => {
							const nextDraft = event.target.value;
							setDraft(nextDraft);
						}}
					/>
				</form>
			</header>
			{todos.length > 0 ? (
				<main className="main">
					<input
						id="toggle-all"
						className="toggle-all"
						type="checkbox"
						data-action="toggle-all"
						checked={allDone}
						onChange={(event) => {
							const done = event.target.checked;
							const nextTodos = todos.map((todo) => ({
								id: todo.id,
								title: todo.title,
								done,
							}));
							setTodos(nextTodos);
							onTrace('toggle-all', { done }, event);
						}}
					/>
					<label htmlFor="toggle-all">Mark all as complete</label>
					<ul className="todo-list">
						{todos.map((todo) => (
							<li
								key={todo.id}
								className={
									editing === todo.id ? 'editing' : todo.done ? 'completed' : ''
								}
								data-oracle-todo-key={todo.id}
								hidden={
									filter === 'active'
										? todo.done
										: filter === 'completed'
											? !todo.done
											: false
								}
							>
								{editing === todo.id ? (
									<form
										className="edit-form"
										data-commit={todo.id}
										onClick={(event) => {
											onTrace('press', { area: 'edit' }, event);
										}}
										onSubmit={(event) => {
											event.preventDefault();
											const title = editDraft.trim();
											const nextTodos =
												title === ''
													? todos
													: todos.map((entry) =>
															entry.id === todo.id
																? {
																		id: entry.id,
																		title,
																		done: entry.done,
																	}
																: entry,
														);
											setTodos(nextTodos);
											const nextEditing = '';
											setEditing(nextEditing);
											const nextEditDraft = '';
											setEditDraft(nextEditDraft);
											onTrace('commit', { id: todo.id, title }, event);
										}}
									>
										<input
											className="edit"
											data-edit={todo.id}
											value={editDraft}
											onChange={(event) => {
												const nextEditDraft = event.target.value;
												setEditDraft(nextEditDraft);
											}}
										/>
										<button
											type="button"
											className="cancel-edit"
											data-revert={todo.id}
											onClick={(event) => {
												const nextEditing = '';
												setEditing(nextEditing);
												const nextEditDraft = '';
												setEditDraft(nextEditDraft);
												onTrace('revert', { id: todo.id }, event);
											}}
										>
											cancel
										</button>
									</form>
								) : (
									<div className="view">
										<input
											className="toggle"
											type="checkbox"
											data-toggle={todo.id}
											checked={todo.done}
											onChange={(event) => {
												const done = event.target.checked;
												const nextTodos = todos.map((entry) =>
													entry.id === todo.id
														? { id: entry.id, title: entry.title, done }
														: entry,
												);
												setTodos(nextTodos);
												onTrace('toggle', { id: todo.id, done }, event);
											}}
										/>
										<button
											type="button"
											className="todo-title"
											data-title={todo.id}
											onClick={(event) => {
												const opened = event.detail === 2;
												const nextEditing = opened ? todo.id : editing;
												setEditing(nextEditing);
												const nextEditDraft = opened
													? todo.title
													: editDraft;
												setEditDraft(nextEditDraft);
												onTrace('edit', { id: todo.id, opened }, event);
											}}
										>
											{todo.title}
										</button>
										<button
											type="button"
											className="destroy"
											data-destroy={todo.id}
											onClick={(event) => {
												const nextTodos = todos.filter(
													(entry) => entry.id !== todo.id,
												);
												setTodos(nextTodos);
												onTrace('destroy', { id: todo.id }, event);
											}}
										>
											x
										</button>
									</div>
								)}
							</li>
						))}
					</ul>
				</main>
			) : null}
			{todos.length > 0 ? (
				<footer className="footer">
					<span className="todo-count">
						<strong>{active}</strong>
						{remainingLabel}
					</span>
					<ul className="filters">
						<li>
							<a
								href="#/"
								data-filter="all"
								className={filter === 'all' ? 'selected' : ''}
								onClick={(event) => {
									event.preventDefault();
									const nextFilter = 'all';
									setFilter(nextFilter);
									onTrace('filter', { filter: 'all' }, event);
								}}
							>
								All
							</a>
						</li>
						<li>
							<a
								href="#/active"
								data-filter="active"
								className={filter === 'active' ? 'selected' : ''}
								onClick={(event) => {
									event.preventDefault();
									const nextFilter = 'active';
									setFilter(nextFilter);
									onTrace('filter', { filter: 'active' }, event);
								}}
							>
								Active
							</a>
						</li>
						<li>
							<a
								href="#/completed"
								data-filter="completed"
								className={filter === 'completed' ? 'selected' : ''}
								onClick={(event) => {
									event.preventDefault();
									const nextFilter = 'completed';
									setFilter(nextFilter);
									onTrace('filter', { filter: 'completed' }, event);
								}}
							>
								Completed
							</a>
						</li>
					</ul>
					{completed > 0 ? (
						<button
							type="button"
							className="clear-completed"
							data-action="clear-completed"
							onClick={(event) => {
								const cleared = todos.filter((todo) => todo.done).length;
								const nextTodos = todos.filter((todo) => !todo.done);
								setTodos(nextTodos);
								onTrace('clear-completed', { cleared }, event);
							}}
						>
							Clear completed
						</button>
					) : null}
				</footer>
			) : null}
		</section>
	);
}
