<!-- @generated by @frameless/svelte from BranchBoard; do not edit. -->
<script>
	import { untrack } from 'svelte';
	let { seed, onTrace } = $props();
	let phase = $state('live');
	let entries = $state(untrack(() => seed.slice()));
	let ticks = $state(0);
	let seen = $state('none');
	const size = $derived(entries.length);
</script>

<section data-scenario="s5"
	><p data-count="size">{size}</p
	><button
		data-action="toggle"
		onclick={(event) => {
			const next = phase === 'live' ? 'idle' : 'live';
			phase = next;
			onTrace('toggle', { phase: next }, event);
		}}
	>toggle</button
	>{#if phase === 'live'}
		<div data-arm="live"
			><output data-live-ticks="true">{ticks}</output
			><p data-live-seen="true">{seen}</p
			><button
				data-action="tick"
				onclick={(event) => {
					ticks++;
					onTrace('tick', { ticks }, event);
				}}
			>tick</button
			><ul data-branch-rows="true"
				>{#each entries as entry (entry.id)}
					<li data-oracle-branch-key={entry.id}
						><button
							data-pick={entry.id}
							onclick={(event) => {
								seen = entry.id;
								onTrace('pick', { id: entry.id }, event);
							}}
						>pick</button
					></li>
				{/each}</ul
		></div>
	{:else}
		<div data-arm="idle"
			><output data-idle-ticks="true">{ticks}</output
			><p data-idle-seen="true">{seen}</p
			><button
				data-action="drop"
				onclick={(event) => {
					const remaining = entries.slice(1);
					entries = remaining;
					onTrace('drop', { size: remaining.length }, event);
				}}
			>drop</button
		></div>
	{/if}</section>
