<!-- @generated by @frameless/svelte from EventForm; do not edit. -->
<script lang="ts">
	import { untrack } from 'svelte';
	let { initial, onTrace } = $props();
	let text = $state(untrack(() => initial));
	let checked = $state(false);
	let writes = $state(0);
</script>

<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_noninteractive_element_interactions --><form
	data-scenario="s3"
	onclick={(event) => {
		if (event.target.dataset.action === 'submit') {
			onTrace('bubble', { source: 'form' }, event);
		}
	}}
	><input
		data-action="text"
		value={text}
		oninput={(event) => {
			text = event.currentTarget.value;
			onTrace('text', { value: event.currentTarget.value }, event);
		}}
	><input
		type="checkbox"
		data-action="checked"
		checked={checked}
		onchange={(event) => {
			checked = event.currentTarget.checked;
			onTrace('checked', { checked: event.currentTarget.checked }, event);
		}}
	><button
		type="button"
		data-action="submit"
		onclick={(event) => {
			event.preventDefault();
			writes = 1;
			writes = 2;
			onTrace('submit', { text, checked, writes: 2 }, event);
		}}
	>submit</button
	><button
		type="submit"
		data-action="cancel-submit"
		onclick={(event) => {
			event.preventDefault();
		}}
	>cancel-submit</button
	><output data-writes="true">{writes}</output
	><span data-callback-marker="present"></span
	><details data-cancel="guarded"
		><summary
			data-action="cancel-open"
			onclick={(event) => {
				if (event.detail === 1) {
					event.preventDefault();
				}
			}}
		>cancel-open</summary
	></details
	><details data-cancel="unguarded"
		><summary
			data-action="allow-open"
			onclick={(event) => {
				if (event.detail === 2) {
					event.preventDefault();
				}
			}}
		>allow-open</summary
	></details
></form>
