<!-- @generated by @frameless/svelte from FormBoard; do not edit. -->
<script>
	import { untrack } from 'svelte';
	let { seed, onTrace } = $props();
	let size = $state('s');
	let notes = $state('draft');
	let pick = $state('r1');
	let lock = $state(null);
	let rows = $state(untrack(() => seed.map((row) => ({ ...row }))));
	const chosen = $derived(rows.filter((row) => row.on).map((row) => row.id).join('+') || 'none');
	const onFirst = $derived(pick === 'r1');
	const onSecond = $derived(pick === 'r2');
	const locked = $derived(lock !== null);
	const guard = $derived(lock === null ? null : 'held');
</script>

<form data-scenario="s7"
	><select
		data-control="size"
		data-size={size}
		oninput={(event) => {
			const next = event.currentTarget.value;
			size = next;
			onTrace('size', { size: next }, event);
		}}
		><option value="s">small</option
		><option value="m">medium</option
		><option value="l">large</option
	></select
	><textarea
		data-control="notes"
		data-notes={notes}
		oninput={(event) => {
			const next = event.currentTarget.value;
			notes = next;
			onTrace('notes', { notes: next }, event);
		}}
	></textarea
	><input
		type="radio"
		name="s7pick"
		data-pick="r1"
		checked={onFirst}
		onchange={(event) => {
			pick = 'r1';
			onTrace('pick', { pick: 'r1' }, event);
		}}
	><input
		type="radio"
		name="s7pick"
		data-pick="r2"
		checked={onSecond}
		onchange={(event) => {
			pick = 'r2';
			onTrace('pick', { pick: 'r2' }, event);
		}}
	><p data-picked="true">{pick}</p
	><p data-chosen="true">{chosen}</p
	><ul data-tags="true"
		>{#each rows as row (row.id)}
			<li data-oracle-form-key={row.id}
				><input
					type="checkbox"
					data-tag={row.id}
					checked={row.on}
					onchange={(event) => {
						const next = rows.map((entry) => entry.id === row.id ? { id: entry.id, on: !entry.on } : entry);
						rows = next;
						onTrace('tag', { id: row.id }, event);
					}}
			></li>
		{/each}</ul
	><button
		type="button"
		data-action="resize"
		onclick={(event) => {
			size = 'l';
			notes = 'final';
			onTrace('resize', { size: 'l', notes: 'final' }, event);
		}}
	>resize</button
	><button
		type="button"
		data-action="lock"
		data-lock={lock}
		onclick={(event) => {
			const next = lock === null ? 'on' : null;
			lock = next;
			onTrace('lock', { lock: next }, event);
		}}
	>lock</button
	><button type="button" data-guard="true" aria-disabled={locked} data-held={guard}>guard</button
></form>
