<!-- @generated by @frameless/svelte from RenderOnce; do not edit. -->
<script>
	import { untrack } from 'svelte';
	let { label, multiplier, visible, onTrace } = $props();
	untrack(() => onTrace('setup', { runs: 1 }));
	let count = $state(1);
	const prefix = untrack(() => `${label}:`);
	const derived = $derived(`${prefix}${count * multiplier}`);
</script>

<div data-s1-root=""
	>{#if !visible}
		<p data-branch="hidden">hidden</p>
	{:else}
		<section data-scenario="s1"
			><output data-value="derived">{derived}</output
			><button
				data-action="increment"
				onclick={() => {
					count++;
					onTrace('change', { count });
				}}
			>increment</button
		></section>
	{/if}</div>
