<!-- @generated by @frameless/svelte from TodoMvc; do not edit. -->
<script lang="ts">
	let { onTrace }: {
		onTrace: (name: string, detail: Record<string, unknown>, event: unknown) => void;
	} = $props();
	let todos = $state([{ id: 't1', title: 'Taste JavaScript', done: true }, { id: 't2', title: 'Buy a unicorn', done: false }]);
	let draft = $state('');
	let next = $state(3);
	let filter = $state('all');
	let editing = $state('');
	let editDraft = $state('');
	const active = $derived(todos.filter((todo) => !todo.done).length);
	const completed = $derived(todos.filter((todo) => todo.done).length);
	const allDone = $derived(todos.length > 0 && todos.filter((todo) => !todo.done).length === 0);
	const remainingLabel = $derived(todos.filter((todo) => !todo.done).length === 1 ? ' item left' : ' items left');
</script>

<section class="todoapp" data-app="todomvc"
	><header class="header"
		><h1>todos</h1
		><!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_noninteractive_element_interactions --><form
			class="new-todo-form"
			data-action="add"
			onclick={(event) => onTrace('press', { area: 'new-todo' }, event)}
			onsubmit={(event) => {
				event.preventDefault();
				const title = draft.trim();
				const item = { id: `t${next}`, title, done: false };
				todos = title === '' ? todos : todos.concat(item);
				next = title === '' ? next : next + 1;
				draft = '';
				onTrace('add', { id: item.id, title }, event);
			}}
			><input
				class="new-todo"
				placeholder="What needs to be done?"
				data-action="new"
				value={draft}
				oninput={(event) => draft = event.currentTarget.value}
		></form
	></header
	>{#if todos.length > 0}
		<main class="main"
			><input
				id="toggle-all"
				class="toggle-all"
				type="checkbox"
				data-action="toggle-all"
				checked={allDone}
				onchange={(event) => {
					const done = event.currentTarget.checked;
					todos = todos.map((todo) => ({ id: todo.id, title: todo.title, done }));
					onTrace('toggle-all', { done }, event);
				}}
			><label for="toggle-all">Mark all as complete</label
			><ul class="todo-list"
				>{#each todos as todo (todo.id)}
					<li
						class={editing === todo.id ? 'editing' : todo.done ? 'completed' : ''}
						data-oracle-todo-key={todo.id}
						hidden={filter === 'active' ? todo.done : filter === 'completed' ? !todo.done : false}
						>{#if editing === todo.id}
							<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_noninteractive_element_interactions --><form
								class="edit-form"
								data-commit={todo.id}
								onclick={(event) => onTrace('press', { area: 'edit' }, event)}
								onsubmit={(event) => {
									event.preventDefault();
									const title = editDraft.trim();
									todos = title === '' ? todos : todos.map((entry) => entry.id === todo.id ? { id: entry.id, title, done: entry.done } : entry);
									editing = '';
									editDraft = '';
									onTrace('commit', { id: todo.id, title }, event);
								}}
								><input
									class="edit"
									data-edit={todo.id}
									value={editDraft}
									oninput={(event) => editDraft = event.currentTarget.value}
								><button
									type="button"
									class="cancel-edit"
									data-revert={todo.id}
									onclick={(event) => {
										editing = '';
										editDraft = '';
										onTrace('revert', { id: todo.id }, event);
									}}
								>cancel</button
							></form>
						{:else}
							<div class="view"
								><input
									class="toggle"
									type="checkbox"
									data-toggle={todo.id}
									checked={todo.done}
									onchange={(event) => {
										const done = event.currentTarget.checked;
										todos = todos.map((entry) => entry.id === todo.id ? { id: entry.id, title: entry.title, done } : entry);
										onTrace('toggle', { id: todo.id, done }, event);
									}}
								><button
									type="button"
									class="todo-title"
									data-title={todo.id}
									onclick={(event) => {
										const opened = event.detail === 2;
										editing = opened ? todo.id : editing;
										editDraft = opened ? todo.title : editDraft;
										onTrace('edit', { id: todo.id, opened }, event);
									}}
								>{todo.title}</button
								><button
									type="button"
									class="destroy"
									data-destroy={todo.id}
									onclick={(event) => {
										todos = todos.filter((entry) => entry.id !== todo.id);
										onTrace('destroy', { id: todo.id }, event);
									}}
								>x</button
							></div>
						{/if}</li>
				{/each}</ul
		></main>
	{/if}{#if todos.length > 0}
		<footer class="footer"
			><span class="todo-count"><strong>{active}</strong>{remainingLabel}</span
			><ul class="filters"
				><li
					><a
						href="#/"
						data-filter="all"
						class={filter === 'all' ? 'selected' : ''}
						onclick={(event) => {
							event.preventDefault();
							filter = 'all';
							onTrace('filter', { filter: 'all' }, event);
						}}
					>All</a
				></li
				><li
					><a
						href="#/active"
						data-filter="active"
						class={filter === 'active' ? 'selected' : ''}
						onclick={(event) => {
							event.preventDefault();
							filter = 'active';
							onTrace('filter', { filter: 'active' }, event);
						}}
					>Active</a
				></li
				><li
					><a
						href="#/completed"
						data-filter="completed"
						class={filter === 'completed' ? 'selected' : ''}
						onclick={(event) => {
							event.preventDefault();
							filter = 'completed';
							onTrace('filter', { filter: 'completed' }, event);
						}}
					>Completed</a
				></li
			></ul
			>{#if completed > 0}
				<button
					type="button"
					class="clear-completed"
					data-action="clear-completed"
					onclick={(event) => {
						const cleared = todos.filter((todo) => todo.done).length;
						todos = todos.filter((todo) => !todo.done);
						onTrace('clear-completed', { cleared }, event);
					}}
				>Clear completed</button>
			{/if}</footer>
	{/if}</section>
