// @generated by @frameless/solid; do not edit.
import { createSignal, untrack, For, Show } from 'solid-js';
import { createStore, reconcile } from 'solid-js/store';

export function BranchBoard(props) {
	const [phase, setPhase] = createSignal('live');
	const [entries, setEntries] = createStore(untrack(() => props.seed.slice()));
	const [ticks, setTicks] = createSignal(0);
	const [seen, setSeen] = createSignal('none');
	const size = () => entries.length;
	return (
		<section data-scenario="s5">
			<p data-count="size">{size()}</p>
			<button
				data-action="toggle"
				onClick={(event) => {
					const next = phase() === 'live' ? 'idle' : 'live';
					setPhase(next);
					props.onTrace('toggle', { phase: next }, event);
				}}
			>
				toggle
			</button>
			<Show
				when={phase() === 'live'}
				fallback={
					<div data-arm="idle">
						<output data-idle-ticks="true">{ticks()}</output>
						<p data-idle-seen="true">{seen()}</p>
						<button
							data-action="drop"
							onClick={(event) => {
								const remaining = entries.slice(1);
								setEntries(reconcile(remaining, { key: 'id' }));
								props.onTrace('drop', { size: remaining.length }, event);
							}}
						>
							drop
						</button>
					</div>
				}
			>
				<div data-arm="live">
					<output data-live-ticks="true">{ticks()}</output>
					<p data-live-seen="true">{seen()}</p>
					<button
						data-action="tick"
						onClick={(event) => {
							setTicks(ticks() + 1);
							props.onTrace('tick', { ticks: ticks() }, event);
						}}
					>
						tick
					</button>
					<ul data-branch-rows="true">
						<For each={entries}>
							{(entry) => (
								<li data-oracle-branch-key={entry.id}>
									<button
										data-pick={entry.id}
										onClick={(event) => {
											setSeen(entry.id);
											props.onTrace('pick', { id: entry.id }, event);
										}}
									>
										pick
									</button>
								</li>
							)}
						</For>
					</ul>
				</div>
			</Show>
		</section>
	);
}
