// @generated by @frameless/solid; do not edit.
import { createSignal, untrack, For } from 'solid-js';
import { createStore, reconcile } from 'solid-js/store';

export function FormBoard(props) {
	const [size, setSize] = createSignal('s');
	const [notes, setNotes] = createSignal('draft');
	const [pick, setPick] = createSignal('r1');
	const [lock, setLock] = createSignal(null);
	const [rows, setRows] = createStore(untrack(() => props.seed.map((row) => ({ ...row }))));
	const chosen = () =>
		rows
			.filter((row) => row.on)
			.map((row) => row.id)
			.join('+') || 'none';
	const onFirst = () => pick() === 'r1';
	const onSecond = () => pick() === 'r2';
	const locked = () => lock() !== null;
	const guard = () => (lock() === null ? null : 'held');
	return (
		<form data-scenario="s7">
			<select
				data-control="size"
				data-size={size()}
				onInput={(event) => {
					const next = event.currentTarget.value;
					setSize(next);
					props.onTrace('size', { size: next }, event);
				}}
			>
				<option value="s">small</option>
				<option value="m">medium</option>
				<option value="l">large</option>
			</select>
			<textarea
				data-control="notes"
				data-notes={notes()}
				onInput={(event) => {
					const next = event.currentTarget.value;
					setNotes(next);
					props.onTrace('notes', { notes: next }, event);
				}}
			/>
			<input
				type="radio"
				name="s7pick"
				data-pick="r1"
				checked={onFirst()}
				onChange={(event) => {
					setPick('r1');
					props.onTrace('pick', { pick: 'r1' }, event);
				}}
			/>
			<input
				type="radio"
				name="s7pick"
				data-pick="r2"
				checked={onSecond()}
				onChange={(event) => {
					setPick('r2');
					props.onTrace('pick', { pick: 'r2' }, event);
				}}
			/>
			<p data-picked="true">{pick()}</p>
			<p data-chosen="true">{chosen()}</p>
			<ul data-tags="true">
				<For each={rows}>
					{(row) => (
						<li data-oracle-form-key={row.id}>
							<input
								type="checkbox"
								data-tag={row.id}
								checked={row.on}
								onChange={(event) => {
									const next = rows.map((entry) =>
										entry.id === row.id
											? { id: entry.id, on: !entry.on }
											: entry,
									);
									setRows(reconcile(next, { key: 'id' }));
									props.onTrace('tag', { id: row.id }, event);
								}}
							/>
						</li>
					)}
				</For>
			</ul>
			<button
				type="button"
				data-action="resize"
				onClick={(event) => {
					setSize('l');
					setNotes('final');
					props.onTrace('resize', { size: 'l', notes: 'final' }, event);
				}}
			>
				resize
			</button>
			<button
				type="button"
				data-action="lock"
				data-lock={lock()}
				onClick={(event) => {
					const next = lock() === null ? 'on' : null;
					setLock(next);
					props.onTrace('lock', { lock: next }, event);
				}}
			>
				lock
			</button>
			<button type="button" data-guard="true" aria-disabled={locked()} data-held={guard()}>
				guard
			</button>
		</form>
	);
}
