// @generated by @frameless/solid; do not edit.
import { createSignal, untrack, Show } from 'solid-js';

export function RenderOnce(props) {
	untrack(() => props.onTrace('setup', { runs: 1 }));
	const [count, setCount] = createSignal(1);
	const prefix = untrack(() => `${props.label}:`);
	const derived = () => `${prefix}${count() * props.multiplier}`;
	return (
		<div data-s1-root="">
			<Show
				when={!props.visible}
				fallback={
					<section data-scenario="s1">
						<output data-value="derived">{derived()}</output>
						<button
							data-action="increment"
							onClick={() => {
								setCount(count() + 1);
								props.onTrace('change', { count: count() });
							}}
						>
							increment
						</button>
					</section>
				}
			>
				<p data-branch="hidden">hidden</p>
			</Show>
		</div>
	);
}
