// @generated by @frameless/solid; do not edit.
import { For } from 'solid-js';
import { createStore, reconcile } from 'solid-js/store';

export function TaskBoard(props: {
	onTrace: (name: string, detail: Record<string, unknown>, event: unknown) => void;
}) {
	const [columns, setColumns] = createStore([
		{
			id: 'backlog',
			title: 'Backlog',
			mark: '◌',
			prevId: '',
			nextId: 'todo',
			tasks: [
				{
					id: 't1',
					title: 'Mobile app redesign',
					blurb: 'Complete redesign of mobile application for better UX',
					date: 'Feb 10',
					comments: '2',
					links: '3',
					tags: [{ id: 't1g1', name: 'Design' }],
				},
				{
					id: 't2',
					title: 'API documentation update',
					blurb: 'Update API docs with latest endpoints and examples',
					date: 'Feb 15',
					comments: '',
					links: '8',
					tags: [{ id: 't2g1', name: 'Product' }],
				},
				{
					id: 't3',
					title: 'Accessibility improvements',
					blurb: 'Enhance accessibility for screen readers and keyboard navigation',
					date: 'Feb 20',
					comments: '1',
					links: '5',
					tags: [
						{ id: 't3g1', name: 'Design' },
						{ id: 't3g2', name: 'New releases' },
					],
				},
			],
		},
		{
			id: 'todo',
			title: 'Todo',
			mark: '○',
			prevId: 'backlog',
			nextId: 'progress',
			tasks: [
				{
					id: 't4',
					title: 'Design system update',
					blurb: 'Enhance design system for consistency and usability',
					date: 'Jan 25',
					comments: '4',
					links: '',
					tags: [
						{ id: 't4g1', name: 'Design' },
						{ id: 't4g2', name: 'New releases' },
					],
				},
				{
					id: 't5',
					title: 'Retention rate by 23%',
					blurb: 'Improve retention through campaigns and feature updates',
					date: 'Jan 25',
					comments: '4',
					links: '12',
					tags: [
						{ id: 't5g1', name: 'Marketing' },
						{ id: 't5g2', name: 'Product' },
					],
				},
				{
					id: 't6',
					title: 'Icon system',
					blurb: 'Develop scalable icons for cohesive platform visuals',
					date: 'Jan 25',
					comments: '4',
					links: '',
					tags: [{ id: 't6g1', name: 'Design' }],
				},
			],
		},
		{
			id: 'progress',
			title: 'In Progress',
			mark: '◑',
			prevId: 'todo',
			nextId: 'review',
			tasks: [
				{
					id: 't7',
					title: 'Search features',
					blurb: 'Upgrade search for faster, accurate user results',
					date: 'Jan 25',
					comments: '',
					links: '12',
					tags: [{ id: 't7g1', name: 'Product' }],
				},
				{
					id: 't8',
					title: 'Checkout flow design',
					blurb: 'Optimize checkout process to improve conversion rates',
					date: 'Jan 25',
					comments: '',
					links: '12',
					tags: [{ id: 't8g1', name: 'Design' }],
				},
			],
		},
		{
			id: 'review',
			title: 'Technical Review',
			mark: '◍',
			prevId: 'progress',
			nextId: '',
			tasks: [
				{
					id: 't9',
					title: 'Payment gateway integration',
					blurb: 'Integrate Stripe payment system for subscriptions',
					date: 'Jan 28',
					comments: '2',
					links: '5',
					tags: [{ id: 't9g1', name: 'Product' }],
				},
			],
		},
	]);
	const shipped = () =>
		columns
			.filter((column) => column.nextId === '')
			.reduce((sum, column) => sum + column.tasks.length, 0);
	const totalLabel = () => `/${columns.reduce((sum, column) => sum + column.tasks.length, 0)}`;
	const tally = () =>
		`${columns.filter((column) => column.nextId === '').reduce((sum, column) => sum + column.tasks.length, 0)}/${columns.reduce((sum, column) => sum + column.tasks.length, 0)}`;
	const summary = () =>
		columns
			.filter((column) => column.nextId === '')
			.reduce((sum, column) => sum + column.tasks.length, 0) === 0
			? 'Nothing has reached review yet.'
			: columns
						.filter((column) => column.nextId === '')
						.reduce((sum, column) => sum + column.tasks.length, 0) < 2
				? 'Review is filling up.'
				: columns
							.filter((column) => column.nextId === '')
							.reduce((sum, column) => sum + column.tasks.length, 0) < 4
					? 'Half the board is in review.'
					: columns
								.filter((column) => column.nextId === '')
								.reduce((sum, column) => sum + column.tasks.length, 0) < 9
						? 'Almost everything is in review.'
						: 'Every task is in review.';
	const summaryEmoji = () =>
		columns
			.filter((column) => column.nextId === '')
			.reduce((sum, column) => sum + column.tasks.length, 0) === 0
			? '◔'
			: columns
						.filter((column) => column.nextId === '')
						.reduce((sum, column) => sum + column.tasks.length, 0) < 2
				? '◑'
				: columns
							.filter((column) => column.nextId === '')
							.reduce((sum, column) => sum + column.tasks.length, 0) < 4
					? '◕'
					: columns
								.filter((column) => column.nextId === '')
								.reduce((sum, column) => sum + column.tasks.length, 0) < 9
						? '●'
						: '✦';
	return (
		<section class="tb" data-app="task-board">
			<div class="tb-shell">
				<aside class="tb-side" data-tb="sidebar">
					<div class="tb-brand" data-tb="brand">
						<span class="tb-mark">◧</span>
						<span class="tb-brandname">Frameless</span>
					</div>
					<nav class="tb-nav" data-tb="nav">
						<a
							class="tb-navlink"
							href="#/dashboard"
							data-nav="dashboard"
							onClick={(event) => {
								event.preventDefault();
								props.onTrace('nav', { to: 'dashboard' }, event);
							}}
						>
							<span class="tb-navicon">▤</span>
							<span class="tb-navtext">Dashboard</span>
						</a>
						<a
							class="tb-navlink tb-navlink-on"
							href="#/task"
							data-nav="task"
							onClick={(event) => {
								event.preventDefault();
								props.onTrace('nav', { to: 'task' }, event);
							}}
						>
							<span class="tb-navicon">☆</span>
							<span class="tb-navtext">Task</span>
							<span class="tb-badge" data-badge="task">
								{tally()}
							</span>
						</a>
						<a
							class="tb-navlink"
							href="#/projects"
							data-nav="projects"
							onClick={(event) => {
								event.preventDefault();
								props.onTrace('nav', { to: 'projects' }, event);
							}}
						>
							<span class="tb-navicon">▣</span>
							<span class="tb-navtext">Projects</span>
						</a>
					</nav>
					<div class="tb-promo" data-tb="promo">
						<span class="tb-promotitle">One source, six lanes</span>
						<span class="tb-promotext">
							Every pixel on this page is emitted from a single .tsrx module into
							react, solid, qwik, svelte, vue and angular.
						</span>
					</div>
				</aside>
				<div class="tb-content">
					<header class="tb-top" data-tb="topbar">
						<button
							type="button"
							class="tb-icon"
							aria-label="toggle sidebar"
							data-action="toggle-sidebar"
							onClick={(event) => {
								props.onTrace('press', { area: 'toggle-sidebar' }, event);
							}}
						>
							<span class="tb-iconglyph">▥</span>
						</button>
						<h1 class="tb-crumb" data-tb="crumb">
							Task
						</h1>
						<span class="tb-topgap" />
						<span class="tb-stamp" data-tb="stamp">
							Last update 3 days ago
						</span>
						<button
							type="button"
							class="tb-pill"
							data-action="share"
							onClick={(event) => {
								props.onTrace('press', { area: 'share' }, event);
							}}
						>
							<span class="tb-pillglyph">↗</span>
							<span class="tb-pilltext">Share</span>
						</button>
					</header>
					<div class="tb-tools" data-tb="tools">
						<button
							type="button"
							class="tb-tool"
							data-action="filter"
							onClick={(event) => {
								props.onTrace('press', { area: 'filter' }, event);
							}}
						>
							<span class="tb-toolglyph">⚟</span>
							<span class="tb-tooltext">Filter</span>
						</button>
						<button
							type="button"
							class="tb-tool"
							data-action="sort"
							onClick={(event) => {
								props.onTrace('press', { area: 'sort' }, event);
							}}
						>
							<span class="tb-toolglyph">⇅</span>
							<span class="tb-tooltext">Sort</span>
						</button>
						<span class="tb-toolgap" />
						<span class="tb-date" data-tb="date">
							Sep 6, 2024
						</span>
						<button
							type="button"
							class="tb-tool tb-tool-solid"
							data-action="request-task"
							onClick={(event) => {
								props.onTrace('press', { area: 'request-task' }, event);
							}}
						>
							<span class="tb-toolglyph">+</span>
							<span class="tb-tooltext">Request task</span>
						</button>
					</div>
					<div class="tb-headline" data-tb="headline">
						<p class="tb-tally">
							<span class="tb-tallydone" data-tally="done">
								{shipped()}
							</span>
							<span class="tb-tallytotal" data-tally="total">
								{totalLabel()}
							</span>
						</p>
						<p class="tb-summaryline">
							<span class="tb-summaryemoji" data-summary="emoji">
								{summaryEmoji()}
							</span>
							<span class="tb-summarytext" data-summary="text">
								{summary()}
							</span>
						</p>
					</div>
					<p class="tb-note" data-tb="dragnote">
						<span class="tb-notemark">!</span>
						<span class="tb-notetext">
							DRAG AND DROP IS NOT WIRED ON THIS PAGE, and that absence is the
							measurement. Cards move with the ◀ and ▶ arrows instead — a different
							interaction, labelled as one. Measured through all six real emitters:
							the drag events DO emit in five lanes and are inert only where the lane
							binds by a framework prop name, but one drop zone and one draggable card
							take pnpm check from 267 to 280. See the fixture header.
						</span>
					</p>
					<main class="tb-board" data-tb="board">
						<For each={columns}>
							{(column) => (
								<div class="tb-col" data-col={column.id}>
									<div class="tb-colhead" data-colhead={column.id}>
										<span class="tb-colmark">{column.mark}</span>
										<span class="tb-coltitle" data-coltitle={column.id}>
											{column.title}
										</span>
										<span class="tb-colcount" data-colcount={column.id}>
											{column.tasks.length}
										</span>
										<span class="tb-colgap" />
										<button
											type="button"
											class="tb-colicon"
											aria-label="add task to column"
											data-coladd={column.id}
											onClick={(event) => {
												props.onTrace('press', { area: 'col-add' }, event);
											}}
										>
											<span class="tb-iconglyph">+</span>
										</button>
									</div>
									<ul class="tb-cards" data-cards={column.id}>
										<For each={column.tasks}>
											{(task) => (
												<li class="tb-card" data-card={task.id}>
													<div class="tb-cardtop">
														<span class="tb-cardmark">
															{column.mark}
														</span>
														<span
															class="tb-cardtitle"
															data-cardtitle={task.id}
														>
															{task.title}
														</span>
													</div>
													<p
														class="tb-cardblurb"
														data-cardblurb={task.id}
													>
														{task.blurb}
													</p>
													<div class="tb-tags" data-tags={task.id}>
														<For each={task.tags}>
															{(tag) => (
																<span
																	class="tb-tag"
																	data-tag={tag.id}
																>
																	{tag.name}
																</span>
															)}
														</For>
													</div>
													<div
														class="tb-cardfoot"
														data-cardfoot={task.id}
													>
														<span class="tb-meta">
															<span class="tb-metaglyph">▤</span>
															<span class="tb-metatext">
																{task.date}
															</span>
														</span>
														<span
															class="tb-meta"
															hidden={task.comments === ''}
														>
															<span class="tb-metaglyph">▭</span>
															<span class="tb-metatext">
																{task.comments}
															</span>
														</span>
														<span
															class="tb-meta"
															hidden={task.links === ''}
														>
															<span class="tb-metaglyph">⛓</span>
															<span class="tb-metatext">
																{task.links}
															</span>
														</span>
														<span class="tb-metagap" />
														<button
															type="button"
															class="tb-move"
															aria-label="move task to the previous column"
															data-left={task.id}
															hidden={column.prevId === ''}
															onClick={(event) => {
																setColumns(
																	reconcile(
																		columns.map((entry) =>
																			entry.id === column.id
																				? {
																						id: entry.id,
																						title: entry.title,
																						mark: entry.mark,
																						prevId: entry.prevId,
																						nextId: entry.nextId,
																						tasks: entry.tasks.filter(
																							(row) =>
																								row.id !==
																								task.id,
																						),
																					}
																				: entry.id ===
																					  column.prevId
																					? {
																							id: entry.id,
																							title: entry.title,
																							mark: entry.mark,
																							prevId: entry.prevId,
																							nextId: entry.nextId,
																							tasks: entry.tasks.concat(
																								[
																									task,
																								],
																							),
																						}
																					: entry,
																		),
																		{ key: 'id' },
																	),
																);
																props.onTrace(
																	'move',
																	{
																		id: task.id,
																		to: column.prevId,
																	},
																	event,
																);
															}}
														>
															<span class="tb-moveglyph">◀</span>
														</button>
														<button
															type="button"
															class="tb-move"
															aria-label="move task to the next column"
															data-right={task.id}
															hidden={column.nextId === ''}
															onClick={(event) => {
																setColumns(
																	reconcile(
																		columns.map((entry) =>
																			entry.id === column.id
																				? {
																						id: entry.id,
																						title: entry.title,
																						mark: entry.mark,
																						prevId: entry.prevId,
																						nextId: entry.nextId,
																						tasks: entry.tasks.filter(
																							(row) =>
																								row.id !==
																								task.id,
																						),
																					}
																				: entry.id ===
																					  column.nextId
																					? {
																							id: entry.id,
																							title: entry.title,
																							mark: entry.mark,
																							prevId: entry.prevId,
																							nextId: entry.nextId,
																							tasks: entry.tasks.concat(
																								[
																									task,
																								],
																							),
																						}
																					: entry,
																		),
																		{ key: 'id' },
																	),
																);
																props.onTrace(
																	'move',
																	{
																		id: task.id,
																		to: column.nextId,
																	},
																	event,
																);
															}}
														>
															<span class="tb-moveglyph">▶</span>
														</button>
													</div>
												</li>
											)}
										</For>
									</ul>
									<p
										class="tb-empty"
										data-empty={column.id}
										hidden={column.tasks.length !== 0}
									>
										<span class="tb-emptytext">No tasks here.</span>
									</p>
									<button
										type="button"
										class="tb-add"
										data-add={column.id}
										onClick={(event) => {
											props.onTrace('press', { area: 'add-task' }, event);
										}}
									>
										<span class="tb-addglyph">+</span>
										<span class="tb-addtext">Add task</span>
									</button>
								</div>
							)}
						</For>
					</main>
				</div>
			</div>
		</section>
	);
}
