// @generated by @frameless/solid; do not edit.
import { createSignal, For, Show } from 'solid-js';
import { createStore, reconcile } from 'solid-js/store';

export function TodoMvcAdvanced(props: {
	onTrace: (name: string, detail: Record<string, unknown>, event: unknown) => void;
}) {
	const [todos, setTodos] = createStore([
		{ id: 't1', title: 'Taste JavaScript', done: true, pending: false },
		{ id: 't2', title: 'Buy a unicorn', done: false, pending: false },
		{ id: 't3', title: 'Measure the async door', done: false, pending: false },
	]);
	const [draft, setDraft] = createSignal('');
	let next = 4;
	const [filter, setFilter] = createSignal('all');
	const [editing, setEditing] = createSignal('');
	const [editDraft, setEditDraft] = createSignal('');
	const [query, setQuery] = createSignal('');
	const [remoteTerm, setRemoteTerm] = createSignal('');
	const [remoteHits, setRemoteHits] = createSignal(0);
	const [remoteStatus, setRemoteStatus] = createSignal('idle');
	const [serverFails, setServerFails] = createSignal(false);
	const [syncNote, setSyncNote] = createSignal('idle');
	const active = () => todos.filter((todo) => !todo.done).length;
	const completed = () => todos.filter((todo) => todo.done).length;
	const allDone = () => todos.length > 0 && todos.filter((todo) => !todo.done).length === 0;
	const remainingLabel = () =>
		todos.filter((todo) => !todo.done).length === 1 ? ' item left' : ' items left';
	const shown = () =>
		todos.filter(
			(todo) => query() === '' || todo.title.toLowerCase().includes(query().toLowerCase()),
		).length;
	const shownLabel = () =>
		todos.filter(
			(todo) => query() === '' || todo.title.toLowerCase().includes(query().toLowerCase()),
		).length === 1
			? ' row matches locally'
			: ' rows match locally';
	const remoteLabel = () => (remoteHits() === 1 ? ' remote match for ' : ' remote matches for ');
	const searching = () => remoteStatus() === 'searching';
	return (
		<section class="todoapp todoapp-advanced" data-app="todomvc-advanced">
			<header class="header">
				<h1>todos</h1>
				<form
					class="new-todo-form"
					data-action="add"
					onClick={(event) => {
						props.onTrace('press', { area: 'new-todo' }, event);
					}}
					onSubmit={(event) => {
						event.preventDefault();
						const title = draft().trim();
						const item = { id: `t${next}`, title, done: false, pending: false };
						setTodos(
							reconcile(title === '' ? todos : todos.concat(item), { key: 'id' }),
						);
						next = title === '' ? next : next + 1;
						setDraft('');
						props.onTrace('add', { id: item.id, title }, event);
					}}
				>
					<input
						class="new-todo"
						placeholder="What needs to be done?"
						data-action="new"
						value={draft()}
						attr:value={draft()}
						onInput={(event) => {
							setDraft(event.currentTarget.value);
						}}
					/>
				</form>
			</header>
			<div class="advanced" data-advanced="bar">
				<form
					class="search-form"
					data-action="search"
					onClick={(event) => {
						props.onTrace('press', { area: 'search' }, event);
					}}
					onSubmit={async (event) => {
						event.preventDefault();
						const term = query().trim();
						const hits = todos.filter(
							(todo) =>
								term === '' ||
								todo.title.toLowerCase().includes(term.toLowerCase()),
						).length;
						setRemoteTerm(term);
						setRemoteStatus('searching');
						await new Promise((settle) => {
							setTimeout(() => settle(true), 600);
						});
						setRemoteHits(hits);
						setRemoteStatus('done');
						props.onTrace('remote-search', { term, hits }, event);
					}}
				>
					<input
						class="search"
						placeholder="Filter locally, submit to query"
						data-action="search-term"
						value={query()}
						attr:value={query()}
						onInput={(event) => {
							setQuery(event.currentTarget.value);
						}}
					/>
					<button
						type="submit"
						class="search-go"
						data-action="remote"
						disabled={searching()}
					>
						search
					</button>
				</form>
				<p class="local-count" data-local="count">
					<strong>{shown()}</strong>
					{shownLabel()}
				</p>
				<p class="remote-status" data-remote="status">
					{remoteStatus()}
				</p>
				<p class="remote-count" data-remote="hits">
					<strong>{remoteHits()}</strong>
					{remoteLabel()}
					{remoteTerm()}
				</p>
				<input
					id="server-fails"
					class="server-fails"
					type="checkbox"
					data-action="server-fails"
					checked={serverFails()}
					onChange={(event) => {
						setServerFails(event.currentTarget.checked);
					}}
				/>
				<label for="server-fails">Reject the next save</label>
				<p class="sync-note" data-sync="note">
					{syncNote()}
				</p>
			</div>
			<Show when={todos.length > 0}>
				<main class="main">
					<input
						id="toggle-all"
						class="toggle-all"
						type="checkbox"
						data-action="toggle-all"
						checked={allDone()}
						onChange={(event) => {
							const done = event.currentTarget.checked;
							setTodos(
								reconcile(
									todos.map((todo) => ({
										id: todo.id,
										title: todo.title,
										done,
										pending: false,
									})),
									{ key: 'id' },
								),
							);
							props.onTrace('toggle-all', { done }, event);
						}}
					/>
					<label for="toggle-all">Mark all as complete</label>
					<ul class="todo-list">
						<For each={todos}>
							{(todo) => (
								<li
									class={
										editing() === todo.id
											? 'editing'
											: todo.pending
												? 'saving'
												: todo.done
													? 'completed'
													: ''
									}
									data-oracle-advanced-key={todo.id}
									hidden={
										query() !== '' &&
										!todo.title.toLowerCase().includes(query().toLowerCase())
											? true
											: filter() === 'active'
												? todo.done
												: filter() === 'completed'
													? !todo.done
													: false
									}
								>
									<Show
										when={editing() === todo.id}
										fallback={
											<div class="view">
												<input
													class="toggle"
													type="checkbox"
													data-toggle={todo.id}
													checked={todo.done}
													onChange={async (event) => {
														const wanted = event.currentTarget.checked;
														const rejected = serverFails();
														setTodos(
															reconcile(
																todos.map((entry) =>
																	entry.id === todo.id
																		? {
																				id: entry.id,
																				title: entry.title,
																				done: wanted,
																				pending: true,
																			}
																		: entry,
																),
																{ key: 'id' },
															),
														);
														setSyncNote('saving');
														await new Promise((settle) => {
															setTimeout(() => settle(true), 600);
														});
														setTodos(
															reconcile(
																todos.map((entry) =>
																	entry.id === todo.id
																		? {
																				id: entry.id,
																				title: entry.title,
																				done: rejected
																					? !wanted
																					: wanted,
																				pending: false,
																			}
																		: entry,
																),
																{ key: 'id' },
															),
														);
														setSyncNote(
															rejected ? 'reverted' : 'saved',
														);
														setServerFails(false);
														props.onTrace(
															'toggle',
															{ id: todo.id, done: wanted, rejected },
															event,
														);
													}}
												/>
												<button
													type="button"
													class="todo-title"
													data-title={todo.id}
													onClick={(event) => {
														const opened = event.detail === 2;
														setEditing(opened ? todo.id : editing());
														setEditDraft(
															opened ? todo.title : editDraft(),
														);
														props.onTrace(
															'edit',
															{ id: todo.id, opened },
															event,
														);
													}}
												>
													{todo.title}
												</button>
												<span
													class="row-pending"
													data-pending={todo.id}
													hidden={!todo.pending}
												>
													saving
												</span>
												<button
													type="button"
													class="destroy"
													data-destroy={todo.id}
													onClick={(event) => {
														setTodos(
															reconcile(
																todos.filter(
																	(entry) => entry.id !== todo.id,
																),
																{ key: 'id' },
															),
														);
														props.onTrace(
															'destroy',
															{ id: todo.id },
															event,
														);
													}}
												>
													x
												</button>
											</div>
										}
									>
										<form
											class="edit-form"
											data-commit={todo.id}
											onClick={(event) => {
												props.onTrace('press', { area: 'edit' }, event);
											}}
											onSubmit={(event) => {
												event.preventDefault();
												const title = editDraft().trim();
												setTodos(
													reconcile(
														title === ''
															? todos
															: todos.map((entry) =>
																	entry.id === todo.id
																		? {
																				id: entry.id,
																				title,
																				done: entry.done,
																				pending:
																					entry.pending,
																			}
																		: entry,
																),
														{ key: 'id' },
													),
												);
												setEditing('');
												setEditDraft('');
												props.onTrace(
													'commit',
													{ id: todo.id, title },
													event,
												);
											}}
										>
											<input
												class="edit"
												data-edit={todo.id}
												value={editDraft()}
												attr:value={editDraft()}
												onInput={(event) => {
													setEditDraft(event.currentTarget.value);
												}}
											/>
											<button
												type="button"
												class="cancel-edit"
												data-revert={todo.id}
												onClick={(event) => {
													setEditing('');
													setEditDraft('');
													props.onTrace('revert', { id: todo.id }, event);
												}}
											>
												cancel
											</button>
										</form>
									</Show>
								</li>
							)}
						</For>
					</ul>
				</main>
			</Show>
			<Show when={todos.length > 0}>
				<footer class="footer">
					<span class="todo-count">
						<strong>{active()}</strong>
						{remainingLabel()}
					</span>
					<ul class="filters">
						<li>
							<a
								href="#/"
								data-filter="all"
								class={filter() === 'all' ? 'selected' : ''}
								onClick={(event) => {
									event.preventDefault();
									setFilter('all');
									props.onTrace('filter', { filter: 'all' }, event);
								}}
							>
								All
							</a>
						</li>
						<li>
							<a
								href="#/active"
								data-filter="active"
								class={filter() === 'active' ? 'selected' : ''}
								onClick={(event) => {
									event.preventDefault();
									setFilter('active');
									props.onTrace('filter', { filter: 'active' }, event);
								}}
							>
								Active
							</a>
						</li>
						<li>
							<a
								href="#/completed"
								data-filter="completed"
								class={filter() === 'completed' ? 'selected' : ''}
								onClick={(event) => {
									event.preventDefault();
									setFilter('completed');
									props.onTrace('filter', { filter: 'completed' }, event);
								}}
							>
								Completed
							</a>
						</li>
					</ul>
					<Show when={completed() > 0}>
						<button
							type="button"
							class="clear-completed"
							data-action="clear-completed"
							onClick={(event) => {
								const cleared = todos.filter((todo) => todo.done).length;
								setTodos(
									reconcile(
										todos.filter((todo) => !todo.done),
										{ key: 'id' },
									),
								);
								props.onTrace('clear-completed', { cleared }, event);
							}}
						>
							Clear completed
						</button>
					</Show>
				</footer>
			</Show>
		</section>
	);
}
