// @generated by @frameless/solid; do not edit.
import { createSignal, untrack, For } from 'solid-js';
import { createStore } from 'solid-js/store';

export function WhitespaceBoard(props) {
	const [done, setDone] = createSignal(1);
	const [unit, setUnit] = createSignal('px');
	const [note, setNote] = createSignal(untrack(() => props.label));
	const [joiner, setJoiner] = createSignal('|');
	const [rows] = createStore(untrack(() => props.seed.slice()));
	const total = () => rows.length;
	return (
		<section data-scenario="s6">
			<p data-ratio="true">
				{done()}/{total()}
			</p>
			<p data-glue="true">
				start{done()}
				{unit()}end
			</p>
			<p data-wrap="true">[{note()}]</p>
			<p data-mixed="true">
				a<b data-emph="true">{unit()}</b>z
			</p>
			<p data-static="true">one two three</p>
			<ul data-lines="true">
				<For each={rows}>
					{(row) => (
						<li data-oracle-text-key={row.id}>
							<span data-pair={row.id}>
								{row.left}
								{joiner()}
								{row.right}
							</span>
							<button
								data-widen={row.id}
								onClick={(event) => {
									const next = ` ${row.id} `;
									setJoiner(next);
									props.onTrace('widen', { id: row.id, joiner: next }, event);
								}}
							>
								widen
							</button>
						</li>
					)}
				</For>
			</ul>
			<button
				data-action="tick"
				onClick={(event) => {
					setDone(done() + 1);
					setUnit('em');
					props.onTrace('tick', { done: done(), unit: unit() }, event);
				}}
			>
				tick
			</button>
			<button
				data-action="pad"
				onClick={(event) => {
					const padded = ` ${note()} `;
					setNote(padded);
					props.onTrace('pad', { note: padded }, event);
				}}
			>
				pad
			</button>
		</section>
	);
}
