// @generated by @frameless/qwik; do not edit.
import { $, component$, sync$, useSignal } from '@qwik.dev/core';

export const AsyncBoard = component$(
	(props: {
		ready: Promise<string>;
		onTrace$: (name: string, detail: Record<string, unknown>, event: unknown) => void;
	}) => {
		const ticks = useSignal(0);
		const phase = useSignal('idle');
		const cancels = useSignal(0);
		return (
			<form data-scenario="s8">
				<p data-async="ticks">{ticks.value}</p>
				<p data-async="phase">{phase.value}</p>
				<p data-async="cancels">{cancels.value}</p>
				<button
					type="button"
					data-action="run"
					onClick$={async (event) => {
						phase.value = 'pending';
						await props.ready;
						ticks.value = ticks.value + 1;
						phase.value = 'done';
						await props.onTrace$('run', { phase: 'done' }, event);
					}}
				>
					run
				</button>
				<button
					type="submit"
					data-action="cancel-run"
					onClick$={[
						sync$((event) => {
							event.preventDefault();
						}),
						$(async (event) => {
							await props.ready;
							cancels.value = cancels.value + 1;
							await props.onTrace$('cancel', { cancels: 1 }, event);
						}),
					]}
				>
					cancel
				</button>
			</form>
		);
	},
);
