// @generated by @frameless/qwik; do not edit.
import { component$, useComputed$, useSignal, useStore } from '@qwik.dev/core';

export const AttrBoard = component$((props) => {
	const locked = useSignal(false);
	const steps = useSignal(0);
	const rows = useStore(props.seed.map((row) => ({ ...row })));
	const stage = useComputed$(() => (locked.value ? 'locked' : 'open'));
	const sealed = useComputed$(
		() =>
			rows
				.filter((row) => row.off)
				.map((row) => row.id)
				.join('+') || 'none',
	);
	return (
		<section data-scenario="s9">
			<button type="button" data-gate="true" disabled={locked.value} data-stage={stage.value}>
				gate
			</button>
			<input type="text" data-note="true" required={locked.value} />
			<p data-sealed="true">{sealed.value}</p>
			<p data-steps="true">{steps.value}</p>
			<ul data-fields="true">
				{rows.map((row) => (
					<li key={row.id} data-oracle-attr-key={row.id}>
						<button type="button" data-field={row.id} disabled={row.off}>
							field
						</button>
						<button
							type="button"
							data-seal={row.id}
							onClick$={async (event) => {
								const next = rows.map((entry) =>
									entry.id === row.id ? { id: entry.id, off: !entry.off } : entry,
								);
								rows.splice(0, rows.length, ...next);
								await props.onTrace$('seal', { id: row.id }, event);
							}}
						>
							seal
						</button>
					</li>
				))}
			</ul>
			<button
				type="button"
				data-action="lock"
				onClick$={async (event) => {
					locked.value = true;
					steps.value = steps.value + 1;
					await props.onTrace$('lock', { locked: true }, event);
				}}
			>
				lock
			</button>
			<button
				type="button"
				data-action="unlock"
				onClick$={async (event) => {
					locked.value = false;
					steps.value = steps.value + 1;
					await props.onTrace$('unlock', { locked: false }, event);
				}}
			>
				unlock
			</button>
		</section>
	);
});
