// @generated by @frameless/qwik; do not edit.
import { component$, useSignal } from '@qwik.dev/core';

export const EventForm = component$((props) => {
	const text = useSignal(props.initial);
	const checked = useSignal(false);
	const writes = useSignal(0);
	return (
		<form
			data-scenario="s3"
			onClick$={async (event) => {
				if (event.target.dataset.action === 'submit') {
					await props.onTrace$('bubble', { source: 'form' }, event);
				}
			}}
		>
			<input
				data-action="text"
				value={text.value}
				onInput$={async (event, element) => {
					text.value = element.value;
					await props.onTrace$('text', { value: element.value }, event);
				}}
			/>
			<input
				type="checkbox"
				data-action="checked"
				checked={checked.value}
				onChange$={async (event, element) => {
					checked.value = element.checked;
					await props.onTrace$('checked', { checked: element.checked }, event);
				}}
			/>
			<button
				type="button"
				data-action="submit"
				onClick$={async (event) => {
					event.preventDefault();
					writes.value = 1;
					writes.value = 2;
					await props.onTrace$(
						'submit',
						{ text: text.value, checked: checked.value, writes: 2 },
						event,
					);
				}}
			>
				submit
			</button>
			<output data-writes="true">{writes.value}</output>
			<span data-callback-marker="present" />
		</form>
	);
});
