// @generated by @frameless/qwik; do not edit.
import { $, component$, useComputed$, useSignal, useStore } from '@qwik.dev/core';

export const KeyedTodo = component$((props) => {
	const todos = useStore(props.seed.map((todo) => ({ ...todo })));
	const draft = useSignal('');
	const next = useSignal(3);
	const complete = useComputed$(() => todos.filter((todo) => todo.done).length);
	return (
		<section data-scenario="s2">
			<p data-count="complete">
				{complete.value}/{todos.length}
			</p>
			<input
				data-action="new"
				value={draft.value}
				onInput$={$((event, element) => {
					draft.value = element.value;
				})}
			/>
			<button
				data-action="add"
				onClick$={$(async (event) => {
					const item = { id: `c${next.value}`, title: draft.value, done: false };
					next.value += 1;
					todos.splice(0, todos.length, ...todos.concat(item));
					draft.value = '';
					await props.onTrace$('add', { id: item.id, title: item.title }, event);
				})}
			>
				add
			</button>
			{todos.length === 0 ? <p data-empty="true">empty</p> : null}
			<ul>
				{todos.map((todo) => (
					<li key={todo.id} data-oracle-row-key={todo.id}>
						<input
							data-edit={todo.id}
							value={todo.title}
							onInput$={$(async (event, element) => {
								const title = element.value;
								const alias = todos.find((item) => item.id === todo.id);
								alias.title = title;
								todos.splice(0, todos.length, ...todos.slice());
								await props.onTrace$('edit', { id: todo.id, title }, event);
							})}
						/>
						<input
							type="checkbox"
							data-toggle={todo.id}
							checked={todo.done}
							onChange$={$(async (event, element) => {
								const checked = element.checked;
								const copy = todos.slice();
								const alias = copy.find((item) => item.id === todo.id);
								alias.done = checked;
								todos.splice(0, todos.length, ...copy);
								await props.onTrace$('toggle', { id: todo.id, checked }, event);
							})}
						/>
						<button
							data-remove={todo.id}
							onClick$={$(async (event) => {
								todos.splice(
									0,
									todos.length,
									...todos.filter((item) => item.id !== todo.id),
								);
								await props.onTrace$('remove', { id: todo.id }, event);
							})}
						>
							remove
						</button>
					</li>
				))}
			</ul>
			<button
				data-action="reorder"
				onClick$={$(async (event) => {
					const order = todos.slice().reverse();
					todos.splice(0, todos.length, ...order);
					await props.onTrace$('reorder', { order: order.map((todo) => todo.id) }, event);
				})}
			>
				reorder
			</button>
			<button
				data-action="clear"
				onClick$={$(async (event) => {
					const count = todos.length;
					todos.splice(0, todos.length);
					await props.onTrace$('clear', { count }, event);
				})}
			>
				clear
			</button>
		</section>
	);
});
