// @generated by @frameless/qwik; do not edit.
import { $, component$, useComputed$, useSignal, useTask$ } from '@qwik.dev/core';

export const RenderOnce = component$((props) => {
	useTask$(async () => {
		await props.onTrace$('setup', { runs: 1 });
	});
	const count = useSignal(1);
	const prefix = useSignal(() => `${props.label}:`);
	const derived = useComputed$(() => `${prefix.value}${count.value * props.multiplier}`);
	return (
		<div data-s1-root="">
			{!props.visible ? (
				<p data-branch="hidden">hidden</p>
			) : (
				<section data-scenario="s1">
					<output data-value="derived">{derived.value}</output>
					<button
						data-action="increment"
						onClick$={$(async () => {
							count.value += 1;
							await props.onTrace$('change', { count: count.value });
						})}
					>
						increment
					</button>
				</section>
			)}
		</div>
	);
});
