// @generated by @frameless/qwik; do not edit.
import { component$, useComputed$, useSignal, useStore } from '@qwik.dev/core';

export const WhitespaceBoard = component$((props) => {
	const done = useSignal(1);
	const unit = useSignal('px');
	const note = useSignal(props.label);
	const joiner = useSignal('|');
	const rows = useStore(props.seed.slice());
	const total = useComputed$(() => rows.length);
	return (
		<section data-scenario="s6">
			<p data-ratio="true">
				{done.value}/{total.value}
			</p>
			<p data-glue="true">
				start{done.value}
				{unit.value}end
			</p>
			<p data-wrap="true">[{note.value}]</p>
			<p data-mixed="true">
				a<b data-emph="true">{unit.value}</b>z
			</p>
			<p data-static="true">one two three</p>
			<ul data-lines="true">
				{rows.map((row) => (
					<li key={row.id} data-oracle-text-key={row.id}>
						<span data-pair={row.id}>
							{row.left}
							{joiner.value}
							{row.right}
						</span>
						<button
							data-widen={row.id}
							onClick$={async (event) => {
								const next = ` ${row.id} `;
								joiner.value = next;
								await props.onTrace$('widen', { id: row.id, joiner: next }, event);
							}}
						>
							widen
						</button>
					</li>
				))}
			</ul>
			<button
				data-action="tick"
				onClick$={async (event) => {
					done.value += 1;
					unit.value = 'em';
					await props.onTrace$('tick', { done: done.value, unit: unit.value }, event);
				}}
			>
				tick
			</button>
			<button
				data-action="pad"
				onClick$={async (event) => {
					const padded = ` ${note.value} `;
					note.value = padded;
					await props.onTrace$('pad', { note: padded }, event);
				}}
			>
				pad
			</button>
		</section>
	);
});
