// @generated by @frameless/react; do not edit.
function Frame({ children }) {
	return <section data-frame="">{children}</section>;
}

export function SlotPage() {
	return (
		<Frame>
			<strong data-projected-node="">Projected composition</strong>
		</Frame>
	);
}
