// @generated by @frameless/react; do not edit.
import { createContext, useContext, useState, useSyncExternalStore } from 'react';

function createCompositionSharedStore() {
	let count = 0;
	let countVersion = 0;
	let countSnapshot = count;
	let countSnapshotVersion = countVersion;
	const countListeners = new Set();
	let history = 'seed';
	let historyVersion = 0;
	let historySnapshot = history;
	let historySnapshotVersion = historyVersion;
	const historyListeners = new Set();
	let audit = 'pending';
	let auditVersion = 0;
	let auditSnapshot = audit;
	let auditSnapshotVersion = auditVersion;
	const auditListeners = new Set();
	const writeCount = (nextCount, changed) => {
		if (Object.is(count, nextCount)) {
			return;
		}
		count = nextCount;
		countVersion++;
		changed.add('count');
	};
	const writeHistory = (nextHistory, changed) => {
		if (Object.is(history, nextHistory)) {
			return;
		}
		history = nextHistory;
		historyVersion++;
		changed.add('history');
	};
	const writeAudit = (nextAudit, changed) => {
		if (Object.is(audit, nextAudit)) {
			return;
		}
		audit = nextAudit;
		auditVersion++;
		changed.add('audit');
	};
	return {
		getCount: () => {
			if (countSnapshotVersion !== countVersion) {
				countSnapshot = count;
				countSnapshotVersion = countVersion;
			}
			return countSnapshot;
		},
		subscribeCount: (listener) => {
			countListeners.add(listener);
			return () => {
				countListeners.delete(listener);
			};
		},
		getHistory: () => {
			if (historySnapshotVersion !== historyVersion) {
				historySnapshot = history;
				historySnapshotVersion = historyVersion;
			}
			return historySnapshot;
		},
		subscribeHistory: (listener) => {
			historyListeners.add(listener);
			return () => {
				historyListeners.delete(listener);
			};
		},
		getAudit: () => {
			if (auditSnapshotVersion !== auditVersion) {
				auditSnapshot = audit;
				auditSnapshotVersion = auditVersion;
			}
			return auditSnapshot;
		},
		subscribeAudit: (listener) => {
			auditListeners.add(listener);
			return () => {
				auditListeners.delete(listener);
			};
		},
		advance() {
			const changed = new Set();
			const initialCount = count;
			const initialHistory = history;
			const initialAudit = audit;
			writeHistory(`${history}:${count}`, changed);
			writeCount(count + 1, changed);
			writeAudit(`${history}|${count}`, changed);
			for (const changedCell of changed) {
				if (changedCell === 'count' && !Object.is(initialCount, count)) {
					for (const listener of countListeners) listener();
				}
				if (changedCell === 'history' && !Object.is(initialHistory, history)) {
					for (const listener2 of historyListeners) listener2();
				}
				if (changedCell === 'audit' && !Object.is(initialAudit, audit)) {
					for (const listener3 of auditListeners) listener3();
				}
			}
		},
		append() {
			const changed2 = new Set();
			const initialCount2 = count;
			const initialHistory2 = history;
			const initialAudit2 = audit;
			writeHistory(`${history}!`, changed2);
			for (const changedCell2 of changed2) {
				if (changedCell2 === 'count' && !Object.is(initialCount2, count)) {
					for (const listener4 of countListeners) listener4();
				}
				if (changedCell2 === 'history' && !Object.is(initialHistory2, history)) {
					for (const listener5 of historyListeners) listener5();
				}
				if (changedCell2 === 'audit' && !Object.is(initialAudit2, audit)) {
					for (const listener6 of auditListeners) listener6();
				}
			}
		},
	};
}

const CompositionSharedContext = createContext(null);

export function CompositionSharedProvider({ children }) {
	const [store] = useState(createCompositionSharedStore);
	return <CompositionSharedContext value={store}>{children}</CompositionSharedContext>;
}

const subscribeCompositionSharedToNothing = () => () => {};

const getCompositionSharedNothing = () => 0;

function useCompositionShared(cell) {
	const store = useContext(CompositionSharedContext);
	if (store === null) {
		throw new Error('useCompositionShared is missing its provider');
	}
	const value = useSyncExternalStore(
		cell === 'count'
			? store.subscribeCount
			: cell === 'history'
				? store.subscribeHistory
				: cell === 'audit'
					? store.subscribeAudit
					: subscribeCompositionSharedToNothing,
		cell === 'count'
			? store.getCount
			: cell === 'history'
				? store.getHistory
				: cell === 'audit'
					? store.getAudit
					: getCompositionSharedNothing,
		cell === 'count'
			? store.getCount
			: cell === 'history'
				? store.getHistory
				: cell === 'audit'
					? store.getAudit
					: getCompositionSharedNothing,
	);
	if (cell === 'count') {
		return value;
	}
	if (cell === 'history') {
		return value;
	}
	if (cell === 'audit') {
		return value;
	}
	return store;
}

function Incrementer() {
	const shared = {
		advance: useCompositionShared('store').advance,
		append: useCompositionShared('store').append,
	};
	return (
		<>
			<button
				data-action="advance-shared"
				onClick={() => {
					shared.advance();
				}}
			>
				Advance
			</button>
			<button
				data-action="append-shared"
				onClick={() => {
					shared.append();
				}}
			>
				Append
			</button>
		</>
	);
}

function Reader() {
	const shared = {
		history: useCompositionShared('history'),
		count: useCompositionShared('count'),
	};
	return <output data-shared-reader="">{`${shared.history}|${shared.count}`}</output>;
}

function SharedAudit() {
	const shared = { audit: useCompositionShared('audit') };
	return <output data-shared-audit="">{shared.audit}</output>;
}

export function SharedParticipants() {
	return (
		<>
			<Incrementer />
			<Reader />
			<SharedAudit />
		</>
	);
}
