// @generated by @frameless/react; do not edit.
import { useCallback, useRef } from 'react';

function FocusField({ ref }) {
	const attachHost = useCallback(
		(node2) => {
			ref.current = node2;
			const cleanup = ((node) => {
				const localState = node.parentElement?.querySelector('[data-handle-state]');
				let witness = document.querySelector('body > [data-handle-witness]');
				if (witness === null) {
					witness = document.createElement('section');
					witness.dataset.handleWitness = '';
					witness.innerHTML = '<output data-handle-state></output>';
					document.body.append(witness);
				}
				if (localState !== null) localState.textContent = 'set';
				const externalState = witness.querySelector('[data-handle-state]');
				if (externalState !== null) externalState.textContent = 'set';
				return () => {
					if (localState !== null) localState.textContent = 'cleared';
					if (externalState !== null) externalState.textContent = 'cleared';
				};
			})(node2);
			return () => {
				if (typeof cleanup === 'function') {
					cleanup();
				}
				ref.current = null;
			};
		},
		[ref],
	);
	return <input data-focus-target="" ref={attachHost} />;
}

export function FocusPage() {
	const input = useRef(null);
	return (
		<section data-handle-witness="">
			<output data-handle-state="" />
			<FocusField ref={input} />
			<button
				data-action="focus-composed"
				onClick={() => {
					if (input.current !== null) {
						input.current.focus();
					}
				}}
			>
				Focus
			</button>
		</section>
	);
}
