// @generated by @frameless/react; do not edit.
import { useCallback, useState } from 'react';
export function CleanupPage() {
	const [behaviorInput, setBehaviorInput] = useState('one');
	const attachHost = useCallback(
		(node2) => {
			const cleanup = ((node) => {
				let witness = document.querySelector('body > [data-composition-witness]');
				if (witness === null) {
					witness = document.createElement('section');
					witness.dataset.compositionWitness = '';
					witness.innerHTML =
						'<output data-composition-cleanup></output><output data-behavior-log></output>';
					document.body.append(witness);
				}
				const localState = node.querySelector('[data-composition-cleanup]');
				const externalState = witness.querySelector('[data-composition-cleanup]');
				const localLog = node.querySelector('[data-behavior-log]');
				const externalLog = witness.querySelector('[data-behavior-log]');
				const append = (entries) => {
					const prior = externalLog?.textContent ?? '';
					const next = prior === '' ? entries.join('|') : `${prior}|${entries.join('|')}`;
					if (localLog !== null) localLog.textContent = next;
					if (externalLog !== null) externalLog.textContent = next;
				};
				if (localState !== null) localState.textContent = 'attached';
				if (externalState !== null) externalState.textContent = 'attached';
				append([`install:A:${behaviorInput}`, `install:B:${behaviorInput}`]);
				return () => {
					append([`cleanup:B:${behaviorInput}`, `cleanup:A:${behaviorInput}`]);
					if (localState !== null) localState.textContent = 'cleaned';
					if (externalState !== null) externalState.textContent = 'cleaned';
				};
			})(node2);
			return () => {
				if (typeof cleanup === 'function') {
					cleanup();
				}
			};
		},
		[behaviorInput],
	);
	return (
		<section data-composition-witness="" ref={attachHost}>
			<output data-composition-cleanup="" />
			<output data-behavior-log="" />
			<button
				data-action="change-behavior-input"
				onClick={() => {
					const nextBehaviorInput = 'two';
					setBehaviorInput(nextBehaviorInput);
				}}
			>
				Change behavior input
			</button>
		</section>
	);
}
