// @generated by @frameless/react; do not edit.
import { useState } from 'react';

function PropsReader({ propsValueSharedValue }) {
	const shared = { value: propsValueSharedValue };
	return <output data-tier-props="">{shared.value}</output>;
}

export function PropsPage() {
	const [propsValueSharedValue] = useState(5);
	return <PropsReader propsValueSharedValue={propsValueSharedValue} />;
}
