// @generated by @frameless/react; do not edit.
import { createContext, useContext } from 'react';

const ScalarFanoutContext = createContext(null);

function useScalarFanout() {
	const value = useContext(ScalarFanoutContext);
	if (value === null) {
		throw new Error('useScalarFanout is missing its provider');
	}
	return value;
}

export function ScalarFanoutProvider({ children }) {
	return <ScalarFanoutContext value={6}>{children}</ScalarFanoutContext>;
}

function ScalarLeft() {
	const shared = { value: useScalarFanout() };
	return <output data-tier-scalar="left">{shared.value}</output>;
}

function ScalarRight() {
	const shared = { value: useScalarFanout() };
	return <output data-tier-scalar="right">{shared.value}</output>;
}

function ScalarLeftBranch() {
	return <ScalarLeft />;
}

function ScalarRightBranch() {
	return <ScalarRight />;
}

export function ScalarPage() {
	return (
		<>
			<ScalarLeftBranch />
			<ScalarRightBranch />
		</>
	);
}
