// @generated by @frameless/react; do not edit.
import { useSyncExternalStore } from 'react';

function createPageLedgerStore() {
	let count = 0;
	let countVersion = 0;
	let countSnapshot = count;
	let countSnapshotVersion = countVersion;
	const countListeners = new Set();
	const writeCount = (nextCount, changed) => {
		if (Object.is(count, nextCount)) {
			return;
		}
		count = nextCount;
		countVersion++;
		changed.add('count');
	};
	return {
		getCount: () => {
			if (countSnapshotVersion !== countVersion) {
				countSnapshot = count;
				countSnapshotVersion = countVersion;
			}
			return countSnapshot;
		},
		subscribeCount: (listener) => {
			countListeners.add(listener);
			return () => {
				countListeners.delete(listener);
			};
		},
		increment() {
			const changed = new Set();
			const initialCount = count;
			writeCount(count + 1, changed);
			for (const changedCell of changed) {
				if (changedCell === 'count' && !Object.is(initialCount, count)) {
					for (const listener of countListeners) listener();
				}
			}
		},
	};
}

const pageLedgerStore = createPageLedgerStore();

const subscribePageLedgerToNothing = () => () => {};

const getPageLedgerNothing = () => 0;

function usePageLedger(cell) {
	const store = pageLedgerStore;
	const value = useSyncExternalStore(
		cell === 'count' ? store.subscribeCount : subscribePageLedgerToNothing,
		cell === 'count' ? store.getCount : getPageLedgerNothing,
		cell === 'count' ? store.getCount : getPageLedgerNothing,
	);
	if (cell === 'count') {
		return value;
	}
	return store;
}

export function PageLedger() {
	const ledger = { count: usePageLedger('count'), increment: usePageLedger('store').increment };
	return (
		<>
			<button
				data-action="increment-page-tier"
				onClick={() => {
					ledger.increment();
				}}
			>
				Increment
			</button>
			<output data-tier-page="">{ledger.count}</output>
		</>
	);
}
