// @generated by @frameless/react; do not edit.
export function Panel({ label, children }) {
	return (
		<section data-panel="">
			<h2 data-panel-label="">{label}</h2>
			<div data-panel-body="">{children}</div>
		</section>
	);
}
