// @generated by @frameless/react; do not edit.
import { Panel } from './M1-panel.jsx';

export function ComposedPage() {
	return (
		<Panel label={'Composed'}>
			<p data-panel-copy="">Projected across the module boundary</p>
		</Panel>
	);
}
