// @generated by @frameless/qwik; do not edit.
import { Slot, component$ } from '@qwik.dev/core';

export const Panel = component$((props) => {
	return (
		<section data-panel>
			<h2 data-panel-label>{props.label}</h2>
			<div data-panel-body>
				<Slot />
			</div>
		</section>
	);
});
