// @generated by @frameless/qwik; do not edit.
import { component$ } from '@qwik.dev/core';
import { Panel } from './M1-panel.jsx';

export const ComposedPage = component$(() => {
	return (
		<Panel label={'Composed'}>
			<p data-panel-copy>Projected across the module boundary</p>
		</Panel>
	);
});
