import { mkdir, mkdtemp, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'pathe';
import { afterEach, describe, expect, test } from 'vitest';
import {
	checkGeneratedFiles,
	checkSources,
	discoverGeneratedFiles,
	SOLID_GATE_POLICIES,
} from '../src/gate/index.ts';

const temporaryRoots: string[] = [];
afterEach(async () =>
	Promise.all(temporaryRoots.splice(0).map((root) => rm(root, { recursive: true, force: true }))),
);

const valid = `import { createSignal, untrack, For, Show } from 'solid-js';
import { createStore, reconcile } from 'solid-js/store';
export function Mutant(props) {
  const [items, setItems] = createStore(untrack(() => props.items));
  const [value, setValue] = createSignal(0);
  const label = () => props.label;
  return <section><Show when={props.visible}><span>{label()}</span></Show><input value={value()} attr:value={value()} onInput={(event) => setValue(Number(event.currentTarget.value))} /><ul><For each={items}>{(item) => <li>{item.id}<button onClick={() => setItems(reconcile([], { key: 'id' }))}>clear</button></li>}</For></ul></section>;
}`;

async function policies(source: string): Promise<string[]> {
	const result = await checkSources([{ file: 'generated/Mutant.jsx', source }]);
	expect(result.violations.every((entry) => /^T003 ruling \d+$/.test(entry.dossierRef))).toBe(
		true,
	);
	return result.violations.map((entry) => entry.policy);
}

describe('Solid dossier gate', () => {
	test('publishes a dossier reference on every policy', () => {
		expect(
			SOLID_GATE_POLICIES.every((policy) => /^T003 ruling \d+$/.test(policy.dossierRef)),
		).toBe(true);
	});

	test('discovers and accepts every checked-in generated component', async () => {
		expect(await discoverGeneratedFiles()).toEqual([
			'generated/S1.jsx',
			'generated/S2.jsx',
			'generated/S3.jsx',
		]);
		const result = await checkGeneratedFiles();
		expect(result.violations, JSON.stringify(result.violations, null, 2)).toEqual([]);
		for (const file of result.files)
			expect(await readFile(resolve(import.meta.dirname, '..', file), 'utf8')).toContain(
				'@generated by @frameless/solid',
			);
	});

	const mutationCases = [
		['disable directive', `/* eslint-disable */\n${valid}`, 'eslint-directive'],
		['foreign import', `import value from 'elsewhere';\n${valid}`, 'undisclosed-import'],
		[
			'require',
			valid.replace('const label', "require('elsewhere');\n  const label"),
			'undisclosed-import',
		],
		[
			'dynamic import',
			valid.replace('const label', "import('elsewhere');\n  const label"),
			'undisclosed-import',
		],
		[
			'createMemo import',
			valid.replace('createSignal,', 'createMemo, createSignal,'),
			'solid-import-allowlist',
		],
		[
			'object signal',
			valid.replace('createSignal(0)', 'createSignal({ value: 0 })'),
			'cell-type',
		],
		[
			'lazy object signal',
			valid.replace('createSignal(0)', 'createSignal(() => ({ value: 0 }))'),
			'cell-type',
		],
		[
			'untrack-wrapped array signal',
			valid.replace('createSignal(0)', 'createSignal(untrack(() => []))'),
			'cell-type',
		],
		[
			'nested helper with malformed signal write',
			valid.replace(
				'onInput={(event) => setValue(Number(event.currentTarget.value))}',
				'onInput={() => { const write = () => setValue(); write(); }}',
			),
			'signal-write-shape',
		],
		[
			'nested helper with raw store write',
			valid.replace(
				"onClick={() => setItems(reconcile([], { key: 'id' }))}",
				'onClick={() => { const actions = { write: () => setItems([]) }; actions.write(); }}',
			),
			'store-write-shape',
		],
		[
			'structural ternary',
			valid.replace('<section>', '<section>{props.visible ? <i /> : <b />}'),
			'structural-ternary',
		],
		['Show without when', valid.replace(' when={props.visible}', ''), 'show-two-arm'],
		[
			'Show with empty-fragment fallback',
			valid.replace(' when={props.visible}', ' when={props.visible} fallback={<></>}'),
			'show-two-arm',
		],
		[
			'duplicated Show arms',
			valid.replace(
				'<Show when={props.visible}><span>{label()}</span></Show>',
				'<Show when={props.visible} fallback={<ul><For each={items}>{(item) => <li>{item.id}</li>}</For></ul>}><span>{label()}</span><ul><For each={items}>{(item) => <li>{item.id}</li>}</For></ul></Show>',
			),
			'show-two-arm',
		],
		['missing attr value', valid.replace(' attr:value={value()}', ''), 'controlled-input'],
		[
			'React text event',
			valid.replace('onInput={(event)', 'onChange={(event)'),
			'controlled-input',
		],
		[
			'collection accessor in row',
			valid.replace('{item.id}<button', '{items() && item.id}<button'),
			'collection-accessor-in-row',
		],
		[
			'stop propagation',
			valid.replace(
				'onInput={(event) => setValue(Number(event.currentTarget.value))}',
				'onInput={(event) => { event.stopPropagation(); setValue(Number(event.currentTarget.value)); }}',
			),
			'stop-propagation',
		],
		[
			'props destructure',
			valid.replace(
				'const [items',
				'const { items: frozen } = props; frozen;\n  const [items',
			),
			'props-destructure',
		],
		[
			'raw prop initializer',
			valid.replace('untrack(() => props.items)', 'props.items'),
			'untrack-once-capture',
		],
		[
			'untrack capture with a parameter',
			valid.replace('untrack(() => props.items)', 'untrack((tracked) => props.items)'),
			'untrack-capture-shape',
		],
		['wrong reconcile key', valid.replace("key: 'id'", "key: 'missingKey'"), 'reconcile-key'],
		[
			'React className',
			valid.replace('<section>', '<section className="bad">'),
			'react-specific-props',
		],
		[
			'destructured component param',
			valid.replace('function Mutant(props)', 'function Mutant({ items })'),
			'component-shape',
		],
		[
			'For index accessor',
			valid.replace('(item) =>', '(item, index) =>').replace('{item.id}', '{index()}'),
			'index-accessor',
		],
		[
			'map render',
			valid.replace(
				"<For each={items}>{(item) => <li>{item.id}<button onClick={() => setItems(reconcile([], { key: 'id' }))}>clear</button></li>}</For>",
				'{items.map((item) => <li>{item.id}</li>)}',
			),
			'map-render',
		],
		[
			'setup setter',
			valid.replace('const label', 'setValue(1);\n  const label'),
			'render-phase-setter',
		],
		[
			'setup helper setter',
			valid.replace(
				'const label',
				'const update = () => setValue(1); update();\n  const label',
			),
			'render-phase-setter',
		],
		[
			'inline-object setter call',
			valid.replace('const label', '({ run: setValue }).run(1);\n  const label'),
			'render-phase-setter',
		],
		[
			'effect alias',
			valid
				.replace('createSignal,', 'createEffect as side, createSignal,')
				.replace('const label', 'side(() => props.label);\n  const label'),
			'render-phase-effect',
		],
		[
			'wrong preventDefault object',
			valid.replace(
				'onInput={(event) => setValue(Number(event.currentTarget.value))}',
				'onInput={(event) => { props.preventDefault(); setValue(Number(event.currentTarget.value)); }}',
			),
			'prevent-default-event',
		],
		[
			'leaf event target',
			valid.replace('event.currentTarget.value', 'event.target.value'),
			'leaf-event-target',
		],
		[
			'unused binding',
			valid.replace('const label', 'const unused = 1;\n  const label'),
			'eslint:no-unused-vars',
		],
		[
			'dead expression',
			valid.replace('const label', 'props.label;\n  const label'),
			'eslint:no-unused-expressions',
		],
		[
			'unreachable statement',
			valid.replace('const label', 'return null;\n  props.label;\n  const label'),
			'eslint:no-unreachable',
		],
	] as const;

	test.each(mutationCases)('rejects the %s bypass mutation', async (_name, source, policy) => {
		expect(await policies(source)).toContain(policy);
	});

	test('has a syntactically valid mutation for every published policy', () => {
		const covered = new Set(mutationCases.map((entry) => entry[2]));
		expect(
			SOLID_GATE_POLICIES.map((policy) => policy.id).filter((id) => !covered.has(id)),
		).toEqual([]);
	});

	test('eslint-plugin-solid recommended is active', async () => {
		expect(await policies(valid.replace('<section>', '<section className="bad">'))).toContain(
			'eslint:solid/no-react-specific-props',
		);
	});

	test('a newly generated file is discovered and rejected end to end', async () => {
		const root = await realpath(await mkdtemp(resolve(tmpdir(), 'frameless-solid-gate-')));
		temporaryRoots.push(root);
		await mkdir(resolve(root, 'generated'));
		await writeFile(
			resolve(root, 'generated/New.jsx'),
			valid.replace('const label', 'setValue(1);\n  const label'),
		);
		const result = await checkGeneratedFiles({ cwd: root });
		expect(result.files).toEqual(['generated/New.jsx']);
		expect(result.violations.map((entry) => entry.policy)).toContain('render-phase-setter');
	});
});
