// @generated by @frameless/angular from SlotPage; do not edit.
import { Component } from '@angular/core';

@Component({
	selector: 'frameless-frame',
	template: `
		<section data-frame><ng-content /></section>
	`,
})
class Frame {}

@Component({
	selector: 'frameless-slot-page',
	imports: [Frame],
	template: `
		<frameless-frame>
			<strong data-projected-node>Projected composition</strong>
		</frameless-frame>
	`,
})
export class SlotPage {}
