// @generated by @frameless/angular from ComposedPage; do not edit.
import { Component } from '@angular/core';
import { Panel } from './M1-panel';

@Component({
	selector: 'frameless-composed-page',
	imports: [Panel],
	template: `
		<frameless-panel [label]="'Composed'">
			<p data-panel-copy>Projected across the module boundary</p>
		</frameless-panel>
	`,
})
export class ComposedPage {}
