import { readdirSync } from 'node:fs';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import type { EnrichedIR } from '@frameless/compiler';
import { resolve } from 'pathe';
import { describe, expect, test } from 'vitest';
import { emit, validateEnrichedIr } from '../src/emitter/index.ts';
import { formatEmitted } from '../src/format-emitted.ts';
import { isUnbuiltEmitted, VUE_UNBUILT_SCENARIOS } from './unbuilt-scenarios.ts';

const packageRoot = resolve(import.meta.dirname, '..');
const compilerGoldenRoot = resolve(packageRoot, '../../compiler/test/goldens');

async function golden(name: string): Promise<EnrichedIR> {
	return JSON.parse(await readFile(resolve(compilerGoldenRoot, name), 'utf8')) as EnrichedIR;
}

/**
 * MUTATION CONSTRUCTOR - see the doc comment on the copy in
 * `packages/frameworks/qwik/test/gate.test.ts`, which instructs a new adapter to
 * copy this block rather than reach for a bare `.replace()`. `String.prototype
 * .replace` promises to return a string, NOT to have matched; a search that
 * misses returns the input unchanged and the test then asserts against a
 * non-mutant, staying green while measuring nothing.
 */
function mutate(source: string, search: string | RegExp, replacement: string): string {
	const mutated = source.replace(search, replacement);
	if (mutated !== source) return mutated;
	throw new Error(
		`mutation did not change the source: ${String(search)} left it byte-identical, ` +
			'so this test would assert against a non-mutant',
	);
}

const generatedRoot = resolve(packageRoot, 'generated');

/** Numeric, so S10 sorts after S9 rather than between S1 and S2. */
function byScenarioNumber(left: string, right: string): number {
	return Number(/(\d+)/.exec(left)![1]) - Number(/(\d+)/.exec(right)![1]);
}

/**
 * THE FIXTURE TABLE IS DERIVED, NOT RE-LITERALLED.
 *
 * This table stopped at `s3-event-form.json`, which meant that when S4 landed NO
 * standing test asserted its emitted bytes equal `formatEmitted(emit(golden))`.
 * That freshness was proved ONCE, by regenerating and diffing by hand; nothing
 * re-proved it per run, so the emitted S4 could have drifted from the emitter
 * that claims to produce it and every lane would still have been green. Four
 * more scenarios are queued, and a table hand-edited per scenario is that same
 * hole four more times.
 *
 * The derivation source is the compiler's ratified golden corpus - `s<n>-*.json`
 * - which is INDEPENDENT of `generated/`: one is the IR this repo agreed to
 * compile, the other is what the emitter actually wrote. The two preconditions
 * below compare them and watch both directions go red.
 */
function scenarioFixtures(goldenDir = compilerGoldenRoot): Array<readonly [string, string]> {
	const table = readdirSync(goldenDir)
		.filter((entry) => /^s\d+-[\w-]+\.json$/.test(entry))
		.sort(byScenarioNumber)
		.map((entry) => [`S${/^s(\d+)-/.exec(entry)![1]}.vue`, entry] as const);
	// THE SUBTRACTION, declared once in ./unbuilt-scenarios.ts, and asserted from
	// the other side by `every UNBUILT scenario really is refused` below.
	const built = table.filter(([file]) => !isUnbuiltEmitted(file));
	// Fail LOUD rather than returning []. An empty table would emit zero freshness
	// tests and the file would still report green, which is the one way a derived
	// list could be greener than the literal it replaced.
	if (table.length === 0)
		throw new Error(`no s<n>-*.json scenario goldens found in ${goldenDir}`);
	return built;
}

/** What the emitter actually wrote - the other side of the cross-check. */
function emittedScenarios(directory = generatedRoot): string[] {
	return readdirSync(directory)
		.filter((entry) => /^S\d+\.vue$/.test(entry))
		.sort(byScenarioNumber);
}

const FIXTURES = scenarioFixtures();

async function emitted(file: string): Promise<string> {
	return readFile(resolve(packageRoot, 'generated', file), 'utf8');
}

/**
 * The `<template>` block only. Directive-shaped text assertions have to be scoped
 * to it: the generated header reads `@generated by @frameless/vue`, so a bare
 * `@name`-shaped pattern over the whole file matches the PROVENANCE COMMENT and
 * reports a directive nothing emitted. Throws rather than returning `''` on a
 * source with no template - an empty haystack silently satisfies every
 * `not.toMatch` in the row below.
 */
function templateOf(source: string): string {
	const start = source.indexOf('<template>');
	if (start < 0) throw new Error('emitted source has no <template> block to slice');
	return source.slice(start);
}

describe('Vue 3 emitter', () => {
	/**
	 * THE OTHER HALF OF THE SUBTRACTION, and the reason `./unbuilt-scenarios.ts`
	 * is a declaration rather than a skip list.
	 *
	 * The row above compares two derived inventories and would be perfectly green
	 * if this lane silently stopped emitting a scenario for a reason nobody
	 * recorded - both sides subtract the same names. This row is the other half:
	 * every declared unbuilt scenario is driven through the REAL `emit()` on its
	 * REAL golden, and must throw with the recorded message. It goes red three
	 * ways: the day the limit is lifted and the scenario emits, the day it starts
	 * refusing for a different reason, and the day a listed golden disappears.
	 */
	test('every UNBUILT scenario really is refused, with the recorded message', async () => {
		// A vacuous loop would make this row agree with an empty declaration, which
		// is exactly the greener-than-the-literal failure the derivations guard.
		expect(VUE_UNBUILT_SCENARIOS.length).toBeGreaterThan(0);
		for (const scenario of VUE_UNBUILT_SCENARIOS) {
			const ir = await golden(scenario.golden);
			expect(() => emit(ir), `${scenario.golden} should still be refused`).toThrow(
				scenario.refusalContains,
			);
			// And the artifact really is absent, rather than present and ignored.
			expect(
				readdirSync(generatedRoot).includes(scenario.emitted),
				`${scenario.emitted} must not exist in generated/`,
			).toBe(false);
		}
	});

	/**
	 * THE CONTROL FOR THE ROW ABOVE. Without it, `toThrow(...)` proves only that
	 * SOMETHING throws - a broken `golden()` or an emitter that refused every
	 * input would satisfy it just as well. A BUILT scenario goes through the same
	 * call and must NOT throw.
	 */
	test('CONTROL: a BUILT scenario is not refused by the same call', async () => {
		const firstBuilt = FIXTURES[0];
		expect(firstBuilt).toBeDefined();
		const ir = await golden(firstBuilt![1]);
		expect(() => emit(ir)).not.toThrow();
	});

	test('the derived fixture table is the corpus, and the emitter wrote exactly it', () => {
		// THE FLOOR. Every scenario ratified so far must still be in the derivation.
		// A lower bound, so S5 and later widen it with no edit here, while a golden
		// that silently disappeared is red.
		expect(FIXTURES.map(([file]) => file)).toEqual(
			expect.arrayContaining(['S1.vue', 'S2.vue', 'S3.vue', 'S4.vue']),
		);
		// Two independent readings compared: the goldens this repo agreed to
		// compile, and the files the emitter actually wrote.
		expect(emittedScenarios()).toEqual(FIXTURES.map(([file]) => file));
	});

	/**
	 * CALIBRATION for the DERIVED table. A derived list nobody has watched go red
	 * is not an instrument - and the literal it replaced at least went red when a
	 * golden it named disappeared. Both directions run through the SAME
	 * `scenarioFixtures()` and `emittedScenarios()` the row above calls, against
	 * throwaway roots.
	 */
	test('CALIBRATION: the derived table goes red on a missing and on an extra file', async () => {
		const files = FIXTURES.map(([file]) => file);
		const temporary = await mkdtemp(resolve(tmpdir(), 'frameless-vue-fixtures-'));
		try {
			const goldens = resolve(temporary, 'goldens');
			const generated = resolve(temporary, 'generated');
			await mkdir(goldens);
			await mkdir(generated);
			for (const entry of readdirSync(compilerGoldenRoot))
				await writeFile(resolve(goldens, entry), '{}');
			expect(scenarioFixtures(goldens)).toEqual(FIXTURES);
			// MISSING, on the emitted side: one file short of the derived table.
			for (const file of files.slice(0, -1)) await writeFile(resolve(generated, file), '//\n');
			expect(emittedScenarios(generated)).not.toEqual(files);
			await writeFile(resolve(generated, files.at(-1)!), '//\n');
			expect(emittedScenarios(generated)).toEqual(files);
			// EXTRA, on the emitted side: a stray scenario no golden declares.
			await writeFile(resolve(generated, 'S99.vue'), '//\n');
			expect(emittedScenarios(generated)).not.toEqual(files);
			// And both directions on the DERIVATION side, so a golden that vanished
			// or appeared cannot pass unnoticed either.
			await rm(resolve(goldens, FIXTURES[0]![1]));
			expect(scenarioFixtures(goldens)).not.toEqual(FIXTURES);
			await writeFile(resolve(goldens, 's99-planted.json'), '{}');
			expect(scenarioFixtures(goldens).map(([file]) => file)).toContain('S99.vue');
			// The degenerate case the throw exists for: an empty derivation must NOT
			// quietly agree with an empty directory.
			await rm(goldens, { recursive: true, force: true });
			await mkdir(goldens);
			expect(() => scenarioFixtures(goldens)).toThrow(/no s<n>-\*\.json scenario goldens/);
		} finally {
			await rm(temporary, { recursive: true, force: true });
		}
	});

	test('CALIBRATION: the mutation constructor is loud on a non-mutant', async () => {
		const source = await emitted('S1.vue');
		expect(() => mutate(source, 'text that is not in the emitted S1', 'x')).toThrow(
			/did not change the source/,
		);
		expect(source).toContain('computed(');
		expect(() => mutate(source, 'computed(', 'computed(')).toThrow(
			/did not change the source/,
		);
	});

	// GOLDEN FRESHNESS. Byte equality against what the emitter produces right now,
	// so a checked-in artifact can never drift from the emitter that claims to
	// produce it.
	for (const [file, artifact] of FIXTURES)
		test(`${file} is byte-identical to a fresh emission`, async () => {
			const fresh = formatEmitted(emit(await golden(artifact)));
			const checkedIn = await emitted(file);
			expect(fresh).toBe(checkedIn);
			// CALIBRATION for the comparison itself: a byte-equality assertion that
			// has only ever been shown to pass is not evidence it can fail.
			expect(mutate(fresh, 'do not edit.', 'do not edit!')).not.toBe(checkedIn);
		});

	/**
	 * STEP 1.5 FLIPPED THE `lang` ARM OF THIS ROW AND KEPT ITS SHAPE. It used to
	 * read `<script setup>` plus `not.toContain('lang=')`; the attribute is now
	 * REQUIRED.
	 *
	 * WHAT THIS ROW DENIES HAS NARROWED, AND THE NARROWING IS THE POINT. It used
	 * to read "NO PRINTED TYPE", justified by defineProps keeping its ARRAY form.
	 * That is no longer true and the claim is corrected rather than deleted: prop
	 * types ARE now printed, through Vue's RUNTIME DECLARATION channel, as
	 * ordinary JavaScript values. What stays denied is TYPESCRIPT TYPE SYNTAX in
	 * the emitted script - `defineProps<T>()` and `withDefaults()` - which Gate 5
	 * refuses because the type-argument form makes Vue infer runtime prop types,
	 * and the `Boolean` it would infer for `visible` flips an empty-string binding
	 * from falsy to truthy. That denial is unchanged and is asserted below; the
	 * one that rested on "the IR carries no type" is gone, because the IR carries
	 * one.
	 */
	test('emits an SFC with <script setup lang="ts">, NO TypeScript type syntax, and a default-exported component', async () => {
		for (const [file] of FIXTURES) {
			const source = await emitted(file);
			expect(source).toContain('<script setup lang="ts">\n');
			// The ONLY `lang=` in the file is the one above - a second would mean a
			// normal <script> block appeared alongside the setup block.
			expect(source.match(/lang=/g)).toHaveLength(1);
			// STILL DENIED AT GATE 5, and these two lines are the whole reason the
			// runtime declaration was reachable at all.
			expect(source).not.toContain('defineProps<');
			expect(source).not.toContain('withDefaults(');
			// NO TYPE ANNOTATION REACHES THE SCRIPT. The runtime declaration prints
			// VALUES (`String`, `null`), never a `: T`, so the emitted script stays
			// syntactically JavaScript even under `lang="ts"`.
			expect(source).not.toMatch(/as\s+PropType</);
			expect(source).not.toContain('satisfies ');
			expect(source).toContain('<template>\n');
			// A .vue module is one component exported as the module DEFAULT, so the
			// IR's named ComponentExport cannot be honoured by spelling. The name is
			// carried in the generated header instead - the same divergence the
			// Svelte lane records, and the reason this row exists rather than an
			// `export function <Name>` one.
			expect(source).not.toContain('export ');
		}
		expect(await emitted('S1.vue')).toContain('@frameless/vue from RenderOnce');
		expect(await emitted('S2.vue')).toContain('@frameless/vue from KeyedTodo');
		expect(await emitted('S3.vue')).toContain('@frameless/vue from EventForm');
	});

	/**
	 * THE DECISION THIS BOARD'S T005 RULED AND T006 ADOPTED, asserted here so a
	 * silent revert is loud.
	 *
	 * `docs/emitter-idiom-policy.md` worked example 2a rules the VALUED `v-bind`
	 * and `v-on` shorthands **sugar** on all six gates. Worked example 2b - the
	 * `v-slot` shorthand `#header` - split off and is DENIED, and the `.prop`
	 * shorthand and every `v-on` modifier were never covered at all. Each of those
	 * three refusals gets its own line below, because they are separate rulings
	 * that happen to share a syntax family.
	 *
	 * The spelling is worth pinning HERE and not only in the gate because T005
	 * measured that the two spellings are behaviourally identical - so no
	 * behavioural check anywhere in this repo can tell them apart, and a text
	 * assertion is the only instrument that can.
	 */
	test('emits the VALUED shorthands only, with no longhand, modifier or v-slot', async () => {
		for (const [file] of FIXTURES) {
			const source = await emitted(file);
			// SCOPED TO THE TEMPLATE, and the scoping is a correction rather than a
			// convenience: the generated header reads "@generated by @frameless/vue",
			// so a bare shorthand-shaped pattern over the whole file matches the
			// PROVENANCE COMMENT and reports a directive that is not there.
			const template = templateOf(source);
			// Worked example 2a, adopted: no longhand `v-bind:`/`v-on:` survives.
			expect(template, file).not.toMatch(/v-(?:bind|on):/);
			// Worked example 2b, DENIED: no `v-slot`, in either spelling.
			expect(source, file).not.toContain('v-slot');
			expect(template, file).not.toMatch(/\s#[a-z-]+[=>\s]/);
			// Never covered by any ruling: the `.prop` shorthand, and every modifier
			// on either adopted shorthand.
			expect(template, file).not.toMatch(/\s\.[A-Za-z][\w-]*=/);
			expect(template, file).not.toMatch(/\s[@:][A-Za-z][\w-]*\./);
			// ALWAYS WITH A VALUE. A value-less `:x` is Vue 3.4's same-name shorthand
			// and a value-less `@x` is a syntax error; the emitter interpolates
			// `="..."` unconditionally, and this is what says so out loud. The gate's
			// `directive-carries-value` policy re-reaches it from Vue's own parse tree,
			// which is the instrument that does not depend on a regex being right.
			expect(template, file).not.toMatch(/\s[@:][A-Za-z][\w-]*(?=[\s/>])/);
			expect(source, file).not.toContain('v-model');
			expect(source, file).not.toContain('defineModel');
			expect(source, file).not.toContain('defineEmits');
			expect(source, file).not.toContain('withDefaults');
		}
		expect(await emitted('S1.vue')).toContain('@click="');
		expect(await emitted('S2.vue')).toContain(':key="todo.id"');
		// `v-for` KEEPS its longhand and is not a counterexample: it has no shorthand
		// at all, and `todo in todos` is not a JavaScript expression.
		expect(await emitted('S2.vue')).toContain('v-for="todo in todos"');
		expect(await emitted('S3.vue')).toContain(':checked="checked"');
	});

	/**
	 * CALIBRATION for the row above. Every assertion in it is a `not.toMatch`, and
	 * a `not.toMatch` passes just as happily against a pattern that could never
	 * match anything - or against a haystack the slicer emptied. Both failure modes
	 * are planted against here, out of the REAL emitted S2.
	 */
	test('CALIBRATION: the template slicer and each refused-form pattern go red', async () => {
		const s2 = await emitted('S2.vue');
		// The slicer first: it must keep the directives and drop the header comment,
		// otherwise every pattern below is being run against the wrong string.
		const template = templateOf(s2);
		expect(template).toContain('@click="');
		expect(template).toContain(':key="todo.id"');
		expect(template).not.toContain('@generated');
		expect(() => templateOf('<script setup></script>')).toThrow(/no <template> block/);
		const plant = (search: string, replacement: string): string =>
			templateOf(mutate(s2, search, replacement));
		expect(plant(':key="todo.id"', 'v-bind:key="todo.id"')).toMatch(/v-(?:bind|on):/);
		expect(mutate(s2, ':key="todo.id"', 'v-slot:row')).toContain('v-slot');
		expect(plant(' :key="todo.id"', ' #row=')).toMatch(/\s#[a-z-]+[=>\s]/);
		expect(plant(':key="todo.id"', '.key="todo.id"')).toMatch(/\s\.[A-Za-z][\w-]*=/);
		expect(plant('@input="(event) => draft', '@input.stop="(event) => draft')).toMatch(
			/\s[@:][A-Za-z][\w-]*\./,
		);
		expect(plant(':key="todo.id"', ':key')).toMatch(/\s[@:][A-Za-z][\w-]*(?=[\s/>])/);
	});

	/**
	 * THE SCRIPT/TEMPLATE SPLIT, which is the one thing this emitter does that the
	 * React, Solid and Svelte emitters do not need at all.
	 *
	 * In the TEMPLATE, Vue's own compiler resolves identifiers against
	 * `bindingMetadata` - a ref is unwrapped and a prop is reached - so expressions
	 * are emitted VERBATIM from the IR. In `<script setup>` there is no such
	 * resolution, so a prop becomes `props.x` and a ref becomes `x.value`.
	 */
	test('respells SCRIPT expressions and leaves TEMPLATE expressions verbatim', async () => {
		const s1 = await emitted('S1.vue');
		// Script: prop through the defineProps object, ref through .value. S1 is the
		// corpus's ONLY annotated module, so its declaration takes the RUNTIME
		// OBJECT form; the array form is asserted on an unannotated scenario in the
		// requiredness row below, so both regimes stay pinned.
		expect(s1).toContain(
			"const props = defineProps({ label: { type: String, required: true }, multiplier: { type: Number, required: true }, visible: { type: null, required: true }, onTrace: { type: Function, required: true } });",
		);
		expect(s1).toContain("props.onTrace('setup', { runs: 1 });");
		expect(s1).toContain('const prefix = `${props.label}:`;');
		expect(s1).toContain(
			'const derived = computed(() => `${prefix}${count.value * props.multiplier}`);',
		);
		// `prefix` is an ordinary local, NOT a ref, so it is NOT respelled. Without
		// this row the assertion above would pass for an emitter that suffixed
		// `.value` onto everything.
		expect(s1).not.toContain('prefix.value');
		// Template: the authored spelling, unchanged.
		expect(s1).toContain('v-if="!visible"');
		expect(s1).toContain('{{ derived }}');
		expect(s1).toContain("onTrace('change', { count });");
		expect(s1).not.toContain('props.visible');
	});

	/**
	 * IR-8 REQUIREDNESS, PRINTED. The three regimes this lane now has, plus the
	 * two carve-outs that keep it behaviour-neutral.
	 *
	 * `required` is `!optional` READ FROM SOURCE. The corpus fixture declares all
	 * four props non-optional (`label: string`, not `label?:`), so all four print
	 * `required: true` - and the synthetic arms below flip the flag and watch the
	 * printed value follow, which is what distinguishes "read from the IR" from
	 * "hard-coded true".
	 */
	test('prints {type, required} from IR-8, with booleans mapped to null', async () => {
		const s1 = await emitted('S1.vue');
		// TYPED COMPONENT -> runtime declaration, required from source.
		expect(s1).toContain('label: { type: String, required: true }');
		expect(s1).toContain('multiplier: { type: Number, required: true }');
		expect(s1).toContain('onTrace: { type: Function, required: true }');

		// THE BOOLEAN CARVE-OUT, and it is the strongest denial on this board.
		// `{ visible: Boolean }` makes Vue cast an empty-string binding, flipping
		// `visible=""` from FALSY to TRUTHY and rendering <section> where the
		// array form renders <p>hidden</p> - measured three times at vue@3.5.40.
		// `type: null` normalizes to the array form's exact behaviour, so the
		// REQUIREDNESS still prints while the coercing constructor does not.
		expect(s1).toContain('visible: { type: null, required: true }');
		for (const [file] of FIXTURES) {
			const source = await emitted(file);
			expect(source, `${file} must never print the coercing Boolean constructor`).not.toMatch(
				/\btype: Boolean\b/,
			);
		}

		// UNANNOTATED COMPONENT -> the ARRAY form, byte-for-byte what this lane
		// shipped before IR-8. The other seven scenarios carry no annotation, so
		// this is the control arm proving the object form is TRIGGERED by the IR
		// field rather than printed unconditionally.
		const s2 = await emitted('S2.vue');
		expect(s2).toContain("const props = defineProps(['seed', 'onTrace']);");
		expect(s2).not.toContain('required:');
	});

	/**
	 * THE SAME THREE RULES DRIVEN OFF SYNTHETIC IR, because the corpus can only
	 * ever show ONE combination and a rule proved on one input is a coincidence.
	 */
	test('requiredness, the fail-closed constructor map and the all-or-nothing trigger', async () => {
		const entriesOf = (ir: EnrichedIR) => ir.components[0]!.props.entries as Array<any>;

		// `optional: true` MUST print `required: false`. Without this arm every
		// assertion above is satisfied by an emitter that hard-codes `true`.
		const optionalIr = await golden('s1-render-once.json');
		for (const entry of entriesOf(optionalIr)) entry.optional = true;
		const optionalOut = emit(optionalIr);
		expect(optionalOut).toContain('label: { type: String, required: false }');
		expect(optionalOut).not.toContain('required: true');

		// FAIL CLOSED. A type node the constructor map does not recognise prints
		// `type: null` - Vue's own "do not type-check" - which degrades to the
		// array form's behaviour instead of guessing a constructor.
		const exoticIr = await golden('s1-render-once.json');
		entriesOf(exoticIr)[0]!.type = { type: 'TSTypeReference', typeName: 'Whatever' };
		expect(emit(exoticIr)).toContain('label: { type: null, required: true }');

		// ALL OR NOTHING. One unannotated entry sends the WHOLE component back to
		// the array form, rather than inventing a `required` for the prop whose
		// annotation the compiler never saw.
		const partialIr = await golden('s1-render-once.json');
		delete entriesOf(partialIr)[2]!.type;
		delete entriesOf(partialIr)[2]!.optional;
		const partialOut = emit(partialIr);
		expect(partialOut).toContain("defineProps(['label', 'multiplier', 'visible', 'onTrace'])");
		expect(partialOut).not.toContain('required:');
	});

	test('the script respelling is SCOPE-AWARE, not a name substitution', async () => {
		const s2 = await emitted('S2.vue');
		// `todos` is a ref and is respelled; the arrow parameter `todo` shadows
		// nothing and must not be touched, and `todo.done` is a member property.
		expect(s2).toContain(
			'const complete = computed(() => todos.value.filter((todo) => todo.done).length);',
		);
		expect(s2).toContain('const todos = ref(props.seed.map((todo) => ({ ...todo })));');
		expect(s2).not.toContain('todo.value');
	});

	/**
	 * `ComponentEvaluationPolicy.ordinaryLocals` is `once-per-instance`, and Vue is
	 * the target where that needs NO lowering: `<script setup>` IS the setup body
	 * and runs once per instance. Solid and Svelte both need `untrack` here, so
	 * this row records the absence deliberately rather than leaving it to look like
	 * an oversight.
	 */
	test('emits the once-per-instance policy as plain setup statements, with no untrack', async () => {
		for (const [file] of FIXTURES) {
			const source = await emitted(file);
			expect(source).not.toContain('untrack');
			expect(source).not.toContain('watchEffect');
			expect(source).not.toContain('onMounted');
		}
		expect(await emitted('S3.vue')).toContain('const text = ref(props.initial);');
	});

	test('emits only baseline-safe Vue 3 forms, with no 3.3+ or 3.5+ construct', async () => {
		// IR-4 is DEFERRED and the version corollary is not amended, so every
		// emitted construct must be safe across the Vue 3 line. These are the ones
		// with a version floor above 3.2 that an author would reach for first.
		for (const [file] of FIXTURES) {
			const source = await emitted(file);
			expect(source).not.toContain('defineOptions');
			expect(source).not.toContain('defineSlots');
			expect(source).not.toContain('defineExpose');
			expect(source).not.toContain('useTemplateRef');
			// Reactive props destructure is only non-experimental from 3.5; before
			// that it reads the prop once, and S1's computed reads `multiplier` on
			// every recomputation.
			expect(source).not.toMatch(/const\s*\{[^}]*\}\s*=\s*defineProps/);
		}
	});

	describe('fails closed', () => {
		test('on a declared stopPropagation', async () => {
			const artifact = structuredClone(await golden('s3-event-form.json'));
			const event = artifact.records.events.find((entry) => entry.syncPolicy);
			expect(event).toBeDefined();
			(event as unknown as { syncPolicy: { actions: string[] } }).syncPolicy.actions.push(
				'stopPropagation',
			);
			expect(() => emit(artifact)).toThrow(/fails closed on a declared stopPropagation/);
		});

		test('when a declared unconditional preventDefault is not spelled in the body', async () => {
			const artifact = structuredClone(await golden('s3-event-form.json'));
			const event = artifact.records.events.find((entry) => entry.syncPolicy)!;
			const handler = event.handlers[0]! as { expression: Record<string, any> };
			const body = handler.expression.body as Record<string, any>;
			const before = body.body.length;
			body.body = body.body.filter(
				(statement: Record<string, any>) =>
					statement.expression?.callee?.property?.name !== 'preventDefault',
			);
			expect(body.body.length).toBeLessThan(before);
			expect(() => emit(artifact)).toThrow(/does not spell as a top-level preventDefault/);
		});

		test('on persistence-bearing IR', async () => {
			const artifact = structuredClone(await golden('s1-render-once.json'));
			(artifact.records.persistence as unknown[]).push({ graphNodeId: 'state:count' });
			expect(() => emit(artifact)).toThrow(/does not support persistence-bearing IR/);
		});

		test('on an early component guard, which a .vue module cannot express', async () => {
			const artifact = structuredClone(await golden('s1-render-once.json'));
			(artifact.components[0]!.guards as unknown[]).push({
				id: 'guard:0',
				test: { expression: { type: 'Identifier', name: 'visible' }, reads: [] },
				whenTrue: { kind: 'null' },
			});
			expect(() => emit(artifact)).toThrow(/no lowering for an early component guard/);
		});

		test('on more than one root template node, which would become an SSR fragment', async () => {
			// NOT a stylistic refusal. A multi-root <template> compiles to a Fragment,
			// and a Fragment is server-rendered with `<!--[-->` / `<!--]-->` anchor
			// comments that the e2e lane reads out of the served payload.
			const artifact = structuredClone(await golden('s1-render-once.json'));
			const component = artifact.components[0]! as unknown as Record<string, unknown[]>;
			component.template = [...component.template, structuredClone(component.template[0])];
			expect(() => emit(artifact)).toThrow(/exactly one root template node/);
		});

		test('on a branch arm that is not exactly one host element', async () => {
			const artifact = structuredClone(await golden('s1-render-once.json'));
			let patched = false;
			const stamp = (node: Record<string, any>): void => {
				if (node?.kind === 'branch') {
					node.arms[0].children = [...node.arms[0].children, { kind: 'text', value: 'x' }];
					patched = true;
					return;
				}
				for (const value of Object.values(node ?? {})) {
					if (!value || typeof value !== 'object') continue;
					if (Array.isArray(value)) value.forEach((entry) => stamp(entry));
					else stamp(value as Record<string, any>);
				}
			};
			stamp(artifact.components[0]! as unknown as Record<string, any>);
			expect(patched).toBe(true);
			expect(() => emit(artifact)).toThrow(/branch arm that is not exactly one host element/);
		});

		test('on a keyed repeat construct with no corpus instance', async () => {
			const artifact = structuredClone(await golden('s2-keyed-todo.json'));
			let patched = false;
			const stamp = (node: Record<string, any>): void => {
				if (node?.kind === 'keyed-repeat') {
					node.index = 'position';
					patched = true;
				}
				for (const value of Object.values(node ?? {})) {
					if (!value || typeof value !== 'object') continue;
					if (Array.isArray(value)) value.forEach((entry) => stamp(entry));
					else stamp(value as Record<string, any>);
				}
			};
			stamp(artifact.components[0]! as unknown as Record<string, any>);
			expect(patched).toBe(true);
			expect(() => emit(artifact)).toThrow(/no lowering for an index binding/);
		});

		test('on a component local that would shadow a binding the emitter introduces', async () => {
			const artifact = structuredClone(await golden('s1-render-once.json'));
			const local = artifact.components[0]!.locals[0]! as unknown as Record<string, any>;
			local.names = ['props'];
			expect(() => emit(artifact)).toThrow(/would shadow a binding <script setup>/);
		});

		test('on a declared prop default, which needs the type-argument defineProps form', async () => {
			const artifact = structuredClone(await golden('s1-render-once.json'));
			(artifact.components[0]!.props.entries[0]! as unknown as Record<string, any>)
				.defaultValue = { type: 'Literal', value: 'x', raw: "'x'" };
			expect(() => emit(artifact)).toThrow(/no lowering for a prop default value/);
		});

		test('on a script expression node the rewriter has never been taught', async () => {
			// The rewriter REFUSES rather than guessing. An unknown node type reaching
			// `props.` / `.value` respelling unhandled would produce plausible-looking
			// Vue with a silently unresolved identifier in it.
			const artifact = structuredClone(await golden('s1-render-once.json'));
			const local = artifact.components[0]!.locals.find((entry) => entry.names[0] === 'prefix')!;
			(local as unknown as { initializer: unknown }).initializer = {
				type: 'ClassExpression',
				id: null,
				superClass: null,
				body: { type: 'ClassBody', body: [] },
			};
			expect(() => emit(artifact)).toThrow(/no script lowering for the expression node/);
		});

		test('on an IR whose version discriminator moved', async () => {
			const artifact = structuredClone(await golden('s1-render-once.json'));
			(artifact as { version: string }).version = 'frameless-enriched-ir/3';
			expect(() => validateEnrichedIr(artifact)).toThrow(/frameless-enriched-ir\/2/);
			expect(() => emit(artifact)).toThrow(/frameless-enriched-ir\/2/);
		});

		test('on an unknown semantic field, so a schema addition cannot pass silently', async () => {
			const artifact = structuredClone(await golden('s1-render-once.json'));
			(artifact as unknown as Record<string, unknown>).newField = [];
			expect(() => emit(artifact)).toThrow(/unknown semantic field: newField/);
		});
		/**
		 * THE PROBE ABOVE IS AIMED ONE LEVEL TOO HIGH, AND THIS IS THE ARM THAT
		 * SAYS SO.
		 *
		 * `newField` on `EnrichedIR` was caught by all six lanes from the day it
		 * was written; a key on a NESTED `PropDestructuringEntry` was caught by
		 * exactly two. MEASURED at 127a75b, before T010 tightened this validator:
		 * qwik, svelte, vue AND angular all ACCEPTED the nested key and emitted
		 * BYTE-IDENTICAL output across all eight goldens, while react and solid
		 * threw. That is why the IR-8 plan believed the six validators were
		 * symmetric - the test that would have shown otherwise never looked below
		 * the top level, so "a schema addition cannot pass silently" was true of
		 * one shape of addition and false of the shape actually being added.
		 *
		 * THE CALIBRATION IS THE SECOND ASSERTION, not the first: it pins that the
		 * nested plant is INVISIBLE to the top-level allowlist, because the message
		 * names `PropDestructuringEntry` and never `EnrichedIR`. Delete the nested
		 * check and this test goes red; delete the top-level one and the test above
		 * goes red instead. The two are not substitutes and neither replaced the
		 * other.
		 */
		test('on an unknown field NESTED on a PropDestructuringEntry, which the top-level probe cannot see', async () => {
			const artifact = structuredClone(await golden('s1-render-once.json'));
			const entries = artifact.components[0]!.props.entries as unknown as Array<
				Record<string, unknown>
			>;
			expect(entries.length).toBeGreaterThan(0);
			entries[0]!.newNestedField = 'planted';
			expect(() => emit(artifact)).toThrow(
				/PropDestructuringEntry has unknown semantic field: newNestedField/,
			);
			expect(() => emit(artifact)).not.toThrow(/EnrichedIR has unknown semantic field/);
		});

		/**
		 * IR-8's `type` is ADMITTED, not banned - so the allowlist above must not be
		 * read as "this lane refuses a typed prop". It refuses an UNCHECKED one: a
		 * `type` that is not an AST node is named as loudly as an unknown key, which
		 * is what stops admitting the field from trading one blind spot for another.
		 *
		 * The positive arm is not decoration. `s1-render-once` is the ONLY annotated
		 * fixture in the corpus - four typed entries against fifteen untyped ones
		 * across the other seven goldens - so without it the allowlist entry would
		 * be indistinguishable from a dead one that nothing ever exercises.
		 */
		test('on a malformed IR-8 type annotation, while a well-formed one is admitted', async () => {
			const admitted = structuredClone(await golden('s1-render-once.json'));
			expect(
				admitted.components[0]!.props.entries.filter((entry) => entry.type !== undefined),
			).not.toHaveLength(0);
			expect(() => emit(admitted)).not.toThrow();
			const artifact = structuredClone(await golden('s1-render-once.json'));
			const entries = artifact.components[0]!.props.entries as unknown as Array<
				Record<string, unknown>
			>;
			entries[0]!.type = 'string';
			expect(() => emit(artifact)).toThrow(
				/PropDestructuringEntry has malformed type annotation AST/,
			);
		});

		/**
		 * IR-8 REQUIREDNESS, GUARDED THE SAME WAY AS ITS TYPE - see the fuller doc
		 * comment on the copy in `packages/frameworks/qwik/test/emitter.test.ts`.
		 * MEASURED: `optional` planted on every `PropDestructuringEntry` of all
		 * eight goldens was rejected BY NAME by all six lanes before the field
		 * landed.
		 *
		 * THIS LANE HAS THE MOST TO LOSE BY THE ORPHAN ARM, because it is the one
		 * that PRINTS the flag: an `optional` with no `type` would reach
		 * `propsDeclaration` and be printed straight into a `required:` field, so
		 * requiredness invented downstream would become requiredness asserted in
		 * an emitted artifact. The validator refuses it before any output AST is
		 * built.
		 */
		test('on a malformed or ORPHANED IR-8 requiredness flag, while a well-formed one is admitted', async () => {
			const admitted = structuredClone(await golden('s1-render-once.json'));
			expect(
				admitted.components[0]!.props.entries.filter(
					(entry) => entry.optional !== undefined,
				),
			).not.toHaveLength(0);
			expect(() => emit(admitted)).not.toThrow();

			const malformed = structuredClone(await golden('s1-render-once.json'));
			(
				malformed.components[0]!.props.entries as unknown as Array<Record<string, unknown>>
			)[0]!.optional = 'yes';
			expect(() => emit(malformed)).toThrow(
				/PropDestructuringEntry has malformed optional flag: label/,
			);

			const orphaned = structuredClone(await golden('s1-render-once.json'));
			delete (
				orphaned.components[0]!.props.entries as unknown as Array<Record<string, unknown>>
			)[0]!.type;
			expect(() => emit(orphaned)).toThrow(
				/PropDestructuringEntry declares optionality without a type annotation: label/,
			);
		});

		/**
		 * `emit()` runs its own copy of the compile oracle, so a lowering that
		 * produces uncompilable Vue never reaches disk. This plants a diagnostic
		 * upstream of the emitter's own check by corrupting a handler body into a
		 * shape Vue's template expression parser refuses.
		 */
		test('when its own output would not compile with an empty diagnostic set', async () => {
			const artifact = structuredClone(await golden('s1-render-once.json'));
			const text = artifact.components[0]!.template[0]!;
			const stamp = (node: Record<string, any>): void => {
				if (node?.kind === 'host' && node.tag === 'p')
					node.children = [
						...node.children,
						{
							kind: 'host',
							id: 'planted',
							tag: 'div',
							staticAttributes: [],
							dynamicBindings: [],
							eventIds: [],
							children: [],
						},
					];
				for (const value of Object.values(node ?? {})) {
					if (!value || typeof value !== 'object') continue;
					if (Array.isArray(value)) value.forEach((entry) => stamp(entry));
					else stamp(value as Record<string, any>);
				}
			};
			stamp(text as unknown as Record<string, any>);
			expect(() => emit(artifact)).toThrow(/did not compile with an empty diagnostic set/);
		});
	});
});

describe('formatEmitted asserts what no formatter is available to enforce', () => {
	test('accepts every emitted golden', async () => {
		for (const [file] of FIXTURES) {
			const source = await emitted(file);
			expect(formatEmitted(source)).toBe(source);
		}
	});

	// CALIBRATION. Each row is a shape the missing formatter would otherwise have
	// normalised away.
	const rejected = [
		['CRLF line endings', (source: string) => source.replaceAll('\n', '\r\n'), /LF line/],
		['a missing final newline', (source: string) => source.trimEnd(), /exactly one newline/],
		['a doubled final newline', (source: string) => `${source}\n`, /exactly one newline/],
		[
			'trailing whitespace',
			(source: string) => source.replace('</script>', '</script> '),
			/trailing whitespace/,
		],
		[
			'space indentation',
			(source: string) => source.replace('\n\tconst ', '\n\t  const '),
			/indents with spaces/,
		],
	] as const;

	for (const [shape, apply, message] of rejected)
		test(`CALIBRATION: rejects ${shape}`, async () => {
			const source = await emitted('S1.vue');
			const mutant = apply(source);
			expect(mutant, `${shape} produced a non-mutant`).not.toBe(source);
			expect(() => formatEmitted(mutant)).toThrow(message);
		});
});
