// @generated by @frameless/angular from AsyncBoard; do not edit.
import { ChangeDetectorRef, Component, inject, Input, type OnInit } from '@angular/core';

@Component({
	selector: 'frameless-async-board',
	template: `
		<form data-scenario="s8">
			<p data-async="ticks">{{ ticks }}</p>
			<p data-async="phase">{{ phase }}</p>
			<p data-async="cancels">{{ cancels }}</p>
			<button type="button" data-action="run" (click)="onH4Click($event)">run</button>
			<button type="submit" data-action="cancel-run" (click)="onH5Click($event)">cancel</button>
		</form>
	`,
})
export class AsyncBoard implements OnInit {
	@Input() ready!: Promise<string>;
	@Input() onTrace!: (name: string, detail: Record<string, unknown>, event: unknown) => void;
	ticks: any;
	phase: any;
	cancels: any;
	ngOnInit(): void {
		this.ticks = 0;
		this.phase = 'idle';
		this.cancels = 0;
	}
	private readonly changeDetector = inject(ChangeDetectorRef);
	async onH4Click(event: any): Promise<void> {
		this.phase = 'pending';
		await this.ready;
		this.ticks = this.ticks + 1;
		this.phase = 'done';
		this.onTrace('run', { phase: 'done' }, event);
		this.changeDetector.markForCheck();
	}
	async onH5Click(event: any): Promise<void> {
		event.preventDefault();
		await this.ready;
		this.cancels = this.cancels + 1;
		this.onTrace('cancel', { cancels: 1 }, event);
		this.changeDetector.markForCheck();
	}
}
