// @generated by @frameless/angular from AttrBoard; do not edit.
import { Component, Input, type OnInit } from '@angular/core';

@Component({
	selector: 'frameless-attr-board',
	template: `
		<section data-scenario="s9">
			<button type="button" data-gate="true" [disabled]="locked" [attr.data-stage]="stage">gate</button>
			<input type="text" data-note="true" [required]="locked">
			<p data-sealed="true">{{ sealed }}</p>
			<p data-steps="true">{{ steps }}</p>
			<ul data-fields="true">
				@for (row of rows; track row.id) {
					<li [attr.data-oracle-attr-key]="row.id">
						<button type="button" [attr.data-field]="row.id" [disabled]="row.off">field</button>
						<button
							type="button"
							[attr.data-seal]="row.id"
							(click)="onH8Click(row, $event)"
						>seal</button>
					</li>
				}
			</ul>
			<button type="button" data-action="lock" (click)="onH9Click($event)">lock</button>
			<button type="button" data-action="unlock" (click)="onH10Click($event)">unlock</button>
		</section>
	`,
})
export class AttrBoard implements OnInit {
	@Input() seed: any;
	@Input() onTrace: any;
	locked: any;
	steps: any;
	rows: any;
	get stage(): any {
		return this.locked ? 'locked' : 'open';
	}
	get sealed(): any {
		return this.rows.filter((row) => row.off).map((row) => row.id).join('+') || 'none';
	}
	ngOnInit(): void {
		this.locked = false;
		this.steps = 0;
		this.rows = this.seed.map((row) => ({ ...row }));
	}
	onH8Click(row: any, event: any): void {
		const next = this.rows.map((entry) => entry.id === row.id ? { id: entry.id, off: !entry.off } : entry);
		this.rows = next;
		this.onTrace('seal', { id: row.id }, event);
	}
	onH9Click(event: any): void {
		this.locked = true;
		this.steps = this.steps + 1;
		this.onTrace('lock', { locked: true }, event);
	}
	onH10Click(event: any): void {
		this.locked = false;
		this.steps = this.steps + 1;
		this.onTrace('unlock', { locked: false }, event);
	}
}
