// @generated by @frameless/angular from TodoMvc; do not edit.
import { Component, Input, type OnInit } from '@angular/core';

@Component({
	selector: 'frameless-todo-mvc',
	template: `
		<section class="todoapp" data-app="todomvc">
			<header class="header">
				<h1>todos</h1>
				<form
					class="new-todo-form"
					data-action="add"
					(click)="onH3Click($event)"
					(submit)="onH3Submit($event)"
				>
					<input
						class="new-todo"
						placeholder="What needs to be done?"
						data-action="new"
						[value]="draft"
						(input)="onH4Input($event)"
					>
				</form>
			</header>
			@if (todos.length > 0) {
				<main class="main">
					<input
						id="toggle-all"
						class="toggle-all"
						type="checkbox"
						data-action="toggle-all"
						[checked]="allDone"
						(change)="onH6Change($event)"
					>
					<label for="toggle-all">Mark all as complete</label>
					<ul class="todo-list">
						@for (todo of todos; track todo.id) {
							<li
								[attr.class]="editing === todo.id ? 'editing' : todo.done ? 'completed' : ''"
								[attr.data-oracle-todo-key]="todo.id"
								[hidden]="filter === 'active' ? todo.done : filter === 'completed' ? !todo.done : false"
							>
								@if (editing === todo.id) {
									<form
										class="edit-form"
										[attr.data-commit]="todo.id"
										(click)="onH10Click(todo, $event)"
										(submit)="onH10Submit(todo, $event)"
									>
										<input
											class="edit"
											[attr.data-edit]="todo.id"
											[value]="editDraft"
											(input)="onH11Input(todo, $event)"
										>
										<button
											type="button"
											class="cancel-edit"
											[attr.data-revert]="todo.id"
											(click)="onH12Click(todo, $event)"
										>cancel</button>
									</form>
								} @else {
									<div class="view">
										<input
											class="toggle"
											type="checkbox"
											[attr.data-toggle]="todo.id"
											[checked]="todo.done"
											(change)="onH14Change(todo, $event)"
										>
										<button
											type="button"
											class="todo-title"
											[attr.data-title]="todo.id"
											(click)="onH15Click(todo, $event)"
										>{{ todo.title }}</button>
										<button
											type="button"
											class="destroy"
											[attr.data-destroy]="todo.id"
											(click)="onH16Click(todo, $event)"
										>x</button>
									</div>
								}
							</li>
						}
					</ul>
				</main>
			}
			@if (todos.length > 0) {
				<footer class="footer">
					<span class="todo-count"><strong>{{ active }}</strong>{{ remainingLabel }}</span>
					<ul class="filters">
						<li>
							<a
								href="#/"
								data-filter="all"
								[attr.class]="filter === 'all' ? 'selected' : ''"
								(click)="onH22Click($event)"
							>All</a>
						</li>
						<li>
							<a
								href="#/active"
								data-filter="active"
								[attr.class]="filter === 'active' ? 'selected' : ''"
								(click)="onH24Click($event)"
							>Active</a>
						</li>
						<li>
							<a
								href="#/completed"
								data-filter="completed"
								[attr.class]="filter === 'completed' ? 'selected' : ''"
								(click)="onH26Click($event)"
							>Completed</a>
						</li>
					</ul>
					@if (completed > 0) {
						<button
							type="button"
							class="clear-completed"
							data-action="clear-completed"
							(click)="onH27Click($event)"
						>Clear completed</button>
					}
				</footer>
			}
		</section>
	`,
})
export class TodoMvc implements OnInit {
	@Input() onTrace!: (name: string, detail: Record<string, unknown>, event: unknown) => void;
	todos: any;
	draft: any;
	next: any;
	filter: any;
	editing: any;
	editDraft: any;
	get active(): any {
		return this.todos.filter((todo) => !todo.done).length;
	}
	get completed(): any {
		return this.todos.filter((todo) => todo.done).length;
	}
	get allDone(): any {
		return this.todos.length > 0 && this.todos.filter((todo) => !todo.done).length === 0;
	}
	get remainingLabel(): any {
		return this.todos.filter((todo) => !todo.done).length === 1 ? ' item left' : ' items left';
	}
	ngOnInit(): void {
		this.todos = [{ id: 't1', title: 'Taste JavaScript', done: true }, { id: 't2', title: 'Buy a unicorn', done: false }];
		this.draft = '';
		this.next = 3;
		this.filter = 'all';
		this.editing = '';
		this.editDraft = '';
	}
	onH3Click(event: any): void {
		this.onTrace('press', { area: 'new-todo' }, event);
	}
	onH3Submit(event: any): void {
		event.preventDefault();
		const title = this.draft.trim();
		const item = { id: `t${this.next}`, title, done: false };
		this.todos = title === '' ? this.todos : this.todos.concat(item);
		this.next = title === '' ? this.next : this.next + 1;
		this.draft = '';
		this.onTrace('add', { id: item.id, title }, event);
	}
	onH16Click(todo: any, event: any): void {
		this.todos = this.todos.filter((entry) => entry.id !== todo.id);
		this.onTrace('destroy', { id: todo.id }, event);
	}
	onH22Click(event: any): void {
		event.preventDefault();
		this.filter = 'all';
		this.onTrace('filter', { filter: 'all' }, event);
	}
	onH24Click(event: any): void {
		event.preventDefault();
		this.filter = 'active';
		this.onTrace('filter', { filter: 'active' }, event);
	}
	onH26Click(event: any): void {
		event.preventDefault();
		this.filter = 'completed';
		this.onTrace('filter', { filter: 'completed' }, event);
	}
	onH27Click(event: any): void {
		const cleared = this.todos.filter((todo) => todo.done).length;
		this.todos = this.todos.filter((todo) => !todo.done);
		this.onTrace('clear-completed', { cleared }, event);
	}
	onH4Input(event: any): void {
		this.draft = event.currentTarget.value;
	}
	onH6Change(event: any): void {
		const done = event.currentTarget.checked;
		this.todos = this.todos.map((todo) => ({ id: todo.id, title: todo.title, done }));
		this.onTrace('toggle-all', { done }, event);
	}
	onH10Click(todo: any, event: any): void {
		this.onTrace('press', { area: 'edit' }, event);
	}
	onH10Submit(todo: any, event: any): void {
		event.preventDefault();
		const title = this.editDraft.trim();
		this.todos = title === '' ? this.todos : this.todos.map((entry) => entry.id === todo.id ? { id: entry.id, title, done: entry.done } : entry);
		this.editing = '';
		this.editDraft = '';
		this.onTrace('commit', { id: todo.id, title }, event);
	}
	onH11Input(todo: any, event: any): void {
		this.editDraft = event.currentTarget.value;
	}
	onH12Click(todo: any, event: any): void {
		this.editing = '';
		this.editDraft = '';
		this.onTrace('revert', { id: todo.id }, event);
	}
	onH14Change(todo: any, event: any): void {
		const done = event.currentTarget.checked;
		this.todos = this.todos.map((entry) => entry.id === todo.id ? { id: entry.id, title: entry.title, done } : entry);
		this.onTrace('toggle', { id: todo.id, done }, event);
	}
	onH15Click(todo: any, event: any): void {
		const opened = event.detail === 2;
		this.editing = opened ? todo.id : this.editing;
		this.editDraft = opened ? todo.title : this.editDraft;
		this.onTrace('edit', { id: todo.id, opened }, event);
	}
}
