// @generated by @frameless/angular from WhitespaceBoard; do not edit.
import { Component, Input, type OnInit } from '@angular/core';

@Component({
	selector: 'frameless-whitespace-board',
	template: `
		<section data-scenario="s6">
			<p data-ratio="true">{{ done }}/{{ total }}</p>
			<p data-glue="true">start{{ done }}{{ unit }}end</p>
			<p data-wrap="true">[{{ note }}]</p>
			<p data-mixed="true">a<b data-emph="true">{{ unit }}</b>z</p>
			<p data-static="true">one two three</p>
			<ul data-lines="true">
				@for (row of rows; track row.id) {
					<li [attr.data-oracle-text-key]="row.id">
						<span [attr.data-pair]="row.id">{{ row.left }}{{ joiner }}{{ row.right }}</span>
						<button [attr.data-widen]="row.id" (click)="onH10Click(row, $event)">widen</button>
					</li>
				}
			</ul>
			<button data-action="tick" (click)="onH11Click($event)">tick</button>
			<button data-action="pad" (click)="onH12Click($event)">pad</button>
		</section>
	`,
})
export class WhitespaceBoard implements OnInit {
	@Input() seed: any;
	@Input() label: any;
	@Input() onTrace: any;
	done: any;
	unit: any;
	note: any;
	joiner: any;
	rows: any;
	get total(): any {
		return this.rows.length;
	}
	ngOnInit(): void {
		this.done = 1;
		this.unit = 'px';
		this.note = this.label;
		this.joiner = '|';
		this.rows = this.seed.slice();
	}
	onH10Click(row: any, event: any): void {
		const next = ` ${row.id} `;
		this.joiner = next;
		this.onTrace('widen', { id: row.id, joiner: next }, event);
	}
	onH11Click(event: any): void {
		this.done++;
		this.unit = 'em';
		this.onTrace('tick', { done: this.done, unit: this.unit }, event);
	}
	onH12Click(event: any): void {
		const padded = ` ${this.note} `;
		this.note = padded;
		this.onTrace('pad', { note: padded }, event);
	}
}
