import { readdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { parse } from 'svelte/compiler';
import type { EnrichedIR } from '@frameless/compiler';
import { dirname, normalize, relative, resolve } from 'pathe';
import { SANCTIONED_SVELTE_IGNORE_CODES } from '../emitter/index.ts';

export type DossierRef =
	// Svelte 5 removed event modifiers; the two IR-5 actions become ordinary
	// in-body statements, and stopPropagation fails closed rather than growing an
	// untested on()-from-svelte/events path.
	| 'frameless-svelte-v1 T002 ruling 4'
	// IR-1 (bindable props) is out of scope on two independent axes, and its
	// failure mode is a DEV-ONLY console warning that passes tests.
	| 'frameless-svelte-v1 T002 ruling 5 (IR-1)'
	// IR-7: purity is never asserted while $derived expects a pure expression.
	// Conservative syntactic guard, not a purity proof.
	| 'frameless-svelte-v1 T002 ruling 5 (IR-7)'
	// IR-4 deferred, version corollary NOT amended: emit only baseline-safe forms.
	| 'frameless-svelte-v1 T002 ruling 3'
	// Warning-free emission with a fixed, sanctioned suppression list.
	| 'frameless-svelte-v1 T002 ruling 6'
	// Qwik's artifact-required policy, transposed: fail closed on persistence.
	| 'T002-qwik-architecture D8'
	// The whitespace layout the template printer depends on, MEASURED at 5.56.8.
	| 'frameless-svelte-v1 T003 measurement 3';

export type GatePolicy = {
	readonly id: string;
	readonly dossierRef: DossierRef;
	readonly requiresArtifact?: true;
};
export type GateViolation = {
	readonly file: string;
	readonly policy: string;
	readonly dossierRef: DossierRef;
	readonly message: string;
	readonly line: number | null;
};
export type GateResult = {
	readonly files: readonly string[];
	readonly policies: readonly GatePolicy[];
	readonly violations: readonly GateViolation[];
	readonly unevaluated: ReadonlyArray<{
		readonly policy: string;
		readonly reason: 'requires-artifact';
	}>;
};

function persistenceArtifactPolicy() {
	const policy = {
		id: 'persistence-render-lowering',
		dossierRef: 'T002-qwik-architecture D8',
	} as const;
	Object.defineProperty(policy, 'requiresArtifact', { enumerable: false, value: true });
	return policy as typeof policy & { readonly requiresArtifact: true };
}

export const SVELTE_GATE_POLICIES = [
	{ id: 'generated-header', dossierRef: 'frameless-svelte-v1 T002 ruling 6' },
	{ id: 'no-legacy-event-directive', dossierRef: 'frameless-svelte-v1 T002 ruling 3' },
	{ id: 'no-bindable', dossierRef: 'frameless-svelte-v1 T002 ruling 5 (IR-1)' },
	{ id: 'no-stop-propagation', dossierRef: 'frameless-svelte-v1 T002 ruling 4' },
	{ id: 'derived-expression-purity', dossierRef: 'frameless-svelte-v1 T002 ruling 5 (IR-7)' },
	{ id: 'sanctioned-svelte-ignore', dossierRef: 'frameless-svelte-v1 T002 ruling 6' },
	{
		id: 'no-inter-sibling-whitespace',
		dossierRef: 'frameless-svelte-v1 T003 measurement 3',
	},
	persistenceArtifactPolicy(),
] as const satisfies readonly GatePolicy[];

const POLICIES = new Map<string, GatePolicy>(
	SVELTE_GATE_POLICIES.map((policy) => [policy.id, policy]),
);
const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const GENERATED_HEADER = '<!-- @generated by @frameless/svelte';

type Node = Record<string, any>;

function violation(
	file: string,
	policy: string,
	message: string,
	line: number | null = null,
): GateViolation {
	return {
		file,
		policy,
		dossierRef: POLICIES.get(policy)?.dossierRef ?? 'frameless-svelte-v1 T002 ruling 6',
		message,
		line,
	};
}

function lineOf(source: string, offset: number | undefined): number | null {
	if (typeof offset !== 'number') return null;
	return source.slice(0, offset).split('\n').length;
}

/** Depth-first walk that never follows the `parent` back-references Svelte adds. */
function walk(value: unknown, visit: (record: Node) => void): void {
	if (!value || typeof value !== 'object') return;
	if (Array.isArray(value)) {
		value.forEach((entry) => walk(entry, visit));
		return;
	}
	const record = value as Node;
	visit(record);
	for (const [key, child] of Object.entries(record)) {
		if (key === 'parent' || key === 'metadata') continue;
		walk(child, visit);
	}
}

// ---------------------------------------------------------------------------
// IR-7
// ---------------------------------------------------------------------------

/**
 * Methods whose whole purpose is to mutate their receiver. Deliberately NOT a
 * list of "calls" - `todos.filter(...)` inside a `$derived` is correct and must
 * stay accepted, which is what stops this policy from degenerating into "reject
 * any call".
 */
const KNOWN_MUTATING_METHODS = new Set([
	'add',
	'append',
	'appendChild',
	'assign',
	'clear',
	'copyWithin',
	'defineProperty',
	'delete',
	'fill',
	'insertBefore',
	'pop',
	'push',
	'remove',
	'removeAttribute',
	'replaceChildren',
	'reverse',
	'set',
	'setAttribute',
	'shift',
	'sort',
	'splice',
	'unshift',
	'write',
]);

/**
 * IR-7 - THE CONSERVATIVE GUARD, NOT A PURITY PROOF.
 *
 * `ExpressionSite.expression` is an arbitrary AST node and the IR never asserts
 * that it is pure, while `$derived` requires a pure, re-runnable expression.
 * Svelte reports a violation as `state_unsafe_mutation` or
 * `effect_update_depth_exceeded`, and some of those are DEV-ONLY - so absence of
 * a red test is not evidence of correctness here. S1's `$derived` is trivial and
 * will always pass, which is exactly why the green it produces is a vacuum.
 *
 * A real purity proof is a compiler-wide change with no forcing case, so this is
 * the decidable subset instead: a syntactic reject-list applied to the EMITTER'S
 * OWN OUTPUT, which converts "silently wrong later" into "loudly wrong at gate
 * time" for the shapes it can see.
 *
 * WHAT IT CANNOT SEE, stated plainly rather than implied:
 *   - mutation performed inside a function the expression CALLS. `$derived(f())`
 *     is accepted no matter what `f` assigns; the walk never leaves the
 *     expression.
 *   - a mutating method this list does not name, including any method on a
 *     user-defined object, and any mutation through a computed member access.
 *   - a getter with a side effect, which is syntactically indistinguishable from
 *     a property read.
 *   - anything reached through `eval`, `Function`, or a dynamic property name.
 * It is therefore SOUND ONLY as a reject-list: a violation is real, a pass is
 * not a proof.
 */
function impureNodes(argument: Node): Array<{ node: Node; reason: string }> {
	const found: Array<{ node: Node; reason: string }> = [];
	walk(argument, (node) => {
		if (node.type === 'AssignmentExpression')
			found.push({ node, reason: `assignment (${String(node.operator ?? '=')})` });
		else if (node.type === 'UpdateExpression')
			found.push({ node, reason: `update expression (${String(node.operator ?? '')})` });
		else if (node.type === 'UnaryExpression' && node.operator === 'delete')
			found.push({ node, reason: 'delete expression' });
		else if (
			(node.type === 'CallExpression' || node.type === 'NewExpression') &&
			node.callee?.type === 'MemberExpression' &&
			!node.callee.computed &&
			node.callee.property?.type === 'Identifier' &&
			KNOWN_MUTATING_METHODS.has(node.callee.property.name)
		)
			found.push({
				node,
				reason: `call to the known-mutating method .${node.callee.property.name}()`,
			});
	});
	return found;
}

function derivedArguments(instance: Node | null | undefined): Node[] {
	const args: Node[] = [];
	walk(instance, (node) => {
		if (node.type !== 'CallExpression') return;
		const callee = node.callee as Node | undefined;
		const isDerived =
			callee?.type === 'Identifier'
				? callee.name === '$derived'
				: callee?.type === 'MemberExpression' &&
					!callee.computed &&
					callee.object?.type === 'Identifier' &&
					callee.object.name === '$derived' &&
					callee.property?.type === 'Identifier' &&
					callee.property.name === 'by';
		if (isDerived && node.arguments?.length) args.push(node.arguments[0] as Node);
	});
	return args;
}

// ---------------------------------------------------------------------------
// policies
// ---------------------------------------------------------------------------

function isWhitespaceText(node: Node): boolean {
	return node.type === 'Text' && String(node.data ?? '').trim() === '';
}

/**
 * A node that survives into the DOM. Comments are stripped by the compiler and
 * whitespace-only text is what this policy is about, so neither counts as the
 * content a whitespace node could be sitting BETWEEN.
 *
 * This also covers a `<script>` block: `parse` lifts it into `root.instance` but
 * leaves the text around it in the fragment, so the emitted file's leading
 * whitespace arrives as two separate whitespace-only nodes at the top of the
 * root fragment. Neither has content before it, so neither is a violation.
 */
function isContentNode(node: Node): boolean {
	return node.type !== 'Comment' && !isWhitespaceText(node);
}

function sourceViolations(file: string, source: string): GateViolation[] {
	const violations: GateViolation[] = [];
	if (!source.startsWith(GENERATED_HEADER))
		violations.push(
			violation(
				file,
				'generated-header',
				`Emitted Svelte source must open with ${JSON.stringify(GENERATED_HEADER)}`,
				1,
			),
		);
	let root: Node;
	try {
		root = parse(source, { modern: true }) as unknown as Node;
	} catch (error) {
		return [
			...violations,
			violation(
				file,
				'generated-header',
				`svelte/compiler could not parse emitted source: ${(error as Error).message}`,
			),
		];
	}
	const instance = root.instance as Node | null;
	walk(root.fragment, (node) => {
		if (node.type === 'OnDirective')
			violations.push(
				violation(
					file,
					'no-legacy-event-directive',
					`Emitted Svelte source uses the legacy on:${String(node.name)} directive; Svelte 5 spells this as an on${String(node.name)} attribute and IR-4 is deferred, so only baseline-safe forms may be emitted`,
					lineOf(source, node.start),
				),
			);
		if (node.type === 'BindDirective')
			violations.push(
				violation(
					file,
					'no-bindable',
					`Emitted Svelte source uses bind:${String(node.name)}; two-way binding is out of scope and its failure mode is a dev-only console warning`,
					lineOf(source, node.start),
				),
			);
		if (node.type === 'Fragment') {
			const nodes = (node.nodes ?? []) as Node[];
			for (const [index, child] of nodes.entries()) {
				if (!isWhitespaceText(child)) continue;
				if (!nodes.slice(0, index).some(isContentNode)) continue;
				if (!nodes.slice(index + 1).some(isContentNode)) continue;
				violations.push(
					violation(
						file,
						'no-inter-sibling-whitespace',
						'Emitted Svelte source has whitespace between two siblings; Svelte keeps it as a single space while JSX drops it, so the emitted text content would diverge from the React and Solid lanes',
						lineOf(source, child.start),
					),
				);
			}
		}
		if (node.type === 'Comment') {
			const data = String(node.data ?? '').trim();
			if (!data.startsWith('svelte-ignore')) return;
			const codes = data
				.slice('svelte-ignore'.length)
				.split(/[\s,]+/)
				.filter(Boolean);
			for (const code of codes)
				if (!(SANCTIONED_SVELTE_IGNORE_CODES as readonly string[]).includes(code))
					violations.push(
						violation(
							file,
							'sanctioned-svelte-ignore',
							`Emitted Svelte source suppresses ${code}, which is not in the sanctioned set [${SANCTIONED_SVELTE_IGNORE_CODES.join(', ')}]`,
							lineOf(source, node.start),
						),
					);
		}
	});
	for (const scope of [root.fragment, instance])
		walk(scope, (node) => {
			if (
				node.type === 'CallExpression' &&
				node.callee?.type === 'MemberExpression' &&
				!node.callee.computed &&
				node.callee.property?.type === 'Identifier' &&
				node.callee.property.name === 'stopPropagation'
			)
				violations.push(
					violation(
						file,
						'no-stop-propagation',
						'Emitted Svelte source calls stopPropagation(); Svelte 5 delegates click/input/change to the root and simulates propagation, and the emitter fails closed on the declared action rather than growing an untested on() path',
						lineOf(source, node.start),
					),
				);
			if (
				node.type === 'CallExpression' &&
				node.callee?.type === 'Identifier' &&
				node.callee.name === '$bindable'
			)
				violations.push(
					violation(
						file,
						'no-bindable',
						'Emitted Svelte source declares a $bindable prop; two-way binding is out of scope',
						lineOf(source, node.start),
					),
				);
		});
	for (const argument of derivedArguments(instance))
		for (const { node, reason } of impureNodes(argument))
			violations.push(
				violation(
					file,
					'derived-expression-purity',
					`Emitted $derived() expression contains a ${reason}; IR-7 never asserts purity, and Svelte reports the violation as state_unsafe_mutation or effect_update_depth_exceeded - some of them dev-only`,
					lineOf(source, node.start),
				),
			);
	return violations;
}

function persistenceViolations(file: string, artifact: EnrichedIR): GateViolation[] | undefined {
	const persistence = (artifact.records as { readonly persistence?: unknown }).persistence;
	if (!Array.isArray(persistence)) return undefined;
	if (persistence.length === 0) return [];
	return [
		violation(
			file,
			'persistence-render-lowering',
			'Svelte emission fails closed on persistence-bearing IR; render-time persistence has no Svelte lowering yet',
		),
	];
}

// ---------------------------------------------------------------------------
// entry points
// ---------------------------------------------------------------------------

async function collectSvelteFiles(root: string, directory: string): Promise<string[]> {
	const absolute = resolve(root, directory);
	const entries = await readdir(absolute, { withFileTypes: true }).catch(
		(error: NodeJS.ErrnoException) => {
			if (error.code === 'ENOENT') return [];
			throw error;
		},
	);
	const files: string[] = [];
	for (const entry of entries) {
		const child = resolve(absolute, entry.name);
		if (entry.isDirectory())
			files.push(...(await collectSvelteFiles(root, relative(root, child))));
		else if (entry.isFile() && entry.name.endsWith('.svelte'))
			files.push(normalize(relative(root, child)));
	}
	return files;
}

export async function discoverGeneratedFiles(
	options: { readonly cwd?: string; readonly directory?: string } = {},
): Promise<string[]> {
	const cwd = resolve(options.cwd ?? PACKAGE_ROOT);
	return (await collectSvelteFiles(cwd, options.directory ?? 'generated')).sort();
}

export function checkSources(
	entries: ReadonlyArray<{
		readonly file: string;
		readonly source: string;
		readonly artifact?: EnrichedIR;
	}>,
): GateResult {
	const violations: GateViolation[] = [];
	const unevaluatedPolicies = new Set<string>();
	for (const { file, source, artifact } of entries) {
		violations.push(...sourceViolations(file, source));
		const artifactViolations = artifact ? persistenceViolations(file, artifact) : undefined;
		if (artifactViolations) violations.push(...artifactViolations);
		else unevaluatedPolicies.add('persistence-render-lowering');
	}
	const result = {
		files: entries.map((entry) => entry.file),
		policies: SVELTE_GATE_POLICIES,
		violations,
	} as unknown as GateResult;
	Object.defineProperty(result, 'unevaluated', {
		enumerable: false,
		value: [...unevaluatedPolicies].map((policy) => ({
			policy,
			reason: 'requires-artifact',
		})),
	});
	return result;
}

export async function checkGeneratedFiles(
	options: { readonly cwd?: string; readonly directory?: string } = {},
): Promise<GateResult> {
	const cwd = resolve(options.cwd ?? PACKAGE_ROOT);
	const files = await discoverGeneratedFiles({ cwd, directory: options.directory });
	const entries = await Promise.all(
		files.map(async (file) => ({ file, source: await readFile(resolve(cwd, file), 'utf8') })),
	);
	return checkSources(entries);
}
