<!-- @generated by @frameless/vue from Panel; do not edit. -->
<script setup lang="ts">
	const props = defineProps(['label']);
</script>

<template>
	<section data-panel>
		<h2 data-panel-label>{{ label }}</h2>
		<div data-panel-body><slot /></div>
	</section>
</template>
